### ISSUE TITLE
Embedded runtimes

### ISSUE THREAD

**Issue by henke37** [munificent/craftinginterpreters#1]
The sentence "In a fully compiled language, the code implementing the runtime gets inserted directly into the resulting executable." isn't what actually happens. Dynamic linking is used and space is saved.

**Comment by munificent** [comment]
>  Dynamic linking is used and space is saved.

In which languages? Most don't statically link the *C* runtime, of course, but from what I can tell, I think they do generally statically link their own language's runtime. Go binaries include the Go runtime, and I think OCaml binaries typically do when compiled to native code.

**Comment by hellerve** [comment]
Just a quick note: Haskell also links its runtime statically—and Haskell libraries, for that matter.

**Comment by munificent** [comment]
Good to know. I'm going to go ahead and close this out because it seems like at least enough languages do this that I'm not totally off base for claiming so. :)
