### ISSUE TITLE
\n in a String is not despecialized

### ISSUE THREAD

**Issue by forax** [munificent/craftinginterpreters#101]
The scanner does not de-specialize '\' character in String.

**Comment by munificent** [comment]
Yes! Lox supports multi-line strings, but no actual string escapes. I know, weird, right? Escapes are certainly useful in a real language, but they aren't that interesting to teach so I left them out.

Multi-line strings were easier to support than prohibit (I tried both ways and found the code a little cleaner for the former) so I left them in. The Scanning chapter says:

> For no particular reason, Lox supports multi-line strings. There are pros and cons to that, but prohibiting them was a little more complex than allowing them, so I left them in. 

🤷‍♂️
