### ISSUE TITLE
Way to support function parameter with default value?

### ISSUE THREAD

**Issue by Morphlng** [munificent/craftinginterpreters#1010]
Hi, I want to add *default parameter* support for Lox function/method, but I'm not sure what is the best way of implementing.

This is what I want:

```javascript
fun multiply(a, b = 1) {
  return a * b;
}

multiply(5, 2); // 10
multiply(5, 1); // 5
multiply(5);    // 5
```

How should I store those values, a map with pair like {position : value}? Then how do I call them since I have to check arity() every time I called. Haven't really thought this through, could really appreciate some advice, Thanks!

**Comment by munificent** [comment]
> How should I store those values, a map with pair like {position : value}?

There's no need for a map, since the keys will always be incrementally increasing integers. I'd just do a list of default values for each parameter (with `nil` as the default default if the function declaration doesn't specify a default).

> Then how do I call them since I have to check arity() every time I called.

Yes, in a dynamically typed language, the simplest implementation will have some runtime overhead for checking the arity and filling in any missing arguments with their default.

**Comment by nocturn9x** [comment]
It's actually easier than you think. In my version I use a tuple that matches 1:1 with the argument list. If the tuple is shorter than the arity of the function, that means that the function has some positional arguments before the keyword ones

**Comment by Morphlng** [comment]
> There's no need for a map, since the keys will always be incrementally increasing integers. I'd just do a list of default values for each parameter (with `nil` as the default default if the function declaration doesn't specify a default).

Thanks! I also saw other people done [that](https://github.com/nathsou/Elox/blob/03629b489449a89daf2983f2dab9010fd15d97bf/src/parser/mod.rs?_pjax=%23js-repo-pjax-container#L334) and it's really easy to follow along (even with another language). Now I'm wondering if there is a way to implement function overloading, I can already see ambiguities even before I start coding. I guess that's why Java didn't have them both :)

Anyway, that's all for this issue, thank you all
