### ISSUE TITLE
Typo in the Code Snippet

### ISSUE THREAD

**Issue by AlissonPQ** [munificent/craftinginterpreters#1012]
Section 3.8.1 of the book, titled Closures, has this code snippet:

```
fun addPair(a, b) {
  return a + b;
}

fun identity(a) {
  return a;
}

print identity(addPair)(1, 2); // Prints "3".
```

I believe the last line should have been typed:

`
print identity(addPair(1, 2)); // Prints "3".
`

Source code file/line: https://github.com/munificent/craftinginterpreters/blame/master/book/the-lox-language.md#L631

**Comment by Runrioter** [comment]
`addPair` is a first-class function.

**Comment by kandersen** [comment]
Duplicate of #852 . _Thought_ I had explained this once already :)

**Comment by munificent** [comment]
Yes, as #852 states, this code is correct (though a little unusual).
