### ISSUE TITLE
Issues with closures in JLox

### ISSUE THREAD

**Issue by Yummy-Pizza** [munificent/craftinginterpreters#1029]
The following code:
```
{
   fun a() {
      b();
   }
   fun b() {
      print "Hello world!";
   }
   a();
}
```
throws an error saying that "b" is undefined. When the Resolver class resolves body of "a" "b" is not yet defined. So "b" is not put in the "locals" map. This code works with global functions because the "lookupVariable" function defaults to looking in the "globals" map. How can this issue be overcome? Languages like JavaScript would handle this perfectly fine.

**Comment by munificent** [comment]
This is by design and is how Lox is intended to behave. Lox doesn't support mutually recursive local functions.

JavaScript handles this using "hoisting", which causes its own problems. You can work around this, like:

```
{
   var b;
   fun a() {
      b();
   }
   fun b_() {
      print "Hello world!";
   }
  b = b_;
   a();
}
```
