### ISSUE TITLE
SIGSEGV and SIGABRT from concatenate

### ISSUE THREAD

**Issue by mcfriend99** [munificent/craftinginterpreters#1040]
I experience a lot of SIGSEGV and SIGABRT from `concatenate()` function in `vm.c` whenever the strings are large. Anyone else experiencing this?? Any ideas?? This also leads to corruption in the GC's `sweep()` function as well while clearing garbages.

Any help??

**Comment by RevengerWizard** [comment]
How much large strings?

**Comment by mcfriend99** [comment]
I'm yet to notice any pattern regarding the string length, but once gc is collected during a call to concatenate, the error happens.

**Comment by mcfriend99** [comment]
This issue has been resolved. Thanks @RevengerWizard for the time. For those interested, the issue was due to having a rouge object in my module system.
