### ISSUE TITLE
Module system in Lox

### ISSUE THREAD

**Issue by bichanna** [munificent/craftinginterpreters#1042]
Thank you for your amazing book :D

I have currently learned to write my interpreter following the book.
But I don't know how to implement a module system like Python. I couldn't find any tutorials on the internet.

I appreciate it if you give me a couple of hints.

**Comment by GalaxianMonster** [comment]
Probably just import the module via filename, search from the std and installed modules directory to the user script directory, check if it does exist and return an error, define module map/class, get all globals from the module then add the globals to the module map/class. Might be wrong though.

**Comment by bichanna** [comment]
Should I do it in the parser or the interpreter? 
I tried it in the parser, but it gets nasty (errors thrown) when there are runtime errors in the source code.

**Comment by GalaxianMonster** [comment]
You may do it on runtime.

**Comment by bichanna** [comment]
So, parsing the imported file is done in runtime?
I don't know how to do that.

**Comment by nocturn9x** [comment]
What do you mean? Just call the compiler from inside the VM. How you implement the import system however is more complicated. Do you go down the C route and just copy-paste like C (in which case there's no runtime support needed but it's a horrible idea) or do you create namespaces like Python does?

**Comment by bichanna** [comment]
Thanks!
