### ISSUE TITLE
Questions about the //> and //< commenting style.

### ISSUE THREAD

**Issue by sloganking** [munificent/craftinginterpreters#1049]
I'm intrigued by this repository's comment style of using ``//>`` and ``//<`` to notate explicitly what lines comments are talking about. Is there a name for this? Is there a tool being used to help create, navigate, format and manage these? Or is that all being done by hand?

I have been working on creating my own commenting scheme I've dubbed [Structured commenting](https://github.com/sloganking/Structured-Commenting) which is similar. I've even [been considering](https://github.com/sloganking/Structured-Commenting/issues/1) the same ``//>`` ``//<`` notation.

**Comment by munificent** [comment]
> Is there a tool being used to help create, navigate, format and manage these?

Yes, these comments are the markers that the build system uses to weave the code snippets into the text. I describe it a little in [this blog post](http://journal.stuffwithstuff.com/2020/04/05/crafting-crafting-interpreters/) (search for "bespoke").
