### ISSUE TITLE
Reference to non-existent file/directory.

### ISSUE THREAD

**Issue by harrisi** [munificent/craftinginterpreters#106]
In util/code_snippets.py, [line 482](https://github.com/munificent/craftinginterpreters/blob/master/util/code_snippets.py#L482), there is reference to your home directory and a file named "Interp.java". This breaks the build process, and it's not immediately clear what the replacement should be. It seems as though I can get it working by replacing the line with something along the lines of `load_file(source_code, "/my/home", "/my/home/java/com/craftinginterpreters/lox/Interpreter.java")`.

I'd be happy to make a PR for correcting this, but I'm not quite sure if a more portable version of the above is a reasonable change. My immediate thought is `load_file(source_code, ".", "./java/com/craftinginterpreters/lox/Interpreter.java")`, which seems to work, but I'm not sure if that's correct or portable enough.

**Comment by munificent** [comment]
Ugh, yeah. Accidentally committed some test code. :)

I have it fixed in a branch for the next chapter, which I should merge into master soon. Hopefully tomorrow. Sorry about that!
