### ISSUE TITLE
"Report" method — not shown in text?

### ISSUE THREAD

**Issue by Spooghetti420** [munificent/craftinginterpreters#1062]
In the [Parsing Expressions](http://www.craftinginterpreters.com/parsing-expressions.html) chapter, the code makes mention of a `report()` function, and uses it in three places, but this function doesn't appear to be defined anywhere? I'm assuming the `private ParseError error` is supposed to be: `private ParseError report`.

**Comment by Sidewinder1138** [comment]
I believe it is defined in Chapter 4, here: http://www.craftinginterpreters.com/scanning.html#error-handling
