### ISSUE TITLE
Chapter 4 End State

### ISSUE THREAD

**Issue by philip-sparks** [munificent/craftinginterpreters#1071]
_And with that, we now have a complete scanner for the entire Lox lexical grammar. Fire up the REPL and type in some valid and invalid code. Does it produce the tokens you expect?_ - End of Chapter 4.7

What is the supposed end state for this chapter? My examples appear to have tokens with memory addresses. Is that what we should have at this stage?

```
> "Hello World"
lox.Token@2a139a55
lox.Token@15db9742
> Hello World
lox.Token@6d06d69c
lox.Token@7852e922
lox.Token@4e25154f
> 1.2 + 2.3
lox.Token@55f96302
lox.Token@3d4eac69
lox.Token@42a57993
lox.Token@75b84c92
> 1 + 2
lox.Token@6bc7c054
lox.Token@232204a1
lox.Token@4aa298b7
lox.Token@7d4991ad
```
Thanks for reading!

**Comment by chrisjbreisch** [comment]
It's been a while since I did this chapter, but I did keep all my code by chapters. I don't think your output is correct, but I can't swear to it without re-reading the chapter.

Here's what I have:

```
> "Hello World"
STRING "Hello World" Hello World
EOF
> Hello World
IDENTIFIER Hello
IDENTIFIER World
EOF
> 1.2 + 2.3
NUMBER 1.2 1.2
PLUS +
NUMBER 2.3 2.3
EOF
> 1 + 2
NUMBER 1 1
PLUS +
NUMBER 2 2
EOF
>
```

**Comment by chrisjbreisch** [comment]
I'm guessing you're missing the toString() bit from Token.

  ```
public String toString() {
    return type + " " + lexeme + " " + literal;
  }
```

**Comment by philip-sparks** [comment]
I have toString() in the Token.java file (see below). I notice that Scanner.java and Lox.java never call toString() so far. Is that correct?

```
package lox;

class Token {
    final TokenType type;
    final String lexeme;
    final Object literal;
    final int line;

    Token(TokenType type, String lexeme, Object literal, int line){
        this.type = type;
        this.lexeme = lexeme;
        this.literal = literal;
        this.line = line;
    }

    public String toSting(){
        return type + " " + lexeme + " " + literal;
    }
}
```

**Comment by chrisjbreisch** [comment]
You have `toSting()`, not `toString()`.

**Comment by philip-sparks** [comment]
Got it! So sorry it was such a simple mistake.

**Comment by chrisjbreisch** [comment]
No worries. Lots of times it just takes a second set of eyes. Good luck and enjoy the rest of the book! I know I did.
