### ISSUE TITLE
Error compiling Fibonacci example 

### ISSUE THREAD

**Issue by jthomas08** [munificent/craftinginterpreters#1078]
I downloaded c source from here and ran the Fibonacci example in chapter 24 on calls and functions and got  compile time errors:
[line 3] Error at '(': Expect ';' after return value.
[line 6] Error at '(': Expect ';' after variable declaration.
[line 7] Error at '(': Expect ';' after value.
[line 8] Error at '(': Expect ';' after value.

any ideas?

**Comment by AfanasiyZaharov** [comment]
Good day, @jthomas08 
I had a similar problem compiling code in this chapter, turns out it was my mistake not adding precedence for TOKEN_LEFT_PAREN (it should be PREC_CALL)
I'm not sure it's related to your problem, cause you've downloaded code from here, but maybe it can be useful

**Comment by jthomas08** [comment]
Thanks for reaching out. The code I got from here has that:
/> Calls and Functions infix-left-paren
  [TOKEN_LEFT_PAREN]    = {grouping, call,   PREC_CALL},

**Comment by jthomas08** [comment]
Never mind..my IDE was caching stale code...its working now

**Comment by AfanasiyZaharov** [comment]
@jthomas08 Its great to hear!
I guess you may close this Issue now

**Comment by jthomas08** [comment]
closed
