### ISSUE TITLE
More nitpicks on "Control Flow"

### ISSUE THREAD

**Issue by munificent** [munificent/craftinginterpreters#110]
> You can prove that by writing a simulator for a Turing machine in your language. Since Turing proved his machine can compute any computable function, by induction, that means your language can too.

That's not by induction, that's by composition or something.

**Comment by harrisi** [comment]
That's deductive reasoning, I believe. Flow of logic:

- A Turing machine can compute any computable function. 
- Your language can simulate (exactly) a Turing machine.
- Your language can be used to compute any computable function, i.e., it is Turing complete.

**Comment by m-ender** [comment]
I believe it's usually referred to as a "reduction". https://en.wikipedia.org/wiki/Reduction_(complexity)

**Comment by munificent** [comment]
I love how if your discourse strays anywhere near math, people start expecting the precise mathematical usage of terms, even when the prose itself is informal. :) By "induction" I didn't necessarily mean to imply "a literal proof by induction" but it certainly could be read that way.

I'll change it to "by extension" which is, I think, suitably informal.
