### ISSUE TITLE
AstPrinter and null Statements

### ISSUE THREAD

**Issue by h2oboi89** [munificent/craftinginterpreters#111]
If there is an issue during parsing due to invalid input there will be a `null` statement in the list of statements that makes up the Parsers output.

Would you recommend handling that by filtering it out before passing that on to the Interpreter or AstPrinter, or should those classes deal with it?

**Comment by h2oboi89** [comment]
I've opted to filter them out as the parser serves as a gatekeeper for classes using it's output and it avoids duplication in the consumers.

Here is my `Parser.parse(tokens)` (JavaScript) as of [Statements and State](http://craftinginterpreters.com/statements-and-state.html)
```js
parse(tokens) {
  this._tokens = tokens;
  this._current = 0;

  try {
    const statements = [];

    while(!this._isAtEnd()) {
      statements.push(this._declaration());
    }

    return statements.filter((s) => s !== undefined);
  }
  catch(error) {
    if(error instanceof ParseError) {
      return undefined;
    }
    else {
      throw error;
    }
  }
}
```

**Comment by munificent** [comment]
I don't usually have the parser filter out the invalid subtrees. Instead, if any error is reported while parsing, the parser returns null (so no syntax tree at all) and the later phases aren't run at all.

I talk a little about that here: http://www.craftinginterpreters.com/parsing-expressions.html#wiring-up-the-parser
