### ISSUE TITLE
Flimsy argument

### ISSUE THREAD

**Issue by HorridModz** [munificent/craftinginterpreters#1115]
I just started reading the book, and I found a slight inaccuracy I figured I'd point out:
On `3.9.1` - `page 30, paragraph 2` (physical book), you discuss why object- oriented programing is still useful. Your main argument is that many people use OOP,  and it's responsible for lots of "successful code", so therefore it must not be "_that_ wrong".
However, I believe this is a flimsy and false argument. Just because a lot of people use something does not mean that it's good.
I'd suggest checking that part out and _possibly_ making some changes, but it's your book! Plus, I'm nowhere near being an expert on programming, language design, or argumentitive writing. I just want to help.

**Comment by munificent** [comment]
I'm OK with leaving this claim in. If millions of people successfully use a thing, it may not be good, but I think the burden of proof lies with anyone claiming that it's bad.
