### ISSUE TITLE
minor typo in "Control Flow"

### ISSUE THREAD

**Issue by tallforasmurf** [munificent/craftinginterpreters#112]
> This is a fascinating corner mathematics

**Comment by fsacer** [comment]
Also wrong comment for second print:
> print "hi" or 2; // "hi".
> print nil and "nope"; // nil.

**Comment by fsacer** [comment]
Wrong highlight:
      "Print      : Expr expression",
tool/GenerateAst.java
in main()
replace 1 line
      "Var        : Token name, Expr initializer", // not changed
      "While      : Expr condition, Stmt body"
    ));

**Comment by munificent** [comment]
It is wrong. I must have got my wires crossed trying to decide if I wanted to show examples of both `or` and `and` or examples of both short-circuiting and not short-circuiting.

**Comment by munificent** [comment]
> "Var : Token name, Expr initializer", // not changed

This actually did change, though the code snippet doesn't make that clear. It used to not have that trailing comma.

**Comment by munificent** [comment]
Fixed: cf1bbdfe961d0e1d30ad5126974a4ffac7588d76
