### ISSUE TITLE
Control Flow typo?

### ISSUE THREAD

**Issue by butlermatt** [munificent/craftinginterpreters#114]
Around line 209 of control flow you have this statement:

> If we attach it to the second if statement, then `whenFalse()` is only
>    called if both `first` and `second` are falsey.

However even your diagram indicates if it was attached to the second statement it would be:
```
if (first) {
  if (second) {
    whenTrue();
  } else {
    whenFalse();
  }
}
```
This means that first must me truthy and second falsey. Not both falsey.

**Comment by mrmrwat** [comment]
Sorry, didn't see this and opened a PR for the same thing (https://github.com/munificent/craftinginterpreters/pull/116), but yes I think you're right.

**Comment by munificent** [comment]
Yeah, you are exactly right. You wouldn't believe how many times I read that sentence and still managed to get it wrong. Thanks for the fix @mrmrwat!
