### ISSUE TITLE
Question about challenge 10.3

### ISSUE THREAD

**Issue by ppk03** [munificent/craftinginterpreters#1151]
Since variable redifinition is allowed in Lox, this code seems to be valid:
```
fun scope(a) { // put "a" into environment
  var a = "local"; // redefine is allowed
}
var a = "global";
scope(a);
```

**Comment by munificent** [comment]
Lox only allows redefining top level global variables, not locals.

**Comment by ppk03** [comment]
This really solve my question, thanks.
