### ISSUE TITLE
Compiling bytecode to assembly

### ISSUE THREAD

**Issue by davidoskiii** [munificent/craftinginterpreters#1163]
I know that there isn't a direct method to do so, but how would you handle compiling to assembly or any other intermediate language from the bytecode interpreter without starting from scratch. And how do other language compilers treat the different flavours of assembly? Do they have a different compiler for each architecture?

**Comment by munificent** [comment]
That's a much bigger topic. :) If you want the answer to that, you'll want to dig into a compiler textbook. I really like Cooper and Torczon's "Engineering a Compiler".

**Comment by davidoskiii** [comment]
Ok, thank you :D
