### ISSUE TITLE
Locals may have errors in its calculations

### ISSUE THREAD

**Issue by defpis** [munificent/craftinginterpreters#1166]
In the chapter "Resolving and Binding", I found that a function will create two scopes: one for the arguments, and another for the function body. 

```java
private void resolveFunction(Stmt.Function function) {
  beginScope(); // Create new scope.
  for (Token param : function.params) {
    declare(param);
    define(param);
  }
  resolve(function.body); // Call visitBlockStmt create new nest scope.
  endScope();
}

// resolve(function.body);
@Override
public Void visitBlockStmt(Stmt.Block stmt) {
  beginScope();
  resolve(stmt.statements);
  endScope();
  return null;
}
```

... -> scope{ function.params } -> scope{ function.body } -> ...

However, in the interpreter code, a function call will only create one environment.

```java
@Override
public Object call(Interpreter interpreter, List<Object> arguments) {
  Environment environment = new Environment(closure); // Create new environment.

  for (int i = 0; i < declaration.params.size(); i++) {
    environment.define(declaration.params.get(i).lexeme,
        arguments.get(i));
  }

  interpreter.executeBlock(declaration.body, environment); // Just use current environment.
  return null;
}
```

So, when we calculate the distance of variable bindings in the enclosure and then try to get the value from the environment, it may cause an error.

A simple solution is to iterate over the function body directly in the resolver:

```java
private void resolveFunction(Stmt.Function function) {
  beginScope(); // Create new scope.
  for (Token param : function.params) {
    declare(param);
    define(param);
  }
  // resolve(function.body); // Call visitBlockStmt create new nest scope.
  for (Stmt stmt : function.body.statements) {
    resolve(stmt);
  }
  endScope();
}
```

**Comment by defpis** [comment]
I am not sure whether it is this mistake or not. If it is another problem, I hope you can help to point it out, thank you very much.

**Comment by JesseReinikka** [comment]
In the original code, function statement is supposed have a list of statements (and not the block statement):

```java
static class Function extends Stmt {
  // ...other code

  final Token name;
  final List<Token> params;
  final List<Stmt> body;  // <- What body is supposed to be.
}
```
And thus, you are supposed to call this function in the Resolver for `Function.body`:

```java
void resolve(List<Stmt> statements) {
  for (Stmt statement : statements) {
    resolve(statement);
  }
}
```

So in other words, your simple solution is what is supposed to happen in the first place! 😄

**Comment by defpis** [comment]
I wrote it step by step in C++, and I may have changed the code along the way to cause the problem. Thank you very much.

**Comment by Ariyn** [comment]
This issue helped me a lot! Thanks for you all!

I don't want to complain about this wonderful project, but I think "block" naming is a little miss.
There is a "block" is BNF in this [chapter](https://craftinginterpreters.com/functions.html#function-declarations), but the other part of book uses name "body".

```
function       → IDENTIFIER "(" parameters? ")" block ;
```

ps. There is both "block" and "block statement". So it's totally my mistake, still it looks like easy to confusing.
