### ISSUE TITLE
Not-a-issue: more website information

### ISSUE THREAD

**Issue by felipetesc** [munificent/craftinginterpreters#1180]
I purchased and received the book yesterday, and I would like to suggest to add to the website at https://craftinginterpreters.com/ a little bit more information, such as:
- a  link to the lox executable, so we can download from there 
- the book's summary, that's missing from Amazon as well - before buying, I wanted to know what I contents I could find inside it, and perhaps opening https://craftinginterpreters.com/contents.html isn't so straightforward  
- perhaps a synthetic description of each chapter with no more than one paragraph for each 
- a link to Wren, since it's important project which you (Robert) are part of, it can be placed inside **About Robert Nystrom**
- maybe links to the correct version of the code, so we ca use craftinginterpreters.com to follow the book when building the contents of the book
- links to alternate lox implementations [Rust](https://github.com/g-s-k/lox-lang) , [Swift](https://github.com/alexito4/slox), [C#](https://github.com/dhitchin/Lox-interpreter)

Other than that, I'll start the second chapter today.
Thanks !

PS: Can you open the discussions section, I feel I am not writing this at the correct place

**Comment by HallofFamer** [comment]
Well I second the idea of opening a ‘discussion’ section, many GitHub repos have that and it’s better than posting everything in ‘issues’ section.

**Comment by munificent** [comment]
Not opening "Discussions" is a deliberate (though admittedly maybe frustrating) choice. I don't really have the time to moderate a forum and I don't think it's a good idea to have an unmoderated forum. I also don't have much time to participate, unfortunately.
