### ISSUE TITLE
Parser incorrectly requires 'fun' keyword for class methods

### ISSUE THREAD

**Issue by outaink** [munificent/craftinginterpreters#1186]
## Description
In Chapter 12.5 "Methods on Classes", there appears to be a bug in the Parser implementation where it incorrectly expects the 'fun' keyword for class methods, although this conflicts with both the language grammar rules and standard Kotlin syntax.

The grammar rules clearly specify:
```
classDecl → "class" IDENTIFIER "{" function* "}" ;
funDecl → "fun" function ;
function → IDENTIFIER "(" parameters ")" block ;
```

This shows that only top-level function declarations require the 'fun' keyword, while class methods should start directly with the identifier.

## Steps to Reproduce
Try to parse valid Kotlin code with class methods that don't use the 'fun' keyword:

```kotlin
class Bacon {
    eat() {
        println("Crunch crunch crunch!")
    }
}
```

## Current Behavior
Parser throws error: "Expect method name"

## Expected Behavior
Parser should successfully parse class methods without requiring the 'fun' keyword, as this is valid Kotlin syntax matching the grammar rules.

## Suggested Fix
Modify the Parser implementation to only require the 'fun' keyword for top-level function declarations, not for class methods. Specifically:

1. In the function parsing logic, check the 'kind' parameter
2. Only consume the 'fun' keyword when parsing top-level functions
3. Start directly with identifier consumption for class methods

**Comment by munificent** [comment]
> although this conflicts with both the language grammar rules and standard Kotlin syntax.

Crafting Interpreters is not about implementing Kotlin. :)
