### ISSUE TITLE
Any hints implementing break and continue?

### ISSUE THREAD

**Issue by fsacer** [munificent/craftinginterpreters#119]
I had trouble implementing break statement. I already added the tokens and statements with zero parameters (maybe there should be some - probably some context). I don't know how you would check if break is within a loop. I thought maybe check the tokens, but that would be tedious. Also I don't know how you would break out of a loop which is visited as another statement. Thought about exceptions but I know that is not the right way. So maybe you can give me some hints for these. Maybe it would be useful to put them in a book too because currently a note in challenge only describes what break is.

**Comment by alexito4** [comment]
I've only implemented `break` you can check what I did here https://github.com/alexito4/slox/pull/6 

There are 2 parts here:

1. Check if it's inside a loop: I've done that at parse time, keeping the levels of nesting for the loops. Not sure if there is a nicer way of doing it.

2. Interpret the break and runtime: 
you mention that exceptions are not the right way, but that's what the book suggests:

> At runtime, a break statement causes execution to jump to the end of the nearest enclosing loop and proceeds from there

That's what I've done, maybe there is a better way. The trick is to throw and exception (or return something that allows your implementation language to pop the stack) and catch it in the while, then just break from the loop in your implementation language. The exception has to be a specific one in order to differentiate from the other "something went wrong, runtime is freaking out" exception 😉 

Hope this helps!

**Comment by fsacer** [comment]
Yeah that's probably the cleanest way to do this but using the exceptions is not right for normal flow. But I guess here you almost have to use them since you need to jump stacks. Thanks for feedback :+1:

**Comment by fsacer** [comment]
Continue seems more challenging because you can't just jump the stack, you need to somehow increment the increments.

**Comment by alexito4** [comment]
Oh btw! I found that Bob already pushed the answer to the repo! Check it here: (careful, **SPOILERS INSIDE**) https://github.com/munificent/craftinginterpreters/commit/9881e1066410bce1afc00090e8ee6ca2fc8f9a5d
He did the Java side of catching the exception a little different that my version, but still looks like exceptions is the way to go.

**Comment by aggsol** [comment]
That still feels wrong as the *exception* should be used for *exceptional* situations not ususal *control flow*. But for ease of understanding for the book examples that shoud suffice.

**Comment by fsacer** [comment]
Well maybe continue would be also helpfull to put in notes even though that was not the task?

**Comment by rkirsling** [comment]
I too feel weird about using an exception, but then this is also how [`return`](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Return.java) is implemented in the upcoming chapter. I'm sure the VM will be different though—we won't even _have_ exceptions. :wink:

@fsacer's right though; `continue` would require `for` to be its own statement type (_or we'd need to introduce "labels" to jump to_). I assume this is why the challenge is just `break`.

**Comment by Thomas-Neill** [comment]
I used Haskell, but this should work in your __filthy__ stateful languages. Just have eval_statement() or whatever return a `Interrupt` instead of being `void`. Then in compound statements, you just need to run a while loop and if any of the subordinates return something that isn't `NoInterrupt`, return it. Then the While code can "catch" a `BreakInterrupt` and return a `NoInterrupt`

**Comment by munificent** [comment]
Seems like everyone's got it all figured out. I agree using exceptions for control flow is a little dirty, but in a recursive tree-walk interpreter like we have in the Java one, I think it's the best way to do it. The C one will be different.

(Though I should point out that implementing break as a challenge in clox is quite a bit more difficult. We won't do that for Lox, but my other language Wren is pretty similar and does support break statements. You can see how it's implemented [here](https://github.com/munificent/wren/blob/master/src/vm/wren_compiler.c#L2970) and [here](https://github.com/munificent/wren/blob/master/src/vm/wren_compiler.c#L2837)).

> Continue seems more challenging because you can't just jump the stack, you need to somehow increment the increments for which you have no idea what they are.

Yes, if we wanted to do continue, then desugaring to a while loop would make that harder. In that case, it would probably be better to have a real For AST node and interpret it directly.

**Comment by gonzispina** [comment]
For me using exceptions to handle flow control smells pretty bad. Using an exception is the most obvious and the easiest to implement. I've came to another solution and that is to create the continue and break statements and set them as higher precedence statementes in block statements:

New semantics of block statements
```
block          → "{" ( breakStmt | continueStmt | declaration* "}" ;
```
I've came into two ways of implementing this, the first one is using tree accumulation which I believe it is quiet annoying to implement at this point and the other one, which is less elegant, is to initialize the break and continue statements while parsing and propagate those as arguments in every child statement: 

Note: I'm using go as the implementation language

ForStatement parser's method
```go
func (p *Parser) forStatement() (*ForStmt, error) {
        ...

        // INITIALIZE THE CONTINUE AND BREAK STATEMENTS
	cont := NewContinueStmt(false) 
	br := NewBreakStmt(false)

        ...
	if p.match(LEFT_BRACE) {
		body, err := p.blockStatement(br, cont) // <- PASS THE CIRCUIT BREAKERS AS ARGUMENTS
		if err != nil {
			return nil, err
		}
		rreturn NewForStmt(initializer, conditional, increment, body, br, cont), nil
	}
        ...
	
	
} 
```

The new signature of the other parser's methods:
```go
statement(br *BreakStmt, cont *ContinueStmt) (Stmt, error)
declaration(br *BreakStmt, cont *ContinueStmt) (Stmt, error)
ifStatement(br *BreakStmt, cont *ContinueStmt) (*IfStmt, error)
blockStatement(br *BreakStmt, cont *ContinueStmt) (*BlockStmt, error)
```

Just to mention another way to implement this  :)

**Comment by ands** [comment]
@munificent I just found this thread and implemented the clox version of the break statement in a slightly different way to the one in Wren:
I use the unused 0xff 0xff bytes in each unpatched jump (both from the exitJump in the loop and from all the break statements) to build an in-place linked list of the statements that need to get patched as soon as patchJump() gets called.
It may be a little bit harder to reason about when looking at the code, but I found it to be a quite elegant way to avoid scanning the whole code within the loop again.

Example for the while loop:
```C
static void addToInPlaceJumpOffsetList(int offset, int jumpAddress) {
	// Skip to end of list. Could be optimized away by directly storing the end of the list in the compiler struct:
	while (true) {
		int next = (currentChunk()->code[offset] << 8) | currentChunk()->code[offset + 1];
		if (next == UINT16_MAX)
			break;
		offset += next;
	}

	int jump = jumpAddress - offset;
	if (jump >= UINT16_MAX) {
		error("Too much code for offset.");
	}

	// Append new offset from previous jump to current jump to the list:
	currentChunk()->code[offset] = (jump >> 8) & 0xff;
	currentChunk()->code[offset + 1] = jump & 0xff;
}

static void patchJump(int offset) {
	// Walk the list and patch all the jumps:
	while (true) {
		int jump = currentChunk()->count - offset - 2;
		if (jump > UINT16_MAX) {
			error("Too much code to jump over.");
		}

		int next = (currentChunk()->code[offset] << 8) | currentChunk()->code[offset + 1];

		currentChunk()->code[offset] = (jump >> 8) & 0xff;
		currentChunk()->code[offset + 1] = jump & 0xff;

		if (next == UINT16_MAX)
			break;

		offset += next;
	}
}

static void breakStatement() {
	consume(TOKEN_SEMICOLON, "Expect ';' after break.");
	int breakAddress = emitJump(OP_JUMP);
	addToInPlaceJumpOffsetList(current->exitJump, breakAddress);
}

static void continueStatement() {
	consume(TOKEN_SEMICOLON, "Expect ';' after continue.");
	emitLoop(current->loopStart);
}

static void whileStatement() {
	int loopStartBackup = current->loopStart; // Stores backup from enclosing loop
	current->loopStart = currentChunk()->count;
	consume(TOKEN_LEFT_PAREN, "Expect '(' after 'while'.");
	expression();
	consume(TOKEN_RIGHT_PAREN, "Expect ')' after condition.");

	int exitJumpBackup = current->exitJump; // Stores backup from enclosing loop
	current->exitJump = emitJump(OP_JUMP_IF_FALSE);
	emitByte(OP_POP);
	statement();
	emitLoop(current->loopStart);

	patchJump(current->exitJump);
	emitByte(OP_POP);

	// Back to the enclosing loop:
	current->loopStart = loopStartBackup;
	current->exitJump = exitJumpBackup;
}
```

**Comment by dmx2010** [comment]
thanks for the discussion, I ended up using loop level to report error if break statement is outside of a loop block, and a BreakException to pop the stack, but with Scala, I am thinking about using implicit to see if I can do better. Will post back.

**Comment by dmx2010** [comment]
for the for loop continue, I created a pseudo ContinueCaptureStmt to wrap the for body to handle the exception there so the increment statement can be evaluated without creating a ForStmt
