### ISSUE TITLE
For loop layout

### ISSUE THREAD

**Issue by h2oboi89** [munificent/craftinginterpreters#121]
For small screens (not as wide) the block about for loops (`Most modern languages have a higher-level looping statement for iterating over arbitrary user-defined sequences. ...`) gets interjected between `I probably don’t need to remind you, but it looks like this:` and `for (var i = 0; i < 10; i = i + 1) print i;`

It would read better if the block came after the example for loop.

**Comment by h2oboi89** [comment]
![image](https://user-images.githubusercontent.com/5531999/28228246-ab61f280-68ab-11e7-98ac-c3c0cb35378f.png)

**Comment by munificent** [comment]
Ah, excellent catch, thanks!
