### ISSUE TITLE
Variables declared inside functions

### ISSUE THREAD

**Issue by kelvyang** [munificent/craftinginterpreters#123]
Is the following really an error? The reference interpreter thinks so, but I can't grasp why.

```
fun foo() { var a = "hello"; print a; }
foo();
```

Result:
```
Undefined variable 'a'.
[line 1]
```

(I'm skipping ahead and trying to implement some of these things on my own)

**Comment by aggsol** [comment]
That is valid lox IMO.

**Comment by munificent** [comment]
Oh, interesting. It works fine if you run that as a script in both jlox and clox. But if you run the jlox REPL and enter each of those as a separate line, you get that error when you try to call `foo()`. 

There must be something weird going on. I'll take a look.

**Comment by munificent** [comment]
OK, I've got a fix for this, but it's in with the other changes I have in flight for the next chapter. This should be fixed when that chapter is done. :)
