### ISSUE TITLE
Answer for 8.1

### ISSUE THREAD

**Issue by iwatakeshi** [munificent/craftinginterpreters#124]
There is a snippet that shows two declarations:

```java
private boolean allowExpression;
private boolean foundExpression = false;
```
However, `foundExpression` is never assigned `true` (or explained where to be assigned `true`). Thus, `parseRepl()` never returns the last expression-statement.

Should `foundExpression` be assigned `true` between [these two lines](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Parser.java#L248-L249)?

**Comment by munificent** [comment]
Ah, yes, looks like I forgot a snippet there. Thanks!
