### ISSUE TITLE
clock() implementation doesn't match the description

### ISSUE THREAD

**Issue by mariosangiorgio** [munificent/craftinginterpreters#125]
The text says:

> So we’ll add clock(), a native function that returns how many seconds — as a floating point value — the interpreter has been running.

But then it's implemented calling [currentTimeMillis](
https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#currentTimeMillis()) which returns

> the difference, measured in milliseconds, between the current time and midnight, January 1, 1970 UTC

**Comment by munificent** [comment]
Oops! Nice catch. I'll fix the prose.
