### ISSUE TITLE
An erroneous image

### ISSUE THREAD

**Issue by werediver** [munificent/craftinginterpreters#133]
> It’s called “recursive descent” because it walks down the grammar. Confusingly, we also use direction metaphorically when talking about “high” and “low” precedence, but the orientation is reversed. In a top-down grammar, you reach the lowest-precedence expressions first because they may in turn contain subexpressions of higher precedence.
>
> ![parsing-expressions/direction.png](https://user-images.githubusercontent.com/922687/29001754-d69b2f78-7a9b-11e7-825a-0250d14874e9.png)
>
> CS people really need to get together and straighten out their metaphors. Don’t even get me started on which direction the stack is supposed to grow.

To my understanding the right column (Higher <-- Precedence --> Lower) should be turned upside down (Lower <-- Precedence --> Higher), otherwise there is no contradiction mentioned in the text (and indeed, higher precedence transformations take place earlier _on ascent_ — i.e. _deeper_ in the parse tree).

**Comment by fsacer** [comment]
That is correct, how didn't I notice that :)

**Comment by munificent** [comment]
Haha, Oh, God, you're right. I had this illustration correct originally and had to redraw it to fix #115. In the process, I got the order backwards. :(
