### ISSUE TITLE
Clarification in lambda solution - Chapter 10, challenge 2

### ISSUE THREAD

**Issue by alexito4** [munificent/craftinginterpreters#138]
Hi!
I just implemented the challenge 2 of chapter 10, adding support for anonymous functions or lambdas. I write here the mistakes I made because maybe is worth adding some detail into the proposed solution.

**I will describe what my brain was trying to do, so if you don't want the challenge spoiled stop here ;)**

After reading the proposed solution https://github.com/munificent/craftinginterpreters/blob/master/note/answers/chapter10_functions.md I think it would be nice to clarify what the implementation of `visitFunctionExpr` in the interpreter should be. 

In my mind I was trying to execute the function but I couldn't figure out how, because the parameters there are just Tokens. Furthermore, because I was trying to execute it I was also trying to understand why I had to repeat the execution code that we already have in `visitCallExpr`. 
Some minutes later I realised my mistake. `visitFunctionExpr` is not similar to `visitCallExpr` but to `visitFunctionStmt`. It doesn't have to execute the function but pass it around creating a Function object, like `visitFunctionStmt` does. The difference is that one saves the function in the environment and the other just returns it (stmt vs. expr).
With that the rest was easy, the parameter to argument resolution made sense now because the `visitCallExpr` takes care of it. 

Silly me :P 

*btw, you know how exciting it is to see lambdas working?! It always seems one of those dark feature of a language, and in the end is quite easy to implement :)*

**Comment by munificent** [comment]
> btw, you know how exciting it is to see lambdas working?!

I do! The first time I implemented them I felt exactly the same way! :D

**Comment by alexito4** [comment]
Sorry to raise this again but I think I missed something 😅
While implementing "Methods on classes" when modifying `lox/Interpreter.java visitClassStmt()` to include

```
for (Stmt.Function method : stmt.methods) {
      LoxFunction function = new LoxFunction(method, environment);
      methods.put(method.name.lexeme, function);
}
```

I didn't have a LoxFunction constructor that accepted a Stmt.Function but I have one that accepted a Expr.Function. I went down a rabbit whole to figure out what happened, I saw how in some placed the book accesses `declaration.parameters` but I was not able to do that because my Expr.Function didn't have the parameters so I always accessed the ones in the Stmt via `declaration.function.parameters`.
Now I see that Expr.Function shouldn't exist at all https://github.com/munificent/craftinginterpreters/blob/master/note/answers/chapter11_resolving/4/com/craftinginterpreters/tool/GenerateAst.java#L15 ! 😂
At this moment I don't know if I came up with the Expr.Function on my own by mistake or if it was on the book at some point and had to be removed later and I missed that :S I will investigate further ;) 
But just to let you know that this is probably the cause of my confusion in the original post of this issue ;)

**Comment by munificent** [comment]
> At this moment I don't know if I came up with the Expr.Function on my own by mistake or if it was on the book at some point and had to be removed later and I missed that :S I will investigate further

In the book it's always Stmt.Function, but if you tried to get lambdas working at some point, the logical thing would be for you to have moved it over to Expr instead. Glad you got it sorted out! :)
