### ISSUE TITLE
Some typos in chapter 11

### ISSUE THREAD

**Issue by m-ender** [munificent/craftinginterpreters#144]
Sorry, I didn't remember to write down *where* most of these appear, but I'm sure you can Ctrl+F them.

- "We tend to think consider all of the code"
- "Out variable resolution pass works like"
- Sidenote at the end of 11.2.1 overlaps instructions next to first code block in 11.3. Same with the first sidenote in 11.4
- "unilkely"
- "When we step into the function’s body, we also bind its parameter into that scope." It reads to me like "that" scope refers to the scope in which the function is declared, but I think you mean the function's own scope (which is referenced *two* sentences before this one). Maybe I'm misunderstanding something as well, but you might wanna double check that this says what you want it to say.
- "where interpreter can find the variable’s value"
- "I felt that coupling that first-hand"
- "It walks a fixed number of enviroments"
- And finally, in some places it felt like you're inconsistently capitalising "environment". I assume you're trying to go for a distinction between the general concept of "environment" and the specific class "Environment" you've implemented, but for some usages of the word it seemed off.

Great chapter, as usual! :)

**Comment by harrisi** [comment]
- [x] "We tend to think consider all of the code"
- [x] "Out variable resolution pass works like"
- [ ] Sidenote at the end of 11.2.1 overlaps instructions next to first code block in 11.3. Same with the first sidenote in 11.4
- [ ] "unilkely"
- [ ] "When we step into the function’s body, we also bind its parameter into that scope." It reads to me like "that" scope refers to the scope in which the function is declared, but I think you mean the function's own scope (which is referenced two sentences before this one). Maybe I'm misunderstanding something as well, but you might wanna double check that this says what you want it to say.
- [x] "where interpreter can find the variable’s value"
- [ ] "I felt that coupling that first-hand"
- [x] "It walks a fixed number of enviroments"
- [ ] And finally, in some places it felt like you're inconsistently capitalising "environment". I assume you're trying to go for a distinction between the general concept of "environment" and the specific class "Environment" you've implemented, but for some usages of the word it seemed off.

I found all the marked ones (and one not mentioned here while looking for one of these). I couldn't find the others or I felt they were fine. I'm not sure what to do about the overlapping aside(s) covering the filename for a code snippet.

**Comment by m-ender** [comment]
"unilkely" was already fixed, and "that coupling that" appears in the side note in 11.4.1.

**Comment by munificent** [comment]
OK, that should cover the rest of those. Thanks for the help, @harrisi, and for the bug, @m-ender!
