### ISSUE TITLE
Synchronization concerns.

### ISSUE THREAD

**Issue by rkirsling** [munificent/craftinginterpreters#146]
While playing around with parser errors in my port, I noticed two issues in `synchronize`:

1. While clox makes use of the problematic token, jlox throws it out by immediately `advance`-ing.

    As a result, clox correctly reports two missing semicolons for the following, but jlox misses one:
    ```js
    var x = 1
    var y = 2
    ```

2. Blocks are statements too, so shouldn't we keep track of braces?

    As it stands, jlox/clox report this `}` as extraneous:
    ```js
    var x = 1
    {
      var y = 2;
    }
    ```

    Similarly, they report this `}` as missing:
    ```js
    {
      var x = 1
    }
    var y = 2;
    ```

    I find this to be an awful waste since it's so easy to fix! All we need to do is:
    - Recognize `LEFT_BRACE` alongside the rest of the statement openers.
    - Add a boolean parameter `inBlock` to control whether `RIGHT_BRACE` is recognized/ignored.

All in all, I'm rather impressed by how well "panic mode" seems to work, in spite of its simplicity. :smile:

**Comment by rkirsling** [comment]
**Follow up:**

While the above works swimmingly for synchronizing statements in a block, we'll need an additional mechanism for synchronizing methods in a class body.

For instance, one would like to report errors at the extraneous / missing semicolons below:
```js
class Foo {
  one() { print 1; };
  two() { print 2 };
}
```
(_We surely don't want to forget that we're still inside a class body that needs to be `}`-terminated, and even if a method is malformed, it'd be nice to report any issues we find inside its body block._)

To achieve this, we can add the `try`-`catch` from [`declaration()`](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Parser.java#L61) around each [method parse](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Parser.java#L94), except with a different synchronize function. This new function should advance until the next token is:
- `RIGHT_BRACE`, in which case it promptly returns.
- `LEFT_BRACE`, in which case it calls `block()`, throws away the result, and returns.

Et voilà. 🥞

**Comment by munificent** [comment]
Yes! This is all good stuff. There is a lot of low hanging fruit when it comes to error recovery. But, also, there is, like, a *lot* of fruit in general. You can spend a ton of time adding better and better error recovery and it's hard to decide where to stop. For a real production parser, the best answer is to often add a whole lot. But, for the book, I want to keep it as simple as possible. (The book is already long enough as it is!) So I think I'll leave it where it is.

**Comment by rkirsling** [comment]
That's fair; do note that very first point is a discrepancy between jlox and clox though. 😅
