### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by colms** [munificent/craftinginterpreters#156]
- "EBNF" acronym is used - This was previously used in the "Representing Code" chapter (where it was linked to Wikipedia. I think it might be worth adding this term to the glossary if one is later created.
- "It stores the callee ..." => "The call stores the callee ..." to help reduce ambiguity. If you make this change, double check to be sure "It" really does refer to "The call".
- I can't quite parse this sentence: "That stuff does matter, of course, but if you’re just trying to tell if your optimization to, say, arithmetic made a difference, it’s all noise."
- nitpick - it feels like punctuation is missing before the "(1)" - "It’s syntactic sugar for two distinct steps (1) creating a new function object and (2) binding ..."
- "The call() method above does that." - Be careful for when this is transferred to paper and that `call()` method is on another page and no longer "above". After reading this, I did a quick: `book$ grep -rni "above"` and found some potential offenders (I know they're not all contained within this chapter but I don't want to create another issue):
  - evaluating-expressions.md:122:since that's a superclass of all of the above types.
  - parsing-expressions.md:129:    in the above example. 
  - scanning.md:657:keyword, then the former wins. This is also why we tacitly assumed above that
  - scanning.md:805:    Lua avoids the `return` problem above by requiring a `return` statement to
  - resolving-and-binding.md:130:execution of the program. Our interpreter so far *mostly* implements the above
  - resolving-and-binding.md:491:    *global* one. In other words, the above declaration desugars to:

I'm mentioning these here in case you want to change them but there's a trade off here. It reads well to use "above" so it might be worth leaving it as is until you're totally finished the typesetting etc. and only then changing the ones that genuinely can't use "above" anymore. On the other hand, changing that late into the process may move other stuff around. 
- "Our functions are pretty full-featured, but there is one loose end to tie up. In fact, it’s a big enough tangle that we’ll spend most of the next chapter unknotting it, but we can get started here." - This might be my silliest nitpick to date but ... first it's a loose end that we'll have to tie but the next sentence says we're going to try to untie it. I'll see myself out.

**Comment by munificent** [comment]
Awesome, thanks! I did most of the things.
