### ISSUE TITLE
Forgotten word in 2.3 - "Compilers and Interpreters"

### ISSUE THREAD

**Issue by eirikvaa** [munificent/craftinginterpreters#157]
I just read the following sentence

> Conversely, when say an implementation “is an interpreter”, we mean it takes in source code and executes it immediately. It runs programs “from source”.

I'm guessing it should be *Conversely, when **we** say an implementation "is an interpreter" (...)*? I'm not fluent in English, though, so apologies if it's actually correct.

**Comment by munificent** [comment]
Nice catch!
