### ISSUE TITLE
"A Unified Theory of Garbage Collection" link is broken

### ISSUE THREAD

**Issue by eirikvaa** [munificent/craftinginterpreters#158]
As the title explains, the link is broken. This is under 3.2.2 - Automatic memory management.

**Comment by rkirsling** [comment]
It resolves for me—maybe the site was undergoing maintenance?

**Comment by eirikvaa** [comment]
That might be it, because it works now.

**Comment by billti** [comment]
I tried yesterday and today, and got "forbidden" both times.

![image](https://user-images.githubusercontent.com/993909/62498012-9a19c880-b792-11e9-90ba-15ec1d000fa9.png)
