### ISSUE TITLE
Funny sentence in the classes chapter

### ISSUE THREAD

**Issue by mariosangiorgio** [munificent/craftinginterpreters#161]
> We could silently return some dummy value like nil, but my from languages like JavaScript is that masks bugs more often than it does anything useful

**Comment by dbarisakkurt** [comment]
There is also a typo in Properties on Instances section. I didn't open an issue for this trivial thing. "Every instance is a open collection of named values." should be "... is an open collection..."

**Comment by mchlrhw** [comment]
I got that, don't worry :wink: (https://github.com/munificent/craftinginterpreters/pull/162/commits/c57953e3593e890c51f3f1797aecfec71bf78926)
