### ISSUE TITLE
'=' missing in classes chapter?

### ISSUE THREAD

**Issue by sauer2** [munificent/craftinginterpreters#164]
In 12.4:

`jane.name "Jane";`

Same thing appears in the following, longer example.

**Comment by harrisi** [comment]
This was actually fixed in ef7d585aae87466e152aa4eeab00f71a3349ec9e. It seems like the website just hasn't reflected these changes yet.

**Comment by munificent** [comment]
Yeah, I'll try to push a new version of the site tonight. Thanks for the reminder. :)
