### ISSUE TITLE
12.6.1: redundant print in listing?

### ISSUE THREAD

**Issue by sauer2** [munificent/craftinginterpreters#165]
```
class Foo {
  init() {
    print this;
  }
}

var foo = Foo();
print foo.init();
```

**Comment by harrisi** [comment]
The purpose of that last `print` statement is to highlight what a call to `SomeClass.init()` returns - which is `nil`. At the end of the section, after the necessary changes have been made, that print statement will print "Foo instance" instead.

**Comment by munificent** [comment]
Yeah, as @harrisi says, this is deliberate (though maybe not very obvious).
