### ISSUE TITLE
Missing information about status.

### ISSUE THREAD

**Issue by jibal** [munificent/craftinginterpreters#17]
The document is copyright 2015 but only has the first 4 chapters. The rest say "coming soon!" but that's obviously not true. Please do your readers a favor and include information about the actual status and progress of this book and when they can realistically expect to see the rest of it. As it is, reading this is a  waste of time when so much of the document is missing. Also it's a waste of time to post issues about the content, which I had intended to do.

**Comment by mleonard87** [comment]
Looking at the commit history in this repo seems to suggest its being pretty actively worked on and that the year in the footer is simple a mistake or outdated. See #4

**Comment by jibal** [comment]
What part of "only has the first 4 chapters" don't you understand?

**Comment by louispotok** [comment]
@jibal 
First, you're wrong: in the last three weeks I see commits for the outline and drafts 1-4 of the Scanning chapter. (see eg [here](https://github.com/munificent/craftinginterpreters/commit/127eed2ded56590755ec006a653edbdd6e075534#diff-134f25af7022d17c53fcee6070184c7b).) 

Second, you wrote this in an extremely aggressive way -- completely uncalled for and quite rude. This is someone's side project, which they are providing to you free of charge. If you think it could be improved, you can either forget that it exists or provide *constructive* feedback.

**Comment by mleonard87** [comment]
@louispotok Agreed. I just didn't want anyone reading the book to end up here an think the project was already abandoned which is why I commented.
I also believe that the first 4 chapters alone are worth a read even if the rest of the book did not get finished. I've learnt several things I did not already know and the style of writing is very well suited to me.

**Comment by munificent** [comment]
> The document is copyright 2015

The first commit is from December 27th, 2014. Copyright dates established when the work was *first* created, not when it was last updated.

> only has the first 4 chapters.

I worked on it off and on through 2015. Starting on June 30th of last year, I have worked on it every single day up until today, which you can see by looking at the log:

https://github.com/munificent/craftinginterpreters/blob/master/note/log.txt

The code for the entire book is complete, tested, and split into chapters (that's what all the funny-looking comments in the source are for). If you run:

```sh
make
make chapters
make c_chapters
./util/test.py
```

It will run the tests for each version of the interpreter as it exists at the end of each chapter.

The build script that weaves the code snippets in with the text is working, which is quite a bit of effort. As is the design of the site, the CSS, and the templates.

Sorry you seem to be having a bad day.

**Comment by jibal** [comment]
I did provide constructive criticism, and everyone here has been quite rude to me. Good luck with that. Over and out.

**Comment by mleonard87** [comment]
Thanks for the update @munificent. Loving the book so far and I'm looking forward to the next chapters!
