### ISSUE TITLE
Superfluous word in 12.5 - This

### ISSUE THREAD

**Issue by eirikvaa** [munificent/craftinginterpreters#171]
I just read the following sentence:

> Reusing our environment code for implementing `this` also takes care of interesting cases where methods and functions and interact, like: (...)

The *and* between **functions** and **interact** seems superfluous. Maybe it should read as *(...) where methods and functions interact, like: (...)*?

**Comment by munificent** [comment]
Yup, @mchlrhw sent a fix for this. :)
