### ISSUE TITLE
Parameter with same name as function

### ISSUE THREAD

**Issue by kelvyang** [munificent/craftinginterpreters#173]
What should the behavior of this be?

```
fun foo(a, foo) { return foo; }
print foo(5, 6); // prints "foo"
```

**Comment by munificent** [comment]
It *should* print 6. Is your version of the interpreter doing something different?

**Comment by kelvyang** [comment]
You're right. It worked after I recompiled; must've been fixed. Thanks!

**Comment by munificent** [comment]
\o/
