### ISSUE TITLE
Sidenote on running `GenerateAst` in Ch5

### ISSUE THREAD

**Issue by whostolemyhat** [munificent/craftinginterpreters#181]
I'm not that familiar with Java, and my IDE didn't allow me to run the `GenerateAst` file from within it, so a sidenote showing how to compile and run the script in Chapter 5 would be handy :)

eg
```
javac com/craftinginterpreters/tool/GenerateAst.java
java com.craftinginterpreters.tool.GenerateAst ./com/craftinginterpreters/lox
```

**Comment by munificent** [comment]
This isn't a bad idea, but I worry it opens a can of worms. I don't want to have to go into details like what the current working directory should be. Then when we get to clox, I definitely don't want to get mired in details of how to compile and run the C code.

Also, pragmatically, this doesn't fit in an aside. :( It is annoying when you get stuck on this, but it might be better to let readers muddle their way through.
