### ISSUE TITLE
Overload to resolve() undefined for a long time

### ISSUE THREAD

**Issue by shasta9** [munificent/craftinginterpreters#183]
In 11.3.2 in VisitVarStmt() you introduce the overload Resolve(Expr expr) when you call Resolve(stmt.Initializer).  You define the other two functions, Declare and Define, in the same section but the definition of the Resolve() overload doesn't appear until 11.3.4 which is a long time for the compiler to be complaining...
I'm following along in C#, hence the Capitals for function names.  I'm learning a lot about a language I've been using every day for years!

**Comment by munificent** [comment]
Ah, good call! I moved it up some.
