### ISSUE TITLE
Error message in parser: function argument count check

### ISSUE THREAD

**Issue by ksceriath** [munificent/craftinginterpreters#187]
Error message logged in finishCall does not match up with the condition.
if (arguments.size() >= 8) {
          error(peek(), "Cannot have more than 8 arguments.");
        }

**Comment by silmeth** [comment]
There’s no actual mismatch.

This condition is checked just before parsing new argument. So if current `arguments.size() == 8` it means that after this iteration it would have 9 elements (more than 8), and thus error needs to be reported.

So what this check actually has semantics of ‘do we already have at least 8 arguments at this point? If so, we cannot keep adding new ones and need to print error to the user that they have provided more than 8’.

Identical check is present later when checking parameter count for function declaration.

**Comment by ksceriath** [comment]
We are checking this condition only after acknowledging that there is an additional parameter to be added to the current parameter list.
This is a non-issue and a mistake on my part - closing this,

**Comment by munificent** [comment]
Thanks for figuring this out amongst yourselves! :D
