### ISSUE TITLE
An introductory chapter for JIT.

### ISSUE THREAD

**Issue by btwael** [munificent/craftinginterpreters#192]
For someone like me, who been playing with compilers/interpreters for years, I really hope that you add a chapter about JIT implementation for VM.

Your book is the book I wished I had when I started creating programming languages when I was 17 years old.

**Comment by aggsol** [comment]
@btwael Would be so kind to tell the sources you used in the past for learning about VM and JIT that you would still recommend?

**Comment by btwael** [comment]
@aggsol One of the first ressource I used at the time was a website that introduced PEG.js called "Nathan's University PL101" (not available anymore). 
I used what I learned there to create a (python/coffeescript)-inspired language called [btwael/mammouth](https://github.com/btwael/mammouth), the first implementation of the language has a lot of bugs (and not well designed). So I started learning about how to handwrite parsers and scanners.
The first interpreter I developed was a for Javascript (and written in Javascript) that introduce keywords similar to "await" (in dart and modern languages, the keyword block the execution until a result is available).
The next challenging step was starting a language project developed in C/C++, the goal in first was developing a VM, but when I discovered LLVM (a compiler infrastructure), I decided to create a compiled language (The idea of the language started 2 years ago, but the development started for about 6 months).

I would like also to share with the most difficult challenge to solve while developing a language are

- Memory management (if you're implementing using C/C++, you have nodes, tokens...)
- Error reporting (generally compilers must be able to report many errors at once, so you must design a mechanism that allow the scanner or the parser to continue his work even if there is an syntax error  in the input source code)
- Compilation driver

**Comment by munificent** [comment]
I would love to write about JITs, but (1) this book is already on track to be >200k, which is plenty big enough and (2) I've never actually written one, so I'm probably not the best qualified person to cover. This will have to wait for another book, unfortunately.
