### ISSUE TITLE
Typo in 14.5.3

### ISSUE THREAD

**Issue by fmdkdd** [munificent/craftinginterpreters#196]
we specify what **it’s** operands look like 

(I wanted to submit a PR directly, but it seems the code from the repository isn't in sync with the website anymore?

Thank you for a very nice reading, in any case)

**Comment by munificent** [comment]
It should be mostly in sync, but the site may be a little out of date while I'm working on the next chapter. I'll publish all of the latest changes soon. Thanks for the bug report!
