### ISSUE TITLE
Unable to run Lox breakfast sample code

### ISSUE THREAD

**Issue by mleonard87** [munificent/craftinginterpreters#20]
I'm trying to do challenge 1 at the end of chapter 3 and write a sample Lox program and run it using you example interpreter. I got the interpreter compile very easily with `make` as indicated in #8.

If I do a basic example with a class (Breakfast - just like your samples) it works fine and I get the expected output of `Enjoy your ham and toast, Dear Reader` but when I try and do inheritance (Brunch) I get the error `Only instances have fields. [line 3]`. I'm overriding both `serve` and `init` and in the overriding `init` I call super.init.

Working code:
```
class Breakfast {
  init(meat, bread) {
    this.meat = meat;
    this.bread = bread;
  }

  serve(who) {
    print "Enjoy your " + this.meat + " and " + this.bread + ", " + who;
  }
}

var baconAndToast = Breakfast("ham", "toast", "tea");
baconAndToast.serve("Dear Reader");
```

Code that errors:
```
class Breakfast {
  init(meat, bread) {
    this.meat = meat;
    this.bread = bread;
  }

  serve(who) {
    print "Enjoy your " + this.meat + " and " + this.bread + ", " + who;
  }
}

class Brunch < Breakfast {
  init(meat, bread, drink) {
    super.init(meat, bread);
    this.drink = drink;
  }

  serve(who) {
    print "Enjoy your " + this.meat + " and " + this.bread + " and " + this.drink + ", " + who;
  }
}

var baconAndToastAndTea = Brunch("ham", "toast", "tea");
baconAndToastAndTea.serve("Dear Reader");
```

Any help here would be much appreciated.

**Comment by munificent** [comment]
Oh, wow, great catch. There was a bug in jlox resolving `this` inside a method called from a `super` call. It's fixed now (and tested).

Thanks!

**Comment by codermet** [comment]
How to run the lox code?
