### ISSUE TITLE
Missing word "of" in Chapter 4?

### ISSUE THREAD

**Issue by Zero-1729** [munificent/craftinginterpreters#200]
In the introductory line after the quote:

> "The scanner takes in raw source code as a series characters and groups it into meaningful chunks ..."

It seems the word "**of**" is missing between the words "`series`" and "`characters`". Making it as follows:

> "The scanner takes in raw source code as a series of characters and groups it into meaningful chunks ..."

**Comment by munificent** [comment]
Oh, dear. How did I manage to miss that, and in the very first paragraph! Thanks for pointing that out!
