### ISSUE TITLE
Table in 14.3.1 is oddly typed

### ISSUE THREAD

**Issue by rkirsling** [munificent/craftinginterpreters#202]
This table near the end of 14.3 is doing some interesting type conflation:
![image](https://user-images.githubusercontent.com/2172590/37257645-98802aa2-2529-11e8-9dc2-889f8978f4bf.png)
Looks like the columns are labelled to describe `realloc`'s two parameters, but seeing `1000` in a column labelled "pointer" makes the reader wonder if it's a memory address.

The intent of the `NULL`s is clearer; I think it would suffice to rename the first column "existing size".

**Comment by munificent** [comment]
Yeah, that is weird. I think I went through a couple of iterations on that table, and I seemed to have stopped halfway to something that makes sense. I think I have it better now.
