### ISSUE TITLE
Question about invalid syntax in Chapter 6

### ISSUE THREAD

**Issue by TypeMonkey** [munificent/craftinginterpreters#204]
Hello,

After finishing the Chapter, I was doing some test cases on some invalid expressions. Notably, I was doing a case where tokens of the same type appeared in sequential order, such as:

" 3 3 3" 
"3 + 5 3 "

In the case of the second example, I got 8 (I kinda skipped ahead and did a makeshift traversal with my nodes). And after printing out the contents of my abstract syntax tree, the very last "3" wasn't present.

So this is where I'm at a loss. How do I report this kind of invalid sequence of tokens? Does this type of error reporting belong to the parser at all?

Apologies if I missed something in the chapter. It's a really great book and I've just been jumping around  haha.

**Comment by munificent** [comment]
You didn't miss something in the chapter. :)

You stumbled onto a quirk of the in-progress implementation that I sort of don't mention. Once we get to the point where we are parsing full programs — lists of statements, this issue goes away. The full parser keeps looping until it hits an EOF token, so it ensures it fully consumes the input and reports an error on any unexpected tokens.

But in the early chapters, when we just parse a single expression, the parser just stops once it hits a complete expression and ignores any tokens that may follow it. I thought about adding a little temporary code to check for this case, but never convinced myself it was worth it.

Good job testing the error handling on your parser! That's a good skill for a PL person to have. :)
