### ISSUE TITLE
Section 14.3.1: reallocate can leak memory

### ISSUE THREAD

**Issue by ingramj** [munificent/craftinginterpreters#206]
The behavior of `realloc(ptr, 0)` with a non-null pointer is implementation defined.  It's equivalent to `free(ptr)` on Linux, but according to the man page on macOS:

> If size is zero and ptr is not NULL, a new, minimum sized object is allocated and the original object is freed.

On my system, that's 16 bytes per call to `FREE_ARRAY`, according to the [Leaks Instrument](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/FindingLeakedMemory.html#//apple_ref/doc/uid/TP40004652-CH81-SW1). Explicitly calling `free(previous)` when `newSize` is 0 fixes the leaks.

**Comment by rkirsling** [comment]
Wow, not only that, but according to [this page](http://en.cppreference.com/w/c/memory/realloc#Notes):
> Support for zero size is deprecated as of C11 DR 400.

**Comment by munificent** [comment]
Thank you for bringing this to my attention! Not only was the code wrong, but the text around it was a mess too. I don't know what I was thinking when I wrote that. It should be clearer now (and not leak memory!).
