### ISSUE TITLE
A Virtual Machine – Add challenge to minimize popping?

### ISSUE THREAD

**Issue by munificent** [munificent/craftinginterpreters#210]
zero_operand on reddit [notes]:

> Please stop popping so much!
>
> For your unary negation operator, just modify the top of the stack in place.
>
> For your binary arithmetic operators, pop one element then use it modify the new top of the stack in place.
>
> The number of pops should equal the difference in stack lengths, before and after the operation. 2 elements -> 1 element, 1 pop.

I'm not sure if I want to make that change to the main code, since it makes it a little more complex and a little less clear, but it would be a good challenge for the chapter.

**Comment by rkirsling** [comment]
Note that in C++, rather than adding complexity, this basically [comes for free](https://github.com/rkirsling/cclox/blob/master/src/vm.cpp#L41-L43) thanks to `vector::back`.

I think if you added a `peek` alongside `push` and `pop`, you could get away without sacrificing clarity!

**Comment by cseidman** [comment]
I'm not sure that this would make any real difference in performance. Popping is nothing more that referencing a location on the stack, so replacing a value in place vs. "popping" saves you almost nothing. That said, there seems to be an awful lot of OP_POP calls that maybe could be optimized away to avoid the cost of a cycle each.

**Comment by michaelmalonenz** [comment]
The OP_POP instruction means a full cycle of the interpret loop, which includes the switch statement (including all prior comparisons), the loop jumps as well as the mentioned arithmetic statements. There would be significant savings in work done.

**Comment by pollen5** [comment]
@cseidman wouldn't eliminating the decrement operation used for popping speed up stuff? Even if little a programming language needs to squeeze out as much as possible. Also reducing pop instructions is already a challenge.

**Comment by munificent** [comment]
I didn't feel like mucking with the code in the book, so I went ahead and added this as a challenge.
