### ISSUE TITLE
Ch 5 sidenote redundant wording

### ISSUE THREAD

**Issue by pqnelson** [munificent/craftinginterpreters#215]
> ML, short for “metalanguage” was created by Robin Milner and friends and forms one of the main branches in the great programming language family. Its children include SML, Caml, OCaml, Haskell, and **F#**. Even Scala, **F#**, Rust, and Swift bear a strong resemblance.

(Emphasis added)

F# is mentioned twice here. For the record, F# claims to be inspired by OCaml (well, the claim is of varying strength from "inspired by OCaml" to "implements OCaml on the .NET platform"), so I would consider it a grandchild of ML.

Plus, fun fact, ML was invented to facilitate writing the LCF theorem prover, which is why ML derives its name from "metalanguage" (it was the metalanguage which implemented the LCF prover). For more on this, see the [history of LCF/HOL](https://www.cl.cam.ac.uk/archive/mjcg/papers/HolHistory.pdf) (it later evolved into the HOL family of theorem provers).

**Comment by munificent** [comment]
> F# is mentioned twice here. 

Nice catch, thanks!

> so I would consider it a grandchild of ML.

Yeah, maybe I should have said "offspring" instead of "children". :) It would be a great-grandchild if you include Caml in that lineage too.
