### ISSUE TITLE
Chapter05 representing - Challenges - 1

### ISSUE THREAD

**Issue by dud3** [munificent/craftinginterpreters#217]
```
expr → expr calls
expr → IDENTIFIER
expr → NUMBER

calls → calls call
calls → call

call → "(" ")"
call → "(" arguments ")"
call → "." IDENTIFIER

arguments → expr
arguments → arguments "," expr
```

If I'm not mistaking, according to this grammar we can generate the following:
`NUMBER.IDENTIFIER` or `NUMBER()`, which would allow calls like `10.abc` or `10()`?

I guess I'm just missing a point.

## References
https://github.com/munificent/craftinginterpreters/blob/master/note/answers/chapter05_representing.md

**Comment by munificent** [comment]
> If I'm not mistaking, according to this grammar we can generate the following:
> NUMBER.IDENTIFIER or NUMBER(), which would allow calls like 10.abc or 10()?

Yes, those are allowed syntactically. The former is useful in some object-oriented languages where numbers have methods. The latter isn't very useful, but many grammars allow it syntactically and catch the error later.
