### ISSUE TITLE
Semicolon finishing the "if" rule can be confusing.

### ISSUE THREAD

**Issue by brandizzi** [munificent/craftinginterpreters#220]
The [note about the semicolon in the `while` rule](http://craftinginterpreters.com/control-flow.html#while-loops) is very useful, but it took me some time to figure it out earlier, in the `if` rule. Maybe the note could be moved to the `if` section? This way, not only the reader get a clarification for the `if` rule, she will be alerted to the next instance of it in the loop rule.

**Comment by munificent** [comment]
Good point, thanks!
