### ISSUE TITLE
Slightly confusing sentence in 14.1.1

### ISSUE THREAD

**Issue by yjerem** [munificent/craftinginterpreters#222]
Hi, thanks for doing an amazing job writing the book that I've always wanted to read! 😄 

This seems really minor now, but I know the first time I read it I got a little confused:

> Our existing interpreter has a couple of things going for it:
>
> * Well, first, we already wrote it. *[...]*
>
> * It’s **portable.** Our current interpreter is written in Java and runs on any platform Java supports. If we re-wrote in C, we could compile and run it on basically every platform under the sun.
>
> Those are real advantages. But, on the other hand, **it’s not memory-efficient.**

I think the part about how rewriting in C would make it even *more* portable kind of contradicts the main point, which is that portability is one of the things `jlox` has going for it. Just something that stuck out at me and could maybe use some clearing up.

**Comment by klintmane** [comment]
@yjerem a C implementation being more portable than one in Java does not change the portability fact.

**Comment by munificent** [comment]
Yeah, I agree this was confusing. It sounded like a contrasting point when the intent was to support the original remark. Reworded it. Thanks!
