### ISSUE TITLE
unclear sidenote at scanning.html#reserved-words-and-identifiers

### ISSUE THREAD

**Issue by sschellhoff** [munificent/craftinginterpreters#224]
At the scanning chapter of the first interpreter, at the end of "reserved-words-and-identifiers" you have the side-comment: 

> lox/Scanner.java
> in identifier()
> replace 1 line

which sound like you should replace the first line. Maybe change it to "replace last line" to make that more clear.

**Comment by munificent** [comment]
The location information is generated by a script, so it's kind of hard to tweak for special cases like this. The snippet does show the surrounding code, so hopefully it's fairly clear where the replaced lines go.
