### ISSUE TITLE
visitReturnStmt is new in text, even if you say it isn't

### ISSUE THREAD

**Issue by sschellhoff** [munificent/craftinginterpreters#227]
Hey,
a very small thing, but you say that:

> The new visit method looks like this:

even if the method wasn't declared before. It is no big deal but you should fix this and discard the word "new". Don't get me wrong, i don't want do be niggling. I just want to help :) Your content is really great. Especially because you write about things most books neglect.

**Comment by munificent** [comment]
I meant "new" in the sense of "not present before" not in the sense of "replacing existing thing". :)

But the sentence was a little unclear. Reworded. Thanks!
