### ISSUE TITLE
question: is there an easy way to get a 'clean' version of the source?

### ISSUE THREAD

**Issue by lwhite1** [munificent/craftinginterpreters#229]
Thank you, first of all, for this wonderful book. 

I've made a mistake in my interpreter code and my field setters are not working correctly. I've tried to compare my source with the source here, but the markup for constructing the book makes it difficult. Is there either a version that doesn't include the markup or a way to easily remove it?
Thanks again.

**Comment by lwhite1** [comment]
That's exactly the code I am referring to. It looks like this:


```
/* Evaluating Expressions interpreter-class < Statements and State interpreter
class Interpreter implements Expr.Visitor<Object> {
*/
//> Statements and State interpreter
class Interpreter implements Expr.Visitor<Object>, Stmt.Visitor<Void> {
//< Statements and State interpreter
/* Statements and State environment-field < Functions global-environment
  private Environment environment = new Environment();
*/
//> Functions global-environment
  final Environment globals = new Environment();
  private Environment environment = globals;
//< Functions global-environment

```
etc.

The inclusion of the markup (which seems to include all the code from early chapters that later gets deleted and/or replaced makes it much harder to read than standard java.

**Comment by jlogsdon** [comment]
If you run [`make split_chapters`](https://github.com/munificent/craftinginterpreters/blob/e780086563816c63914301fc7c13e1840e2d8ead/Makefile#L156-L157) it will make a folder for each chapter with cleaned up code. I believe everything ends up in a new `gen/` folder at the root of the repo.

**Comment by lwhite1** [comment]
Thanks

**Comment by munificent** [comment]
@jlogsdon is exactly right. :)
