### ISSUE TITLE
Overzealous em dash-ing

### ISSUE THREAD

**Issue by ozan** [munificent/craftinginterpreters#231]
Thanks for the book!

I noticed that a `--` within a code snippet is being incorrectly replaced with an HTML representation of an em dash:

<img width="339" alt="screenshot 2018-05-20 08 18 24" src="https://user-images.githubusercontent.com/113359/40280591-bf0f168e-5c0a-11e8-9751-5d924ada6f0e.png">

Ack'ing through the book source, this appears to be the only case, but mostly by luck 😀There are a few other `--` patterns within source code, but no others which match [`EM_DASH_PATTERN`](https://github.com/munificent/craftinginterpreters/blob/e780086563816c63914301fc7c13e1840e2d8ead/util/build.py#L34) after other processing steps have been performed.

I was hoping to fix this for you by not performing the substitution within markdown code fences, but ironically given the topic of the book I couldn't immediately see a non-hacky way to do so 😀

If this were my own project, rather than typing '--' in markdown files I'd use shift+option+minus on my mac to insert the Unicode EM DASH code point (U+2014, '—') directly as UTF-8 myself, and avoid the string substitution entirely in the build process. I was going to offer this as a PR—and am happy to still do so—but you'd of course need to update your muscle memory to insert '—' instead of '--' in the future. Personally—as you might notice—I find this quiet straightforward—and honestly rather satisfying 😜

**Comment by munificent** [comment]
Oh, nice catch. Yeah, that's totally broken.

Changing my muscle memory and using the real character is probably the smart solution. After all, I do use the real characters for accented characters. But I find em dash characters pretty hard to read in a monospace font, and I'll also >220k words into muscle memory at this point (including my previous book), so I'll probably just stick with it.

Came up with a super hacky tweak to the regex instead. One of the perks of hand-rolling my own build script. :)
