### ISSUE TITLE
Still able to return nil from init

### ISSUE THREAD

**Issue by mattwildig** [munificent/craftinginterpreters#234]
At the end of Chapter 12 dealing with classes in jlox we make the `init` method always return `this`, and then in the next section we prevent the use of returning any other value from `init`. However the check preventing `return` statements only applies to statements with a value, and doesn’t prevent “plain” `return` statements.

This means it is possible to return `nil` from `init`, which I don”t think is the intention.

```
class Foo {
    init() {
        return;
    }
}

var f = Foo();
print f.init();  // -> nil
```

Removing the `return`, the above code prints `Foo instance`.

One fix is to add a check when catching the return value in `LoxFunction#call`, only returning the value if the function isn’t an initializer and letting it fall through if it is:

```java
try {
    interpreter.executeBlock(declaration.body, environment);
} catch (Return returnValue) {
    if (!isInitializer) {    // <- add this check here
        return returnValue.value;
    }
}
if (isInitializer) {
    return closure.getAt(0, "this");
}
```

Another possibility could be to prevent _all_ `return` statements in initializers, but I don’t think that’s the right choice.

**Comment by munificent** [comment]
Great catch!
