### ISSUE TITLE
Minor typos in 15.1

### ISSUE THREAD

**Issue by Sidewinder1138** [munificent/craftinginterpreters#235]
In a side-note in section 15.1 it reads:

> If you’re building a VM that’s designed to be embedded in other host applications, **it’s** gives the host more flexibility if you do explicitly take a VM pointer and pass it around.

I think you meant "it" instead of "it's".

In 15.1.1 there is:

> The **VMs** runs the chunk and then responds with a value from this enum:

I think that "VMs" should be just "VM".

**Comment by munificent** [comment]
Awesome, thank you!
