### ISSUE TITLE
Minor typo in Ch16

### ISSUE THREAD

**Issue by Sidewinder1138** [munificent/craftinginterpreters#236]
In the first paragraph:

> We **begun** our implementation near the end with chunks and the VM.

Shouldn't that be 'began'? I'm now questioning my understanding of English... haha

**Comment by munificent** [comment]
Haha, someone else pointed that out and I spent like ten minutes trying to think about what the rule between "begun" and "began" is. I had it wrong, but it's fixed now. :)
