### ISSUE TITLE
Scanning on Demand - Compilation Errors in code samples

### ISSUE THREAD

**Issue by christilden** [munificent/craftinginterpreters#237]
I am very excited to get the next chapter and work on it.  I noticed a couple compilation errors.  Unfortunately I don't know how to fix them in order to submit a Pull request (I tried editing the code annotations), but here they are:

scanning-on-demand.md:
-- Line 32: --
^code args (2 before, 2 after)

The next line ("freeChunk(&chunk);") needs to get removed for the code to compile.

-- Line 156: --
^code vm-interpret-c (1 after)

The new interpret(const char* source) function needs the following to compile:
    // Hack to avoid unused error.
    if (false) run();

**Comment by munificent** [comment]
Ah, that first one is a good catch. That was a mistake. I left off the snippet that deletes that line. It's fixed now.

The second one is a little trickier. Basically, you have a function that is defined in the previous chapter, unused temporarily in this one, and then reintroduced in the next chapter. So you'll temporarily get an unused function compile error (if you have that error turned on).

But I don't think it's worth showing people how to hack around that in the book. They can probably just comment out the function locally if they need to.

Thanks for bringing this up!
