### ISSUE TITLE
It is possible to undefine a class

### ISSUE THREAD

**Issue by kelvinyangis** [munificent/craftinginterpreters#238]
```
> class Bagel { init() { print "creating"; } }
> class Bagel < Bagel {}
Superclass must be a class.
[line 1]
> var b = Bagel();
Can only call functions and classes.
> print Bagel;
nil
```

I'm guessing that `environment.define(stmt.name.lexeme, null);` *cannot* be the very first thing we do when visiting a `Stmt.Class`. Perhaps we can save the existing value in the environment, and restore it if the class definition results in a runtime error.

**Comment by munificent** [comment]
Ah, that's an interesting edge case. I think you're right in that we probably don't want the class's name in scope while evaluating its superclass clause. (We do want in scope in the class body, of course.)

I'll take a look and fix this when I get a chance. Thanks!

**Comment by munificent** [comment]
OK, I think I have it doing the right thing now. Thanks for the bug!
