### ISSUE TITLE
rename Statements and Expressions section

### ISSUE THREAD

**Issue by jvasileff** [munificent/craftinginterpreters#24]
Especially given the use of the word "latter" in http://www.craftinginterpreters.com/the-lox-language.html#design-note, it seems the title should list Expressions & Statements in the same order as the text.

> DESIGN NOTE: STATEMENTS AND EXPRESSIONS
Lox has both expressions and statements. Some languages omit the **latter**. Instead, they treat declarations and control flow constructs as expressions too.

**Comment by munificent** [comment]
Great point, done!
