### ISSUE TITLE
toString() not implemented for native clock function in jlox

### ISSUE THREAD

**Issue by silmeth** [munificent/craftinginterpreters#240]
Typically `lox` implements a way to print values, including functions, so that if you do:

```lox
fun foo() { }

print foo;
```

you’ll get `<fn foo>` as the output.

But for the `jlox` implementation, the native `clock` function does not override `toString()` and thus printing it leaks implementation detail, showing it’s a plain Java object of an anonymous class – executing `print clock;` in `jlox` prints something like
```
com.craftinginterpreters.lox.Interpreter$1@71bc1ae4
```
while in `clox` it prints something along the lines of `<native 0x561513e4db90>`.

Perhaps it’d be less surprising if the `clock` function also implemented `toString()` when defined:

```java
new LoxCallable() {
  @Override
  public int arity() {
    return 0;
  }

  @Override
  public Object call(Interpreter interpreter,
                     List<Object> arguments) {
    return (double)System.currentTimeMillis() / 1000.0;
  }

  @Override
  public String toString() {
    return "<native 0x" + Integer.toHexString(hashCode()) + ">";
  }
}
```

**Comment by munificent** [comment]
Ah, good point. Thanks!
