### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by rkirsling** [munificent/craftinginterpreters#241]
In Chapter 16, clox is making use of two new exit codes, 64 and 74, in cases where jlox simply returns 0.

I remember googling for 65 and 70 a year ago to no avail—it wasn't until grepping Wren just now and finding [this comment](https://github.com/munificent/wren/blob/master/test/api/main.c#L114) that I realized these magic numbers are mimicking Unix header `sysexits.h`.

I assume we want jlox to align with clox on this behavior, but if so, the reader is definitely owed at least a sidenote about where these codes are coming from—otherwise the clause "we’re scrupulous tool builders and care about little details" rings quite dubiously. :smile:

**Comment by munificent** [comment]
Haha, fair point! I'll try to clarify these. :)

**Comment by Sidewinder1138** [comment]
Ah ok, I read https://github.com/munificent/craftinginterpreters/commit/1897fb026f63b7d7c8dc4592cfebd4070d3c2d34 and it makes sense now. Sorry for the dupe.

It looks like this aside only resides on the JLox side of things, I wonder if referencing it once more in CLox side would be helpful?
