### ISSUE TITLE
3.3 Data Types Typo

### ISSUE THREAD

**Issue by manojdev** [munificent/craftinginterpreters#243]
Booleans – You can’t code without logic and you can’t logic without Boolean values. **“True” and “false”**, the yin and yang of software.

"T" in True is in caps and "f" in false is in small case.

**Comment by silmeth** [comment]
It’s a sentence beginning with “true”. The first word of a sentence in English begins with a capital letter. Everything looks OK to me here.

**Comment by munificent** [comment]
Yeah, @silmeth is correct. :) Because I'm using these words in their normal sense and not as keywords where case is sensitive, they are capitalized as you would normal words in a sentence. I appreciate your attention to detail!
