### ISSUE TITLE
Code insertion notes lacking in Chapter 16

### ISSUE THREAD

**Issue by Sidewinder1138** [munificent/craftinginterpreters#244]
In 16.1: The three blocks of code where you are inserting error handling into the "readFile" function (following the text that goes "Fortunately, we don’t need to do anything particulary clever if a failure occurs" etc), seem to not have the usually very helpful "insertion" notes. The first one says "add after repl()" and the other two just mention main.c, but it seems to me all should mention inserting code into readFile()?

In 16.2: I noticed the first code block in 16.2 has a note that says "add after compile()" which is a bit confusing, since we are inserting code into compile(), not after.

Sorry if I haven't explained this well.

**Comment by munificent** [comment]
You explained it great. There was indeed a bug in the code that detects the code locations. It wasn't picking up functions whose return type was a pointer. Should be fixed now.
