### ISSUE TITLE
exit() codes in Chapter 16

### ISSUE THREAD

**Issue by Sidewinder1138** [munificent/craftinginterpreters#245]
I was wondering, do the exit codes you are using in Ch16 (64, 65, 70, 74) have some kind of meaning? Or are they just "arbitrary" values you picked for Lox? Wasn't sure if I'm missing some arcane posix knowledge or something haha. Thx!

**Comment by jube** [comment]
See #241 ;)

**Comment by Sidewinder1138** [comment]
Ah ok, I read 1897fb0 and it makes sense now. Sorry for the dupe.

It looks like this aside only resides on the JLox side of things, I wonder if referencing it once more in CLox side would be helpful?

**Comment by munificent** [comment]
...maybe, but I generally worry about having too much repetition between the parts as it is. The book is on track to be quite long. This is probably minor enough that it's not worth explaining twice.
