### ISSUE TITLE
for (;;) vs while (in Ch15/16)

### ISSUE THREAD

**Issue by Sidewinder1138** [munificent/craftinginterpreters#246]
I was wondering, why do you use the **for (;;)** infinite loop idiom rather than **while(1)** or **while(true)**? I don't mind either way, but was just curious what your rationale was behind it...

I've been playing with Go lately, so it's starting to seem seem more "correct" to me to only ever use the 'for' looping construct, but that's just me...

**Comment by munificent** [comment]
I don't have a strong preference either way. My personal habit is towards `while (true)`. But that feels weird to me in C where `true` isn't a real reserved word. So I felt `for (;;)` made more sense since it doesn't introduce any arbitrary faux Boolean values. Also, it's a little shorter. :)
