### ISSUE TITLE
8.3 visitVariableExpr not implemented in AstPrinter 

### ISSUE THREAD

**Issue by dpreston** [munificent/craftinginterpreters#247]
I received this error when compiling to test at the end of 8.3

> The type com.craftinginterpreters.lox.AstPrinter must implement the inherited abstract method com.craftinginterpreters.lox.Expr.Visitor<java.lang.String>.visitVariableExpr(com.craftinginterpreters.lox.Expr.Variable)

I copied the visitVariableExpr implementation from the repo and compilation was successful.

**Comment by Sidewinder1138** [comment]
At the very end of Chapter 5, Bob says:

> Also, as we add new syntax tree types, I won’t bother showing the necessary visit methods for them in AstPrinter. If you want to (and you want the Java compiler to not yell at you), go ahead and add them yourself. It will come in handy in the next chapter when we start parsing Lox code into syntax trees.

It's possible you missed this, or just forgot (I definitely forgot haha). 

Maybe it would be helpful to have one more reminder later in the book that, yeah, it's an exercise to the reader to keep AstPrinter working. You can also of course just kill it if you don't want to maintain it, however it's extremely handy for debugging in my experience.

**Comment by munificent** [comment]
I thought about mentioning it as needed, but it would be in basically every chapter, and that felt like overkill to me. <shrug>
