### ISSUE TITLE
Clarification for Chapter 16, Challenge 2

### ISSUE THREAD

**Issue by dasdware** [munificent/craftinginterpreters#248]
What strikes me a bit odd in that challenge is how you mix C++'s templates with the generics of other languages. They are much more powerful and - in a sense - their own turing-complete programming language. 

So the following is perfectly possible in C++:

```c++
#include <iostream>

template <int N> struct Log2 {
	static const int value = Log2<(N>>1)>::value + 1;
};
template <> struct Log2<0> {
    static const int value = -1;
};

int main() {
  std::cout << "log2 of 0: " << Log2<0>::value << std::endl;
  std::cout << "log2 of 1: " << Log2<1>::value << std::endl;
  std::cout << "log2 of 1024: " << Log2<1024>::value << std::endl;
}
```

I know, the edge case of defining `log2` of `0` as `-1` is mathematically wrong, but it plays nice with the recursion. As you can see, the right-shift operator `>>` is valid in the context of a template instantiation. Therefore, the lexer cannot determine on itself whether you meant that operator or if you wanted to close the arguments of nested tampletes.

Generics do not have that problem, since they can have only much more restricted type arguments.

Or did you leave that bit out for simplicity?

**Comment by munificent** [comment]
That's an interesting point! I forgot that C++ templates can have full expressions inside the template argument list.

I don't think that changes the overall point, though. Even in simpler languages like Java, you can still run into situations where it's ambiguous as to whether or not a `>>` is a shift or two `>` tokens without having context.

Consider this weird animal:

    A(B<C,D<E>>(F))

That `>>` could conceivably be a right shift if you treat the previous `<` as both being less-thans:

    A(B < C, D < E >> (F) )

Or it could be closing two generic argument lists if you treat `B` as a generic method that takes two type arguments:

    A( B<C, D<E>>( F ) )

So I think in either language, you need roughly the same amount of context. And, of course, needing *any* context kicks you out of the much simpler restrictions of a regular language and into the realm of context-free.

**Comment by dasdware** [comment]
And I think, that is the problem I have with that challenge. It suggests, that your classic C++ problem is a scanner one, while it really is a parser problem. In omitting the possibility of general expressions as template arguments, I find the challenge description quite misleading.

I hope, that does not sound too harsh. I really love your book, but after having worked with C++ for several years, that text just feels a bit wrong to me.

**Comment by munificent** [comment]
> It suggests, that your classic C++ problem is a scanner one, while it really is a parser problem.

I think we're talking past each other. :)

The only reason it "really is a parser problem" is precisely because you need too much context to resolve `>>` in the scanner. In other words, the fact that it's a parser problem *is* the problem. You would ideally like to tokenize `>>` in the scanner, but you can't. That's the problem.

This is equally true in C++, C#, Java, etc.
