### ISSUE TITLE
Comment about changed line in code excerpt

### ISSUE THREAD

**Issue by owenjonesuk** [munificent/craftinginterpreters#249]
In 8.2 you have the follwing comment after a code excerpt:

"Also, we need a comma after the Unary line, which is why that one is changed too."

I was surprised you didn't have the equivalent line

"Also, we need a comma after the Print line, which is why that one is changed too."

after the code excerpt just above. Or perhaps one comment about both.

Of course this is pure nitpickery, but you seem like the kind of perfectionist who'd like to know :). Thanks so much for the book.

**Comment by munificent** [comment]
You are right. I am *exactly* that kind of perfectionist. Done: 1d1174f2f05590109c594b65309818e5cf53cdf1

:)
