### ISSUE TITLE
Small inconsistency

### ISSUE THREAD

**Issue by owenjonesuk** [munificent/craftinginterpreters#251]
You took my last nitpick well, so here's another one. I noticed a small inconsistency. In Section 8.3 (and possibly later, but I haven't noticed it earlier), when you give chunks of code to add to a file that already exists, it sometimes isn't explicitly specified where to put them. For example, you don't say whether to put `Object get(Token name)` before or after ` void define(String name, Object value)`. Previously you have stated this, e.g. in section 4.1 you said of `private static void runFile(String path)`: "add after main()".

Obviously this doesn't really matter, it's just slightly inconsistent, and I thought I'd mention it. Again, I'm really enjoying the book, thanks for writing it and putting it online for free.

**Comment by munificent** [comment]
Yes, this is helpful! The build script tries to automatically figure out the context for snippets. Sometimes it isn't very clear and I need to remember to be explicit. This was one of those places.
