### ISSUE TITLE
[css] Border Problem on Small Screens (e.g., cell phones)

### ISSUE THREAD

**Issue by pqnelson** [munificent/craftinginterpreters#252]
So I ran into an interesting problem last night reading on my cell phone, some of the code snippets have borders (namely the `pre.insert` elements)...which don't mesh well with overflow-x. Observe in the screenshot below, the right border seems to be fixed, as opposed to "outside" the scroll widget.

You can reproduce this problem by making your browser ridiculously narrow. (I have done it in both Chrome and Firefox.)

You probably have better things to worry about than pathological CSS bugs, but I thought I should alert you to this...

![border-problem](https://user-images.githubusercontent.com/1752731/42459688-0dc155c2-8351-11e8-9f02-079976579b25.png)

**Comment by munificent** [comment]
Well, I do spend a lot of time on pathological CSS bugs, but this one is particularly nasty. I don't have a solution yet, but I'll keep beating on it. :-/

**Comment by munificent** [comment]
Well, that took some doing!
