### ISSUE TITLE
suggestion: add demo console output in each chapter

### ISSUE THREAD

**Issue by haolloyin** [munificent/craftinginterpreters#253]
Hi Bob, thanks for your wonderful interpreter tutorial. It really helps me a lot. Thanks again! :)

I am recently reimplementing clox in other programming language.
But after I done my work, I am not sure whether my implemention is right.

Especially in Chapter 17 [Compiling Expressions](http://www.craftinginterpreters.com/compiling-expressions.html), it seems you didn't say what is the **INPUT** and **OUTPUT** is.

Would you please add one demo INPUT & OUTPUT in order to check whether our implemention is right?
Thank you very much!

And here is my **INPUT** & **OUTPUT** in bytecode and scan chapters. :)
https://github.com/haolloyin/rsLox

**Comment by beoboo** [comment]
A nice solution could be using https://www.codiva.io/ or a similar tool.

**Comment by munificent** [comment]
This is a good idea, but I've just got to get this book done, and I don't see myself making this happen, so I'm going to close the issue. I do try to have a couple of examples here and there in the chapters, but I don't plan to do anything more thorough than that.
