### ISSUE TITLE
Don't credit Chomsky with the Chomsky hierarchy

### ISSUE THREAD

**Issue by dlukes** [munificent/craftinginterpreters#255]
I know the issue title sounds flippant, but please bear with me :) In Chapter 5, you say:

> Ever since John Backus snuck into Noam Chomsky’s linguistics class and stole some theory to use for specifying ALGOL 58

The wording is playfully vivid (which is one of the things I happen to love about your prose), but it gives Chomsky much more credit than is his due. In all likelihood, it was actually the other way round: Chomsky borrowed the concept from his friends / colleagues working on programming languages and (mis)applied it to natural language. If you're interested in historical details, please refer to sections 3 and 4 of [this paper](https://www.grsampson.net/ARsy.pdf) (the parts labeled with A).

I know it sounds like a trifle, but Chomsky hype led linguistics (my own field) down a rabbit hole for two or three decades, in great part on the strength of such a heroically overinflated mythology of his intellectual achievements. Perpetuating that mythology gives the Chomskyan tradition an aura of authority that it doesn't deserve.

To be clear, I'm not suggesting changing the term "Chomsky hierarchy" to something else -- that ship has sailed a long time ago. I just wouldn't explicitly credit Chomsky with it, not even in tongue-in-cheek made-up anecdotes like the one above. It's unfortunate enough people will implicitly assume he invented it anyway.

On a more pleasant note: thank you so much for the book, it's awesome!

**Comment by munificent** [comment]
Yeah, I agree Chomsky's useful contributions to linguistics turned out to be less than he and others would have you believe. :)
