### ISSUE TITLE
Multiline expressions and line numbering

### ISSUE THREAD

**Issue by mariosangiorgio** [munificent/craftinginterpreters#256]
While I was going throught the code presented in the [Compiling Expressions](http://www.craftinginterpreters.com/compiling-expressions.html) chapter I felt that the approach of using the line of the previous token was much simpler than what I was trying to implement.
https://github.com/munificent/craftinginterpreters/blob/4b49e641b24ce7aa6138dec687e10f5a98febdf8/c/compiler.c#L235

It seems that this approach assumes expressions to be on a single line. If that doesn't happen the bytecode might get the wrong line assigned.

For instance,
```
var a = -(1 +
          2);
```
gets compiled to
```
== <top> ==
0000    1 OP_CONSTANT         1 '1'
0002    2 OP_CONSTANT         2 '2'
0004    | OP_ADD
0005    | OP_NEGATE
0006    | OP_DEFINE_GLOBAL    0 'a'
0008    | OP_NIL
0009    | OP_RETURN
```
and some instructions labelled with line 2 while they're actually on the first line.

This happens because line numbers are printed looking only at the last token we've seen but in some cases (e.g. with unary negation) we need to first fully parse the sub-expression and then emit the bytecode, which is done relying on the call-stack keeping track of what's left to emit.

This is of course a very minor issue but maybe it's worth mentioning it, even if only as a challenge for the reader.

**Comment by munificent** [comment]
Ah, yes. Good observation!
