### ISSUE TITLE
Compilation to binary

### ISSUE THREAD

**Issue by egordorichev** [munificent/craftinginterpreters#26]
Hello! 

I'm very excited about your book. Can you also write a small extension for exporting interpreted code to binary? 

Thanks!

**Comment by munificent** [comment]
Can you give me some more details about what you mean by "exporting" and "binary"?

**Comment by egordorichev** [comment]
I mean convert bytecode to executable (elf on Linux, exe on Windows and so on).

**Comment by aggsol** [comment]
IMO that would exceed the scope of the book wildly and would also render the title Crafting **Interpreters** misleading. Even so ARM64 Elf would be fun though.... ;-P

**Comment by egordorichev** [comment]
But this could be an extension. If you can give me some algorithms and docs, i could try write one...

**Comment by munificent** [comment]
Yes, sorry. That extension would be about as large as the entire book. Compilation to native code is complex. It's a little out of scope here.

> If you can give me some algorithms and docs, i could try write one...

I'd start with the [Dragon Book](https://www.amazon.com/Compilers-Principles-Techniques-Tools-2nd/dp/0321486811).

**Comment by GraydenH** [comment]
Could there maybe be a bit about how to model the vm components (such as the gc) as instead a runtime to package with the program?

I am having a hard time thinking in my head how that would work. It's totally reasonable that native compilation is well outside the scope of the book, but I feel giving directions on this would be a good middle ground. Unless there is some good material on this?

**Comment by munificent** [comment]
Yes, that would definitely be interesting too, but it would be hard to fit that into this book. You'd really need to explain it in the context of the rest of the native code you are compiling and linking it with, and this book doesn't go into that at all.

Maybe if I ever write another book on native compilers. :)
