### ISSUE TITLE
AST generator for void returns.

### ISSUE THREAD

**Issue by beoboo** [munificent/craftinginterpreters#260]
In §8.1.3 you say that:

_Java requires that to satisfy the special capitalized Void return type. Weird, but what can you do?_

Can the AST generator be modified in order to produce a "non-returning" Visitor to handle the Void case? I think it will polish a lot the code, avoid all those nasty `return null`.

**Comment by munificent** [comment]
> Can the AST generator be modified in order to produce a "non-returning" Visitor to handle the Void case?

We would have to have two separate Visitor interfaces, a void one and a non-void one since we need the latter for Interpreter. Using `Void` seemed simpler to me than that.
