### ISSUE TITLE
"binary arithmetic"

### ISSUE THREAD

**Issue by rkirsling** [munificent/craftinginterpreters#261]
In 17.4, you have the amusing phrase:
> The Four Horsemen of binary arithmetic: `+`, `-`, `*`, `/`.

Unfortunately, these are [binary [arithmetic operators]] and not [[binary arithmetic] operators]. :sweat_smile:

You could correct it to "The Four Binary Horsemen of arithmetic", but I'm not sure it has the same ring to it—on the other hand, since it's a playful expression to begin with, I'll note that "the Arithmetic" has the same meter as "the Apocalypse", so you could potentially go with that and drop "binary" altogether. 😛

**Comment by munificent** [comment]
Done, I love it. 😄
