### ISSUE TITLE
Chapter "Functions"- 10.5.1 - Missing statement in while loop

### ISSUE THREAD

**Issue by geertguldentops** [munificent/craftinginterpreters#264]
Hi @munificent, let me first thank you for a wonderful book! It has been an amazing journey, I have read quite a lot of software books but I have not had this much fun and learning since SICP!

I noticed a small error in the Chapter "Functions", sub section 10.5.1 to be precise. This while loop:

<pre>
fun count(n) {
  while (n < 100) {
    if (n == 3) return n; // <--
    print n;
  }
}

count(1);
</pre>

In its current form is an infinite loop since n is not updated anywhere ;), I suspect you meant to write something like this:

<pre>
fun count(n) {
  while (n < 100) {
    if (n == 3) return n; // <--
    print n;
  }
 n = n + 1;
}

count(1);
</pre>

**Comment by munificent** [comment]
Nice catch, thanks!
