### ISSUE TITLE
compiling jlox

### ISSUE THREAD

**Issue by arrmixer** [munificent/craftinginterpreters#266]
I'm sorry for even asking this question. I was able to compile the clox without a problem once I added gcc to my classpath but was wondering why jlox was not compiling successfully. 
I get this printout every time I either type make or make jlox:

make[1]: Nothing to be done for `default'.
   javac java/com/craftinginterpreters/lox/Expr.java                  -Werror
   javac java/com/craftinginterpreters/lox/Stmt.java                  -Werror 

I believe I have javac in my path since I can call javac from the terminal.
I put this in my .bash_profile, export JAVA_HOME=$(/usr/libexec/java_home) to place javac within my class path. 
 I'm using a mac machine. I using Java 8. 

If someone can help me know why those two classes are throwing -Werror I would greatly appreciate it. 

Thank you!

**Comment by munificent** [comment]
They aren't failing with `-Werror`. That's just a flag being passed to `javac` to make all warnings errors.

The output isn't clear, but you have actually built jlox successfully. What's going on is this:

1. The Expr.java and Stmt.java files are generated automatically by running the AST generator I talk about [in the book](http://www.craftinginterpreters.com/representing-code.html#implementing-syntax-trees).

2. Then we compile all of the .java files to .class files.

Step 1 is run unconditionally and ends up producing identical files but with newer modification dates. Make things the files have changed, so it recompiles them, which is where the two `javac` lines of output are coming from.

At some point, I should tweak the Makefile to only recompile those if they've actually changed, but it's not a high priority.

**Comment by arrmixer** [comment]
Ah okay thank you for response. I’m on chapter 4 at the moment. Great book!! 
So how do I run/use the completed version of jlox?  I tried some of the jlox commands from the terminal but they were not recognized. 
I thought it didn’t compile which is why I asked the question. Obviously I’m missing something. 😞
Thank you. 🙂

**Comment by rkirsling** [comment]
@arrmixer After `make` finishes, you should only need to run `./jlox`. Unlike what's written [here](https://github.com/munificent/craftinginterpreters#building) though, the `./` is not optional, so perhaps that could be a helpful clarification to add to the README.

**Comment by munificent** [comment]
@rkirsling is right.

> Unlike what's written here though, the `./` is not optional

Oops! Fixed: https://github.com/munificent/craftinginterpreters/commit/28ed2a98d784e00979d3f40c5ba957b308b428a1

**Comment by arrmixer** [comment]
Thank you gentlemen! 👍 :)
