### ISSUE TITLE
Aside overlap on 11.4

### ISSUE THREAD

**Issue by munificent** [munificent/craftinginterpreters#267]
The "side table" aside overlaps the code location blurb.

**Comment by DanTup** [comment]
I just noticed that the text in the sidebar is also duplicated in the code on the left:

<img width="850" alt="screen shot 2018-08-13 at 22 37 44" src="https://user-images.githubusercontent.com/1078012/44059524-96aa8232-9f49-11e8-94d3-70b1b344e35c.png">

The text "lox/Interpreter.java add after visitVariableExpr()" appears both in the sidebar and in the main content (I don't think it's intended to be in the main content). Maybe should be its own issue, but it's possible it's related to this one.

**Comment by DanTup** [comment]
Oh, a force-refresh fixed that last one, so maybe was a CSS change and the CSS/HTML weren't in-sync.

**Comment by munificent** [comment]
Thanks, fixed it. The second one was fixed by another change already.
