### ISSUE TITLE
Very minor; typo in code comment

### ISSUE THREAD

**Issue by jtanza** [munificent/craftinginterpreters#27]
*The Scanner Class 4.4*

> `while (!isAtEnd()) {
         // We are the beginning of the next lexeme.`

Source code has correct comment  :) 
https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Scanner.java#L49

**Comment by munificent** [comment]
Oh, looks like I just needed to rebuild and republish it. Should be fixed now. Thanks!
