### ISSUE TITLE
Question: Further reading for answer to question 3 in chapter 15?

### ISSUE THREAD

**Issue by mspraggs** [munificent/craftinginterpreters#275]
In the answer to question 3 in chapter 15 (A Virtual Machine) you refer to the fact that an upper bound on the stack can be computed based on the constraints placed upon generated bytecode. Is there a reference to read more about this, or is it just a case of looking at how constants, variables and other instructions interact to produce a stack of a certain size?

**Comment by munificent** [comment]
> Is there a reference to read more about this

I can't think of a good one off-hand, and I don't recall where I got the technique from. Possibly from reading Lua's source code? If you look for `numSlots` and `maxSlots` [here](https://github.com/munificent/wren/blob/master/src/vm/wren_compiler.c), you can see how I implement it in Wren.

>  is it just a case of looking at how constants, variables and other instructions interact to produce a stack of a certain size?

Yes, that's the basic idea. Each instruction has a "stack effect" that defines how it modifies the height of the stack. As you compile, you keep track of the greatest possible number of stack slots needed across all control flow branches.
