### ISSUE TITLE
Possible inaccuracy re. switch/enum behaviour

### ISSUE THREAD

**Issue by harto** [munificent/craftinginterpreters#280]
Hello! I noticed this passage in http://www.craftinginterpreters.com/representing-code.html#working-with-trees (emphasis mine):

> That’s verbose and slow. Also, the Java compiler won’t tell us when we forget to add support for some new expression class. **With an enum, we get a compile error when a switch is missing a case.**

I didn't find that to be true in the version of `javac` that I used to compile this program:
```java
public class EnumExample {
    enum Enum {
        FOO,
        BAR,
    }

    public static void main(String[] args) {
        Enum e = Enum.BAR;
        switch (e) {
        case FOO:
            //
        }
    }
}
```
Did I misunderstand?

**Comment by munificent** [comment]
You are correct! I think some compilers will warn on this, but the language spec doesn't require it.
