### ISSUE TITLE
Miss typed?

### ISSUE THREAD

**Issue by egordorichev** [munificent/craftinginterpreters#282]
Noticed something while reading the source code of clox:

[table.c:](https://github.com/munificent/craftinginterpreters/blob/master/c/table.c#L23)

```
void freeTable(Table* table) {
  FREE_ARRAY(Value, table->entries, table->capacityMask + 1);
  initTable(table);
}
```

[table.h:](https://github.com/munificent/craftinginterpreters/blob/master/c/table.h#L21)
```
typedef struct {
  int count;
  int capacityMask;
  Entry* entries;
} Table;
```

Shouldn't free array be `FREE_ARRAY(`**Entry**`, table->entries, table->capacityMask + 1);`?

**Comment by munificent** [comment]
Yes, good catch! :)
