### ISSUE TITLE
Typos and questions about Part II.

### ISSUE THREAD

**Issue by beoboo** [munificent/craftinginterpreters#285]
§3.8
> An argument is an actual value you pass to a function when you call it. So a function call has an argument list. Sometimes you hear “actual parameter” used for these.
> A parameter is a variable that holds the value of the argument inside the body of the function. Thus, a function declaration has a parameter list. Others call these “formal parameters” or simply “formals”.

`formal parameters` and `formals` are in bold, while `actual parameter` is not.

§9.4
To be more similar to other expectations, `Expect ')' after condition.` should be `Expect ')' after while condition.`

§10.2.1
Why the clock function toString doesn't return something like "<native fn clock>"? It would be much more in line with the user-function toString name defined below.

Also, wouldn't it be better to use `fun` instead of `fn`?

In `craftinginterpreters/note/answers/chapter06_parsing.md`, there's a `consume(":", ...)` instead of `consume(COLON, ...)`

**Comment by munificent** [comment]
> To be more similar to other expectations, `Expect ')' after condition.`

I think this one's OK as-is.

> Why the clock function toString doesn't return something like ""? 

It's consistent with what clox does for native functions.

I fixed the other stuff you mentioned. Thanks!
