### ISSUE TITLE
Parameter name mismatch in chapter 14

### ISSUE THREAD

**Issue by dasdware** [munificent/craftinginterpreters#286]
In section 14.4 ("Disassembling chunks"), the second parameter to `disassembleInstruction` is called `i` in the header file and `offset` in the implementation C file. IMHO, it should be called `offset` in both places to make its intention clearer to the reader.

Of course, the C compiler does not take into account parameter names, so its not that much of a problem.

Thanks again for your book, I already have the first ideas of how to integrate these principles at my work. :-)

**Comment by munificent** [comment]
Great catch, thanks!
