### ISSUE TITLE
"Segmentation fault" when printing a bound method using clox

### ISSUE THREAD

**Issue by benhoyt** [munificent/craftinginterpreters#288]
I found a bug in `clox` which causes a memory access error /segmentation fault when you try to print a bound method object. To repro, save this to `print_bound_method.lox`:

```
class Foo {
  method() { }
}
var foo = Foo();
print foo.method;
```

And run it:

    $ ./clox print_bound_method.lox 
    Segmentation fault: 11

It's happening because the `case OBJ_BOUND_METHOD:` in `printObject()` falls straight through to the `OBJ_CLOSURE` case, which calls `AS_CLOSURE(value)` on something that's not a closure. To fix, I think you just need to change the case to:

```
    case OBJ_BOUND_METHOD:
      printf("<fn %s>", AS_BOUND_METHOD(value)->method->function->name->chars);
      break;
```

Then we get:

    $ ./clox print_bound_method.lox 
    <fn Foo.method>

**Comment by munificent** [comment]
Excellent catch, thanks.
