### ISSUE TITLE
TypeError: markdown() takes 1 positional arguments but 2 were given

### ISSUE THREAD

**Issue by DrunkOnHotCoco** [munificent/craftinginterpreters#291]
Hi, just want to start off by saying I'm pretty new at this, so I apologize if this is something I'm just supposed to deal with on my own or maybe even submit a pull request for. 

The issue occurs when using `make`.
I think the issue is incompatibility with Markdown 3.0 ([release notes](https://python-markdown.github.io/change_log/release-3.0/))   [Python package](https://github.com/Python-Markdown/markdown). I found out the cause by referencing [this issue](https://github.com/apache/incubator-superset/issues/5958). 

Specifically, positional arguments have been deprecated, which /util/build.py uses twice (shown at the bottom of this post).

>  Positional arguments on the markdown.Markdown() class are deprecated as are all except the text argument on the markdown.markdown() wrapper function. Using positional arguments will raise an error. Only keyword arguments should be used. For example, if your code previously looked like this:
> 
> `html = markdown.markdown(text, [SomeExtension()])`
> Then it is recommended that you change it to read something like this:
> `html = markdown.markdown(text, extensions=[SomeExtension()])`

- Line 125,
OLD:
`html = markdown.markdown(markup, ['extra', 'codehilite'])`
FIX:
`html = markdown.markdown(markup, extensions=['extra', 'codehilite'])`
- Line 384,
OLD:
`body = markdown.markdown(contents, ['extra', 'codehilite', 'smarty'])`
FIX:
`body = markdown.markdown(contents, extensions=['extra', 'codehilite', 'smarty'])`

Thanks for reading, just a small issue that I wanted to point out. Thanks :)

**Comment by munificent** [comment]
OK, this should now work with later versions of Python markdown. However, I think there's a bug in 3.0 and 3.1.0 where it inadvertently escapes `<` in some code blocks. With 2.6.11, it seems to do the right thing.
