### ISSUE TITLE
Sidenote collision in 19.3

### ISSUE THREAD

**Issue by rkirsling** [munificent/craftinginterpreters#296]
In 19.3, there's a long sidenote that runs over a whole codeblock, thus obscuring its source file indicator:

![image](https://user-images.githubusercontent.com/2172590/46913522-650e6200-cf43-11e8-9424-4465c64b34fc.png)

**Comment by munificent** [comment]
Fixed by: d509591f43c37aa53e3a34bf0abff98043262788
