### ISSUE TITLE
Typo: Chapter 7 (Section: Evaluating binary operators 7.2.5 (Side Note))

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#300]
Section: Evaluating binary operators 7.2.5 (Side Note)
Typo: "Strangely enough, NaN is supposed to be not equal itself."
Correction: "Strangely enough, NaN is supposed to be not equal to itself."
Action: Insert "to" between "equal" and "itself"

**Comment by munificent** [comment]
Fixed by https://github.com/munificent/craftinginterpreters/pull/306.
