### ISSUE TITLE
Typo: Chapter 9 (Section: Design Note: Spoonfuls of Syntactic Sugar)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#302]
Section: Design Note: Spoonfuls of Syntactic Sugar 
Error: " Eventually you reach Ruby, C++, Perl, and D, languages who have stuffed so much syntax into their grammar..."
Correction: " Eventually you reach Ruby, C++, Perl, and D, languages which have stuffed so much syntax into their grammar..."
Action: Replace "languages who" by "languages which"

**Comment by munificent** [comment]
Fixed by https://github.com/munificent/craftinginterpreters/pull/306.
