### ISSUE TITLE
Suggestion: Chapter 10 (Section: Function Objects 10.4)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#305]
Section: Function Objects 10.4
Target: "As we saw in the chapter on statements and state..."
Problem: Currently, only the text "the chapter on statements" is hyper-linked to chapter 8.  
Suggestion: The whole text "the chapter on statements and state" should be hyper-linked to chapter 8.

**Comment by munificent** [comment]
😁
