### ISSUE TITLE
Typo: Chapter 17 (Section: Parsers for tokens 17.4.1)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#308]
Section: Parsers for tokens 17.4.1
Typo: "Imagine if every expression in Lox is only a single token."
Correction: "Imagine if every expression in Lox were only a single token."
Action: Replace "is" by "were"

**Comment by munificent** [comment]
I switched the "if" to "that". I think that reads better than trying to shift the entire paragraph to the subjunctive mood. Thanks for bug!
