### ISSUE TITLE
Chapetr 19: Missing introductory quote

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#310]
Chapter 19 does not have the customary introductory quotation that starts each chapter.

For example, Chapter 18 starts with: 

<blockquote>
<p>When you are a Bear of Very Little Brain, and you Think of Things, you find
sometimes that a Thing which seemed very Thingish inside you is quite
different when it gets out into the open and has other people looking at it.</p>
<p><cite>A.A. Milne</cite></p>

**Comment by munificent** [comment]
Fixed in f4053f986620c6660cd07513a4d7f1df78b05857. Thanks for reminding me. :)
