### ISSUE TITLE
Building on Ubuntu 16.04

### ISSUE THREAD

**Issue by spencerhuston** [munificent/craftinginterpreters#313]
Error when running **make** on Ubuntu 16.04 on VirtualBox:
`Traceback (most recent call last):
  File "util/build.py", line 542, in <module>
    format_files(False)
  File "util/build.py", line 492, in format_files
    format_file(file, skip_up_to_date, max(code_mod, templates_mod))
  File "util/build.py", line 384, in format_file
    body = markdown.markdown(contents, ['extra', 'codehilite', 'smarty'])
TypeError: markdown() takes 1 positional argument but 2 were given
Makefile:7: recipe for target 'book' failed
make: *** [book] Error 1`

**Comment by rkirsling** [comment]
There's a fix up at #293. :smile:

**Comment by spencerhuston** [comment]
@rkirsling Thank you!
