### ISSUE TITLE
ParseError handling temporarily removed in Ch 8 s8.1.3

### ISSUE THREAD

**Issue by harto** [munificent/craftinginterpreters#314]
In [Executing Statements](http://www.craftinginterpreters.com/statements-and-state.html#executing-statements), we refactor the jlox interpreter so that `Parser.parse` returns `List<Stmt>` instead of `Expr`. However, we remove the `ParseError` handling, so when we're directed to fire up the REPL and try out some statements, any parse error crashes the interpreter. (It looks like the error handling is reintroduced in the subsequent section.)

E.g. this is what I noticed:
```console
~/src/crafting-interpreters (master *%) › ./jlox
> print 1 + 2
[line 1] Error at end: Expect ';' after value.
Exception in thread "main" lox.Parser$ParseError
	at lox.Parser.error(Parser.java:164)
	at lox.Parser.consume(Parser.java:137)
	at lox.Parser.printStatement(Parser.java:33)
	at lox.Parser.statement(Parser.java:27)
	at lox.Parser.parse(Parser.java:21)
	at lox.Lox.run(Lox.java:49)
	at lox.Lox.runPrompt(Lox.java:40)
	at lox.Lox.main(Lox.java:23)
```

**Comment by munificent** [comment]
Ah, yes, you're right. There's a window of time where there isn't any error handling in place. But that window closes before the end of the chapter. In [8.2.2](http://www.craftinginterpreters.com/statements-and-state.html#parsing-variables), when we switch to parsing declaration, the ParseError handling is re-introduced.

As much as possible, I try to avoid regressing functionality as we build stuff, but there are occasionally chunks of a chapter where some stuff is temporarily broken. I think this one is small enough to not cause too many problems.
