### ISSUE TITLE
Typo: “chrews” -> “chews”

### ISSUE THREAD

**Issue by djjonno** [munificent/craftinginterpreters#319]
In chapter 19 section 5 (19.5)

“When the compiler *chrews* through this, it allocates an ObjString for each...” 

should be 

“When the compiler *chews* through this, it allocates an ObjString for each...”

**Comment by munificent** [comment]
Conveniently enough, I *just* fixed this: d4fb34cc8a319734e0fe6d193da3028705497ec8
