### ISSUE TITLE
Dangling next pointer in vm.objects linked list?

### ISSUE THREAD

**Issue by uohzxela** [munificent/craftinginterpreters#32]
Hey there. I'm a programming language enthusiast and I'm trying to understand how garbage collection works by reading your code. I'm new to C as well. So please excuse me for my ignorance and feel free to close the issue if it's moot.

I'm referring to the collectGarbage() ([line 273](https://github.com/munificent/craftinginterpreters/blob/7134b58ddca7ddb055672c8dabfe2043bd2d5a89/c/memory.c#L273) in memory.c). 

From my understanding, vm.objects is a linked list of objects that are dynamically allocated. In line 273, when you free an object, I assume the next pointer gets freed as well. So when you traverse the linked list again, the objects after the freed object will not be accessed due to the dangling next pointer of the previous object (which is pointing to the freed object).

Since the next pointer of the previous object is not updated to point to the object **after** the freed object, I'm having a hard time understanding how this could work.

As I am new to C, my understanding may not be correct and there may be subtleties that I've missed. Please feel free to correct me otherwise!

**Comment by uohzxela** [comment]
I read through the [comments](http://disq.us/p/j3v92b) of your old blog post on GC and I got it now. There's indeed a subtle usage of pointers that I didn't catch. Anyway, really awesome work with the book and the code.

**Comment by munificent** [comment]
I should leave a comment in there tracking how many readers get tripped up by that exact line. :) Out of all ~100k lines of the open source code I've ever written, that one piece confuses 10x more people than all of the rest of it.

Welcome to the club! :)
