### ISSUE TITLE
Hash Tables is marked as Coming Soon

### ISSUE THREAD

**Issue by jyn514** [munificent/craftinginterpreters#320]
![Table of Contents](https://user-images.githubusercontent.com/23638587/50347931-5759f780-0505-11e9-9f68-64095aeae445.png)

I just saw the email you sent to the mailing list, thanks for your work on the book! It looks like you forgot to update the table of contents, though.

**Comment by munificent** [comment]
Try shift-refreshing the page in your browser. :)
