### ISSUE TITLE
spelling errors in Hash Tables chapter and performance of resizing

### ISSUE THREAD

**Issue by ghosttie** [munificent/craftinginterpreters#322]
The word busines instead of business:

> But with a hash table, it takes the same time to find that **busines** card when the stack has ten cards as when it has a million.

The word fewere instead of fewer:

> The bigger the array, the **fewere** indexes that get mapped to the same bucket and the fewer collisions that are likely to occur.

Early on you talk about performance and you talk about it more with regards to tombstones, but in "Allocating and resizing" there's no mention of performance even though it's recalculating all of the entries every time the table resizes.  Is this a fairly rare occurrence that averages out to not being a big deal?

**Comment by munificent** [comment]
The spelling errors are fixed now. Thanks!

>  there's no mention of performance even though it's recalculating all of the entries every time the table resizes. Is this a fairly rare occurrence that averages out to not being a big deal?

That's right. Like a dynamic array, whenever we resize the hash table we grow it by a multiple of its previous size. That means that the [amortized cost over a series of insertions is constant](https://en.wikipedia.org/wiki/Amortized_analysis).
