### ISSUE TITLE
Bug Chapter 20+: table.c tableFindString

### ISSUE THREAD

**Issue by Valakor** [munificent/craftinginterpreters#327]
Shouldn't this function also handle tombstone entries like findEntry?

**Comment by henke37** [comment]
If you support uninterning strings, yes. If you [keep stuffing it and never remove strings](https://blogs.msdn.microsoft.com/oldnewthing/20060502-07/?p=31333), no.

**Comment by Valakor** [comment]
That's sort of what I imagined we were assuming; maybe it's worth noting this decision explicitly? (It's entirely possible I missed something in the text, in which case ignore me!)

**Comment by munificent** [comment]
You are exactly right. This is a bug. (Bugs around tombstone handling are really hard to test for since it's a pain to get a hash table in just the right state where a tombstone comes into play.)

Thank you for noticing this!
