### ISSUE TITLE
Bug Chapter 20+: object.c takeString

### ISSUE THREAD

**Issue by Valakor** [munificent/craftinginterpreters#328]
Line 170 should be changed from:
```
FREE_ARRAY(char, chars, length);
```
to:
```
FREE_ARRAY(char, chars, length + 1);
                              ^^^^
```
This doesn't cause a memory leak since we're calling realloc with 0, but I have some simple memory tracking set up which falls over because it's expecting total bytes alloc'd == total bytes free'd.

**Comment by munificent** [comment]
Good catch! :D
