### ISSUE TITLE
Chapter 20: count when reusing a bucket on insert

### ISSUE THREAD

**Issue by ikatanic** [munificent/craftinginterpreters#335]
Hi Bob, thanks for the book! It's awesome. I'm enjoying chapter 20 right now.

Currently, `table->count` is increased by one even if we reuse a bucket (tombstone) on insert. 

Why not increase it only if we insert into a really empty bucket?

I know that in the best case this saves only one resize iteration, but it also makes `table->count` easier to define and reason about: it is simply a count of used buckets and tombstones.

In fact, you even define the count like that in the text, so this is probably inconsistent.

**Comment by munificent** [comment]
This was a bug. Good catch! I don't think I ever would have noticed that on my own, and it's difficult to write a test that observes the behavior.
