### ISSUE TITLE
Missing include in Chapter 19: Strings

### ISSUE THREAD

**Issue by hinrik** [munificent/craftinginterpreters#336]
In section 19.4, the `AS_STRING` macro gets used in `value.c`, but the text does not mention adding `#include "object.h"` to that file.

**Comment by shasta9** [comment]
Ditto for function printObject called at line 61 of value.c

**Comment by munificent** [comment]
This works out by the end of the chapter. Near the end, "value.c" includes "memory.h", which includes "object.h".

But you're right that it leaves you in a broken state until the very end of the chapter, which I try to avoid. Also, relying on transitive includes always feels kind of hacky. Fixed. Thanks!

**Comment by Owlblocks** [comment]
Wait, I think it's still there. Or something is. I realized I hadn't gotten an #include "memory.h" yet by the end of 19.4. Although that might be intentional (?). ALLOCATE is used during concatenation. It's probably fine to wait to include it, though, just wasn't sure if you were aware.
