### ISSUE TITLE
`creat` isn't part of the C standard library

### ISSUE THREAD

**Issue by aidtopia** [munificent/craftinginterpreters#340]
Regarding this marginal note in Chapter 20:

> Early linkers for C only treated the first six characters of external identifiers as meaningful. Everything after that was ignored. If you've ever wondered why the C standard library is so enamored of abbreviation -- looking at you, creat() -- it turns out it wasn't entirely because of the small screens (or teletypes!) of the day.

1.  `creat()` is not part of the C standard library.  It's a unix system call.  It's true that Posix environments expect their declarations to be added to C standard library headers.  Ironically, that renders those headers non-standard with respect to the C (and C++) standards.

2.  `creat()` is only five characters and `create()` would have been six, which means it isn't a good example of abbreviating to meet the six-character limit for external identifiers.

A better example might be `strncmp()`, which is part of the C standard library.  Although it's seven characters long, it was chosen to be distinguishable based on the first six.  If the function had been called `strcmpn()`, then some systems wouldn't have been able to distinguish it from `strcmp()`.

**Comment by munificent** [comment]
Oh, man, I love old C lore like this. Great suggestion. :)
