### ISSUE TITLE
Unable to compile Lox.java

### ISSUE THREAD

**Issue by reikdas** [munificent/craftinginterpreters#342]
I am getting several errors when trying to compile this file - https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Lox.java with 'javac Lox.java'.

Error logs - https://pastebin.com/xkTv9wJ8

My JDK is Oracle 1.8.

Am I doing something wrong?

**Comment by ksceriath** [comment]
Try compiling from the root of the source directory.
e.g.
javac com/craftinginterpreters/lox/Lox.java

**Comment by munificent** [comment]
Yes, @ksceriath is right. You need to compile it from the correct directory for Java to understand the package structure.

The [Java makefile](https://github.com/munificent/craftinginterpreters/blob/master/util/java.make) I use might be worth looking at as a reference.

**Comment by reikdas** [comment]
Thanks @ksceriath @munificent . Compiling from the source of the directory worked.
