### ISSUE TITLE
Typo: Chapter 20: Hash Tables (Section 20 . 2 Collision Resolution - Paragraph 1)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#349]
Location: Section 20 . 2 Collision Resolution (Paragraph 1)

Typo: To get the chance below 1% requires an array with 492,555 elements, over 4,000 thousand empty buckets for each one in use.

Correction: To get the chance below 1% requires an array with 492,555 elements, over 4,000 empty buckets for each one in use.

Action: Delete "thousand".

**Comment by munificent** [comment]
Thanks!
