### ISSUE TITLE
Typo: Chapter 20: Hash Tables (Section: 20.4.3 Allocating and resizing - Paragraph 2)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#352]
Location: Section: 20.4.3 Allocating and resizing (Paragraph 2)

Typo: But what about when we already one and we need to grow it?

Correction: But what about when we already have one and we need to grow it?

Action: Insert "have" between "already" and "one".

**Comment by munificent** [comment]
Must have fixed this one earlier, thanks!
