### ISSUE TITLE
Chapter 19 (DESIGN NOTE: STRING ENCODING), weird sentence

### ISSUE THREAD

**Issue by nicnys-8** [munificent/craftinginterpreters#353]
"UTF-8 is memory efficient and supports the whole Unicode range, but it’s variable-length encoding make it slow to access arbitrary code points."

It should be "its variable-length encoding makes it", right? Or maybe it's just my sleep-deprived, non-english speaking brain that can't parse the sentence properly.

**Comment by munificent** [comment]
Your sleep-addled non-English brain is correct! I don't have any excuse for mine. :)
