### ISSUE TITLE
Typo: Chapter 20: Hash Tables(Section 20.5 String Interning - Paragraph 13)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#354]
Location: Section 20.5 String Interning  (Paragraph 13)

Typo: We do that in two the higher-level functions that call allocateString()

Correction: We do that in the two higher-level functions that call allocateString()

Action: Replace "two the" by "the two".

**Comment by munificent** [comment]
Thank you for pointing out all of these mistakes! :D
