### ISSUE TITLE
Where to go to discuss learning this stuff?

### ISSUE THREAD

**Issue by morganpackard** [munificent/craftinginterpreters#355]
Hi! What an awesome resource! What would be the best communities to look to discuss questions related to learning this stuff? Ideally a group dedicated to this book in particular. Is there a stack exchange site or a reddit group or an AOL chatroom or something? Thanks!

**Comment by munificent** [comment]
I haven't tried to set up any community for the book itself. (I barely have time to write the book, much less moderate a forum for it.) I tend to hang out on the [programming languages subreddit](https://www.reddit.com/r/ProgrammingLanguages/). If someone wants to set something up more tailored to the book, I'd be happy to participate.

**Comment by morganpackard** [comment]
Cool! 10% chance I'll do that  (wish I could commit more seriously). If I do, any recommendations for which forum/community platform to use?

**Comment by munificent** [comment]
> If I do, any recommendations for which forum/community platform to use?

I like Reddit, but I'm pretty agnostic.

**Comment by morganpackard** [comment]
Cool. Thanks!
