### ISSUE TITLE
Clarification needed: 14 . 1 . 2 Why not compile to native code? (Paragraph 2)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#356]
Unclear paragraph:

Compiling directly to the native instruction set the chip supports is what the fastest languages do, and has been since the early days when engineers actually hand-wrote programs in machine code.

Question: What "has been since the early days..."?

**Comment by munificent** [comment]
Yeah, that conjunction didn't conjunct very well.

**Comment by cm1776** [comment]
By looking at https://github.com/munificent/craftinginterpreters/blob/master/book/chunks-of-bytecode.md we can see for ourselves that the issue reported above has been dealt with. However, http://www.craftinginterpreters.com/chunks-of-bytecode.html still has the original problem/issue.

Suggestion: Synchronize http://www.craftinginterpreters.com/ with https://github.com/munificent/craftinginterpreters/blob/master/book/ as soon as possible. This will prevent people from reporting errors that have already been corrected.

**Comment by munificent** [comment]
Yeah, I'm going to push a new build soon with the next chapter. :)
