### ISSUE TITLE
Small bug in `tableSet` in Chapter 20: Hash Tables

### ISSUE THREAD

**Issue by crazymerlyn** [munificent/craftinginterpreters#358]
After the addition of tombstone entries, the chapter goes into details of fixing `findEntry` and `adjustCapacity` to handle tombstones. But another function that needs a small fix is `tableSet`. If the entry found by `tableSet` is a tombstone, the table count should not be increased. The c code handles it properly but the chapter doesn't discuss it.

**Comment by munificent** [comment]
Yeah, I have it fixed locally, but I haven't pushed a build of the site yet. I'll do that in a bit. :)
