### ISSUE TITLE
Primary "this" introduced prematurely?

### ISSUE THREAD

**Issue by Sidewinder1138** [munificent/craftinginterpreters#359]
Hi Bob! Still loving this book, and still very thankful for you putting time into it.

In 8.2.1 you modify the 'primary' grammar rule to add 'IDENTIFIER', which makes sense in the context of that section, but I just noticed that you also add "this" in there as well, which doesn't have anything to do with adding support for global variables obviously. It doesn't hurt anything, of course, but I thought this might be confusing for some people...

To double-check, I searched backwards and found that the last time you modify 'primary' previous to 8.2.1 was in 6.1, and it indeed doesn't have "this".

**Comment by munificent** [comment]
Good catch! I think I just forgot to remove `| "this"` when I copied that from the reference grammar.
