### ISSUE TITLE
Mixing up terminals and nonterminals

### ISSUE THREAD

**Issue by henke37** [munificent/craftinginterpreters#36]
> We need a production for cooked and pick "poached". That’s a nonterminal, so we add that. Now we’re back to the protein, so we add "eggs". We bounce back to breakfast and add "with". Now all that’s left is to pick a production for bread. We’ll pick "English muffin". That’s again a nonterminal, so we add that and we’re done:

Every single nonterminal should be terminal there.

**Comment by catharsis** [comment]
I saw that as well, I think #39 fixes them all.

**Comment by munificent** [comment]
Yes, thank you!
