### ISSUE TITLE
Typo: Chapter 18 (Section: 18 . 3 . 1 Unary negation and runtime errors - Paragraph 8)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#360]
Location: Section: 18 . 3 . 1 Unary negation and runtime errors (Paragraph 8)

Typo: This book isn’t a C tutorial, so I’ll skim it here ...

Correction: This book isn’t a C tutorial, so I’ll skim over it here ...

Action: Insert "over" between "skim" and "it"

**Comment by cm1776** [comment]
Talking about "C tutorials", why don't you suggest a few to the reader? I think this would be greatly appreciated.

**Comment by munificent** [comment]
Fixed in ba9ae7cf667c3f69e384cd8f7e5105c0a8a55a58.
