### ISSUE TITLE
Typo: Chapter 21 (Section: 1st Aside)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#362]
Location: 1st section. 1st Aside

Typo: C and C++ compilers usually have a variable of ways of compiling switch statements ...

Correction: C and C++ compilers usually have a variety of ways of compiling switch statements ...

Action: Replace "variable " by "variety"

**Comment by munificent** [comment]
Thanks, I clearly had variables on the brain.

**Comment by munificent** [comment]
Eek, I would be lost without you. I definitely don't feel annoyed by you helping me fix all my dumb mistakes. :)

I'm in the middle of the next chapter, but I'll try to get a fix for this out.
