### ISSUE TITLE
Suggestion: grey out the coming chapters from contents.html

### ISSUE THREAD

**Issue by stefanos82** [munificent/craftinginterpreters#364]
Also, it would be nice to have a "coming soon" or a "work in process" right next to them.

**Comment by munificent** [comment]
It does literally say "Coming Soon" next to the chapters that aren't done yet:

<img width="385" alt="screen shot 2019-02-04 at 7 52 53 pm" src="https://user-images.githubusercontent.com/46275/52252290-7d213d00-28b6-11e9-9df4-59b3dade5219.png">

:)

**Comment by stefanos82** [comment]
Oh my...my apologies, I didn't see the messages until I highlighted the entire page. I guess it needs a darker gray color.

**Comment by munificent** [comment]
Yeah, it's very faint. It's always a balancing act choosing colors like this since contrast preferences vary widely across readers. What is too faint for some is too distracting for others.
