### ISSUE TITLE
Typo: Chapter 21 (Section 21 . 4 Assignment - 2nd Aside)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#365]
Location: Section 21 . 4 Assignment  (2nd Aside)

Typo: Wouldn’t it be wild if a * b was as valid assignment target, though?

Correction: Wouldn’t it be wild if a * b were a valid assignment target, though?

Action: Replace "was as" by "were a". (Check with your local English grammar teacher!)

**Comment by munificent** [comment]
I actually prefer the informality of using "was" in the subjunctive mood, though I know it bothers some. My local grammar teacher would probably say that it's a matter of style, not correctness. Note that we no longer say, "If she be rich" ("is" -> "be") or "If he eat dinner" ("eats" -> "eat"). Verb conjugation in the subjunctive mood is dying. 😁
