### ISSUE TITLE
Inconsistency in isAtEnd() checks

### ISSUE THREAD

**Issue by veremenko-y** [munificent/craftinginterpreters#368]
Scanner's `advance` checks isAtEnd() in outside code.

	  private char advance() {                               
		current++;                                           
		return source.charAt(current - 1);                   
	  }

Parser's `advance` makes sure it's not at the end

	  private Token advance() {   
		if (!isAtEnd()) current++;
		return previous();        
	  }
	  
It is not the end of the world, but Scanner's `advance()` *could* throw an exception, if I start reorganizing the scanner for my own language, for example. But on the other hand it is clearly error in scanner.

It is almost like an `assert` should be here. It could be a side not, or just ignore me and close this issue.

P.S. Thank you for the great book.

**Comment by munificent** [comment]
You're definitely welcome to bring it up! :)
