### ISSUE TITLE
Sidenote about generating java code

### ISSUE THREAD

**Issue by henke37** [munificent/craftinginterpreters#37]
The java compiler can be run from within a Java program. Kinda cool thing to point out in a side note. Definitely a bad idea to actually do in the book, but a nice thing to point out in a side note.

**Comment by munificent** [comment]
Good idea! I'll try to remember to find a place to mention this. :)

**Comment by forax** [comment]
It's even easier with java 9, the module-info just need to "requires java.compiler".

**Comment by Qard** [comment]
Alternatively, if you're using Gradle you can run it as a dependent task:

```groovy
task generate_ast(type:JavaExec) {
   main = 'com.craftinginterpreters.tool.GenerateAst'
   classpath = sourceSets.main.runtimeClasspath
   args 'src/main/java/com/craftinginterpreters/lox/'
}
run.dependsOn generate_ast
build.dependsOn generate_ast
```

**Comment by munificent** [comment]
I never found a good place to mention this, so closing it out.
