### ISSUE TITLE
namedVariable() declares `int arg` only to cast it to `uint8_t`

### ISSUE THREAD

**Issue by silmeth** [munificent/craftinginterpreters#377]
In the [Global Variables](http://www.craftinginterpreters.com/global-variables.html) chapter you introduce the function `namedVariable()`, which calls the `uint8_t identifierConstant(Token* name)` function whose result is assigned with an implicit cast to `int arg`, and everywhere where `arg` is used during the chapter, it is cast again into `uint8_t`, the whole function at the end looks like this:

```C
static void namedVariable(Token name, bool canAssign) {
  int arg = identifierConstant(&name);

  if (canAssign && match(TOKEN_EQUAL)) {             
    expression();                          
    emitBytes(OP_SET_GLOBAL, (uint8_t)arg);
  } else {                                 
    emitBytes(OP_GET_GLOBAL, (uint8_t)arg);
  }                                        
}                                          
```

I guess you do this because, in the future, you will actually use `arg` as a signed `int` (and initialize it from a function returning a signed integer) more often than `uint8_t` in later chapters (like in [this comparison](https://github.com/munificent/craftinginterpreters/blob/master/c/compiler.c#L796)).

But right now there are just nonsensical suspicious casts `uint8_t` → `int` → `uint8_t` there without any underlying reason presented for them in the text.

I guess it’s to avoid modifying the `emitBytes()` lines later in the book – but then perhaps a short explanation (a side note?) that a signed integer here will come in handy for resolving possibly missing local variables in the future would improve reading experience for people like me who jump all over the chapter trying to find out why you do this. :)

**Comment by munificent** [comment]
You're right, these casts aren't needed. That variable does become an `int` in a later chapter, but it doesn't need to be one yet.
