### ISSUE TITLE
Context-Free vs Regular languages

### ISSUE THREAD

**Issue by Tordek** [munificent/craftinginterpreters#378]
In `representing-code` you say:

> Note that the production refers to its own rule. This is the key difference between context-free and regular languages. The former are allowed to recurse. It is exactly this that lets them nest and compose.

Which isn't quite right, as

    A -> aA

is a perfectly valid rule in a regular grammar. What CFLs _can_ do is mix them up; i.e., 

    A -> AaA

is not a valid rule in a Regular grammar.

Finally, the language you give as an example is regular. The proof for this is simple: you gave us the regular expression that matches it (after minimal transformation):

    (( "bacon" | "sausage" | ( "scrambled" | "poached" | "fried" ) "eggs" ) ( "and" ( "bacon" | "sausage" | ( "scrambled" | "poached" | "fried" ) "eggs" ) )* ( "with" ( "toast" | "biscuits" | "English muffin" ) )?
          |  "toast" | "biscuits" | "English muffin")

I think a fairer representation of CFLs would be to say that what they allow is nesting, or wrapping, as in

    x -> "(" x ")";

**Comment by munificent** [comment]
Thanks for catching this one, you're exactly right. I forgot that since regular languages do allow repetition, some recursive rules that can be mapped to repetition are still regular. I (hopefully!) changed the sample grammar to one that is actually context free.

**Comment by Tordek** [comment]
Looks great! Awesome work, by the way :)

**Comment by munificent** [comment]
I just noticed I need to rework some of the later half of the chapter to take into account the grammar changes too. Reopening so I don't forget. :)

**Comment by munificent** [comment]
Fixed in 798850a8112026f2ca1c18eb53f7a1db0c642854.
