### ISSUE TITLE
Typo: Chapter 6 (Section 6 . 2 . 1 The parser class)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#381]
Location: Section 6 . 2 . 1 The parser class

Typo: We can see that inside the rule, we must first find either a != or == token. So, if we don’t see one of those, we must be done with the sequence of equality operators. 

Correction: We can see that inside the rule, we must first find either a != or == token. So, if we don’t see any of those, we must be done with the sequence of equality operators. 

Action: "Replace "one of" by "any of"

**Comment by munificent** [comment]
I think I like "one of" a little more here. In this function you might first see several `!=` and `==` and then reach the end of them. The "one of" really only applies to *after* you've found some. I worry "any of" would cause a reader to interpret this as meaning no `!=` or `==` could appear anywhere.
