### ISSUE TITLE
Typo: Chapter 8 (Section 8 . 5 Scope)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#382]
Location: Section 8 . 5 Scope

Typo 1: Any variables declared inside the block disappear.

Correction 1: Any variable declared inside the block disappears.
Action 1: Replace "variables" by "variable" and "disappear" by "disappears".

Alternative 1: All variables declared inside the block disappear.

Typo 2: When we exit the block, we should remove any variables declared inside the block ...

Correction 2: When we exit the block, we should remove any variable declared inside the block ...
Action 2: Replace "any variables" by "any variable"

Alternative 2: When we exit the block, we should remove all variables declared inside the block ...

**Comment by munificent** [comment]
I think "any variables" is better here. A block can contain zero, one, or more variables, and I think "any" most clearly conveys that. :)
