### ISSUE TITLE
Typo: Section 11 . 3 . 1 Resolving blocks

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#383]
Typo: Lexical scopes nest and in both the interpreter and the resolver. They behave like a stack.

Correction: Lexical scopes nest and in both the interpreter and the resolver, they behave like a stack.

Alternative: Lexical scopes nest in both the interpreter and the resolver. They behave like a stack.

**Comment by munificent** [comment]
Nice catch!
