### ISSUE TITLE
Error when Section 3 . 9 . 6 Inheritance code is run

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#389]
Problem:

I ran the following code from Section 3 . 9 . 6 Inheritance:
       var benedict = Brunch("ham", "English muffin");
I got the following error: 
           Expected 0 arguments but got 2.
           [line 1]

Note: I used your own code from github.

**Comment by munificent** [comment]
This was a fun one!

There was indeed a bug in jlox, but not clox. In jlox, `init()` methods were not inherited like they are supposed to be. I fixed this, which also required going back and tweaking the chapters in a couple of places to make sense with the new code. I also added a test for this case.

Thanks for spotting this!
