### ISSUE TITLE
Misleading Comment: Section 17 . 4 . 3 Unary negation

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#390]
In the code below (taken from section 17 . 4 . 3 Unary negation),

typedef enum {                  
  PREC_NONE,                    
  PREC_ASSIGNMENT,  // =        
  PREC_OR,          // or       
  PREC_AND,         // and      
  PREC_EQUALITY,    // == !=    
  PREC_COMPARISON,  // < > <= >=
  PREC_TERM,        // + -      
  PREC_FACTOR,      // * /      
  PREC_UNARY,       // ! - +    
  PREC_CALL,        // . () []  
  PREC_PRIMARY                  
} Precedence;                   

the comment next to  PREC_UNARY ( // ! - + ) seems to suggest that Lox has a unary PLUS. 

Please fix the comment.

**Comment by munificent** [comment]
Your attention to detail is amazing!
