### ISSUE TITLE
"Test Your Language"

### ISSUE THREAD

**Issue by pqnelson** [munificent/craftinginterpreters#393]
(This is a "I want _more_" issue, not a "typo" or "error" issue.)

In the [design note](http://www.craftinginterpreters.com/chunks-of-bytecode.html#design-note) for chapter 14, "Test your language", I have a simple yet broad question: how?

You cover the "why" well (though I didn't need much convincing, I confess). But...

0. Are there specific _heuristics_ I should have when writing tests for my interpreter? Would writing a quickcheck-type randomly generated testing be a wise investment of time or not for interpreter testing? Or is this something which requires greater thought to come up with a "representative sample" of regression tests? 
1. How is this different than unit testing the code for the compiler? Can't I just unit test my interpreter and I call it a day?
2. Could I do this (the testing you advise) in the interpreted language itself? For example, if I were writing a lisp interpreter, is there any danger in my writing an `assert` macro, then creating a bunch of test cases to confirm my language does what I expect? (My intuition suggests _not_ to do this, since I could imagine a ["Mr Burns is indestructible"](https://youtu.be/aI0euMFAWF8) scenario, where a bunch of bugs in my interpreter "balance each other out", as it were.)
3. "How much" should each test...test? I mean, [`or` tests (lines 12-19)](https://github.com/munificent/craftinginterpreters/blob/164d110/test/logical_operator/or.lox#L12-L19) appear, by design or by accident, to include implicit tests of the behavior that assignment should return the value assigned to a variable. Is this "good form" for tests? It contradicts my (perhaps groundless, erroneous, and utterly irrational) belief that each test should test exactly one thing --- is that perception true? If so, is such a belief unmerited in testing interpreters?
4. Coverage concerns. I am having difficulty articulating my intuition here, but it seems like we want to make sure the test suite "covers the grammar" at the very least, in the sense that every grammar rule is tested. (If there is an untested grammar rule, intuition suggests we need to add more tests.) But is there _some_ notion of "coverage" for end-to-end testing an interpreter? If not, is there some criteria for determining "good" tests? I'm just paranoid about _forgetting_ to test some aspect of the interpreter or language, and I'm looking for ways to assuage my paranoia without fooling myself into believing I'm covered when I'm not.

I probably have a few more follow up queries, but I don't see "testing" really discussed anywhere in the literature beyond a paragraph or two saying "Yeah, you should test your compiler/interpreter." (Perhaps I'm reading the wrong literature! If there's any good writing on this topic, please recommend them!)

**Comment by munificent** [comment]
All of these are excellent questions! One could probably write a whole separate book just on testing for language implementations. But, alas, the book I am writing is already getting to be so huge I have to consider splitting it into two volumes, so I don't think I can add much here.

Your questions are great. I don't even have good answers for many of them after working on a language professionally for several years, including working on the test infrastructure for it. Language testing is hard. :-/
