### ISSUE TITLE
Within a function: cannot create, then return, a class with superclass

### ISSUE THREAD

**Issue by PJBaker** [munificent/craftinginterpreters#394]
Thought I'd try out mixins (as we've been discussing on Reddit) in Lox, and came across the following problem.

AFAICT, this code works as expected:

    fun f() {
        class C {}
        return C;
    }

But the following does not. On the line with `return C`, it gives "Error at 'C': Cannot read local variable in its own initializer":

    class B {}
    fun f() {
        class C < B {}
        return C;
    }

The cause of the problem seems to be within `classDeclaration` in `compiler.c`. If a class has a superclass, it does:

    beginScope();

    // Store the superclass in a local variable named "super".
    variable(false);
    addLocal(syntheticToken("super"));

This *declares* `super`, but it is never *defined*, which means that it is not given a `depth`. Then, after compiling the class body we reach:

    endScope();
    defineVariable(nameConstant);

Now, because `depth` was not set, `endScope` fails to remove `super` from `locals[]`. This causes`defineVariable` to actually mark `super` as defined, rather than the class itself.

**Comment by munificent** [comment]
Thanks, this does indeed sound like a bug in clox.
