### ISSUE TITLE
Suggestion to Readers : Vaughan Pratt Parser Tutorial

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#395]
I recently came across a simple, step-by-step tutorial for the Vaughan Pratt Parser.

Interested readers should go to https://engineering.desmos.com/articles/pratt-parser/ to read this tutorial. Should there be a problem with the link, search for "How Desmos uses Pratt Parsers".

**Comment by blackLearning** [comment]
thanks for sharing!

**Comment by munificent** [comment]
Thanks for the link. Since the book has a chapter on this and also links to another article I wrote that is a tutorial on Pratt parsers, I think that's probably sufficient. :)
