### ISSUE TITLE
Rearrange code: Chapter 21 (Section 21 . 1 . 2 Expression statements)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#397]
Consider the code snippet:

static void expressionStatement() {                        
  expression();                                            
  emitByte(OP_POP);                                        
  consume(TOKEN_SEMICOLON, "Expect ';' after expression.");
}  

I think we should first finish parsing before we generate code (as we have done in other similar code). In other words, the code should be written as follows:

static void expressionStatement() {                        
  expression();                                            
  consume(TOKEN_SEMICOLON, "Expect ';' after expression.");
  emitByte(OP_POP);                                      
}  

Is there some reason why we should not prefer and use the above code?

**Comment by munificent** [comment]
It doesn't make much of a difference one way or the other. One minor visible difference is which source location a runtime error will be associated with, though in this case the pop isn't likely to cause a runtime error anyway.

But I agree your suggestion looks a little nicer. :)
