### ISSUE TITLE
Possible typpo in VisitLogicalExpr

### ISSUE THREAD

**Issue by eugenioenko** [munificent/craftinginterpreters#398]
Looking through the code for the logical expression visitor inside the interpreter class  I think there might be a typpo.

This is the code in question:
```
 public Object visitLogicalExpr(Expr.Logical expr) {
    Object left = evaluate(expr.left);

    if (expr.operator.type == TokenType.OR) {
      if (isTruthy(left)) return left;
    } else {
      if (!isTruthy(left)) return left;
    }

    return evaluate(expr.right);
  }
```
It seems like in the case of an `||` (OR)  it will always return `left`  so  this:
`false || true` will end up returning false
Because both `isTruthy(left)` and `!isTruthy(left)` are returning `left`

Of course the code is quit complex so I might be wrong because I missed something.

**Comment by eugenioenko** [comment]
Sorry about that, after looking for the 5th time:
it returns `left` when `!isTruthy(left) and TokenType.AND`

no conflicts

**Comment by munificent** [comment]
Glad you figured it out. :)
