### ISSUE TITLE
1.1.1 Is ASP.NET really a DSL?

### ISSUE THREAD

**Issue by timsneath** [munificent/craftinginterpreters#399]
Nit, but I know you care about nits. ASP.NET is a web framework (the Microsoft.AspNet.* class library). Many (most?) ASP.NET projects are written purely in C#, so I'm wondering what the DSL is. Wondering if you really mean [Razor](https://weblogs.asp.net/scottgu/introducing-razor)?

**Comment by munificent** [comment]
I was thinking more about the old ASP.NET Web Forms .aspx files and the special tags they allow, but I admit I know next to nothing about the platform. Is it a reasonable example or should I come up with something else?

**Comment by timsneath** [comment]
Mostly, the syntax was `<%` ... `%> as an escape sequence to embed C# code, and then custom server-side controls like `<asp:Button />` that got rendered into an `<input type="button" />`. I _guess_ you could think of the server-side controls as a DSL... but with so many other parts to ASP.NET, it might be better to pick something like XAML as an example if you want something readily accessible to the Microsoft crowd.

**Comment by munificent** [comment]
XAML is a great idea. I'll do that.
