### ISSUE TITLE
Typo: Section 22 . 1 Representing Local Variables

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#402]
Typo: The state all lives in this new struct:

Correction: The state lives in this new struct:

Action: Delete "all"

**Comment by munificent** [comment]
This one isn't a typo. I was using "state" as a mass noun and trying to make it clear that everything goes there. :)

**Comment by cm1776** [comment]
In that case, what do you think of this:

"All of the state lives in this new struct:"

**Comment by munificent** [comment]
👍
