### ISSUE TITLE
Question: Section 22 . 3 Declaring Local Variables

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#404]
Excerpt : That index is stored in a single-byte operand, which means the VM only supports up to 255 local variables in scope at one time.

Question: A single byte (no sign) ranges from 0 to 255 inclusive. Hence one byte can represent a total of 256 numbers. Why then does the VM only support up to 255 local variables?

**Comment by munificent** [comment]
Fixed in bbef752bacbc53b19711365a17660be54924095d.

Technically, the VM does only allow 255 locals because slot zero ends up being reserved to refer to `this` or the function being called. But we haven't gotten to that yet and arguably those are "locals" because they're on the stack.
