### ISSUE TITLE
layout issue in Chapter 22

### ISSUE THREAD

**Issue by ghosttie** [munificent/craftinginterpreters#406]
The snippet identifying the code location overlaps with the comment

![ScreenClip](https://user-images.githubusercontent.com/1552778/55008970-339cc680-4fb8-11e9-96e8-2dd1431ea6d3.png)

**Comment by munificent** [comment]
Interesting. The aside *should* be a few lines down from that.

Can you try force-refreshing your browser and see if that helps? What OS/browser/version are you using?

**Comment by ghosttie** [comment]
Hard refresh didn't fix it

Window 10/Chrome 75 (dev channel)

**Comment by cm1776** [comment]
In both Firefox 66.0.2 and Opera Version:58.0.3135.127, running on Windows 10 Pro, the aside appeared OK.

**Comment by munificent** [comment]
I can't seem to repro this and no one else has reported it. Maybe something weird in the dev channel build of Chrome? Closing this for now unless it shows up for other people.
