### ISSUE TITLE
Chapter 22 Section 3: Undefined variable in declareVariable

### ISSUE THREAD

**Issue by TheZxcv** [munificent/craftinginterpreters#407]
The first snippet of the function `declareVariable` in section 22.3 doesn't contain the declaration of `name`.

I guess line 558 should be before line 556.
https://github.com/munificent/craftinginterpreters/blob/c85f9a5e5006165e53341705c2c154fcfed76c8f/c/compiler.c#L556-L558

**Comment by munificent** [comment]
Oh, nice catch, thanks!
