### ISSUE TITLE
Undefined Variables Can Be Used (Section 21 . 4 Assignment)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#409]
Start a new REPL session of clox (the clox code at the end of Chapter 21).

Type in the following:

>>> name = "Bob";

You get the expected error message:

>>> Undefined variable 'name'.
>>> [line 1] in script

Now type in the following:

>>> print name;

You get the UNEXPECTED result below:

>>> Bob

I think the above result is due to the following code in vm.c

      case OP_SET_GLOBAL: {                                     
        ObjString* name = READ_STRING();                        
        if (tableSet(&vm.globals, name, peek(0))) {             
          runtimeError("Undefined variable '%s'.", name->chars);
          return INTERPRET_RUNTIME_ERROR;                       
        }                                                       
        break;  

When you assign to an undeclared variable, said variable is inserted into the vm.globals table. Upon detecting the error, the above code leaves the variable in the vm.globals table and returns an error code. Hence access to this variable is possible at a later period during the same REPL session.

To prevent the above error, simply delete the undeclared variable from vm.globals. See below:

         case OP_SET_GLOBAL: {
            ObjString* name = READ_STRING();
            if (tableSet(&vm.globals, name, peek(0))) {
               tableDelete(&vm.globals, name); // delete undeclared variable
               runtimeError("Undefined variable '%s'.", name->chars);
               return INTERPRET_RUNTIME_ERROR;
            }
            break;
         }

**Comment by cm1776** [comment]
Should be Chapter 21 (not Chapter 12)

**Comment by munificent** [comment]
Wow, excellent catch. How do you find these things?!
