### ISSUE TITLE
Placement of `synchronize()` in the book

### ISSUE THREAD

**Issue by AndroxxTraxxon** [munificent/craftinginterpreters#410]
I'm working my way through this book using Gradle and VS Code. I must say that you've done a fantastic job to this point. 

I just had a small thought on the placement of the section titled _Synchronizing a recursive descent parser_. (6.3.3) You introduce the concept beautifully, but the code (`lox/Parser.java::synchronize()`) remains inactive until Section 8.2.2, and the actual effect of the synchronization isn't really seen until then, though one could basically imagine what the intent of the code is. 

I think it might be worth considering moving a portion of the synchronizing content/introduction to Section 8.2.2, where it is more impactful, and you can immediately see why it is necessary.

**Comment by munificent** [comment]
Yeah, this is one of the ugly corners of the book. As much as possible, I try to minimize dependencies in chapters and structure the code such that I can cover a complete concept in a single chapter. We really need to talk about error handling as soon as we start doing expression parsing, but it's too big to stuff statements into that chapter too. So synchronization gets smeared out a little.

Chapter 8 is already one of the longest chapters in the book, so I think it's best to leave the error recovery code in 6 where there's a little more room for it, so to speak. It's definitely not a perfect solution, but it's the best I could come up with.
