### ISSUE TITLE
Heads Up: Chapter 5 (Online vs Latest Github)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#413]
From Section 5 . 1 . 1 Rules for grammars (Online version), we get:

  Using that, here’s a grammar for breakfast menus:

  breakfast → protein "with" bread ;
  breakfast → protein ;
  breakfast → bread ;
  
  protein   → protein "and" protein ;
  protein   → "bacon" ;
  protein   → "sausage" ;
  protein   → cooked "eggs" ;
  
  cooked    → "scrambled" ;
  cooked    → "poached" ;
  cooked    → "fried" ;
  
  bread     → "toast" ;
  bread     → "biscuits" ;
  bread     → "English muffin" ;

From the corresponding section of the Github version (Latest commit 77484fd), we get: 

  breakfast → protein "with" breakfast "on the side" ;
  breakfast → protein ;
  breakfast → bread ;
  
  protein   → "bacon" ;
  protein   → "sausage" ;
  protein   → cooked "eggs" ;
  
  cooked    → "scrambled" ;
  cooked    → "poached" ;
  cooked    → "fried" ;
  
  bread     → "toast" ;
  bread     → "biscuits" ;
  bread     → "English muffin" ;

Differences: 
1. we are missing the following rule in the Github version: 
     protein   → protein "and" protein ;
but we reference that rule later in the same chapter.

2. the first rules are different:
   breakfast → protein "with" bread ; (Online)
   breakfast → protein "with" breakfast "on the side" ; (Github)

Note: Because of the issues raised above, you will have to revisit the grammar rules in Section 5 . 1 . 2
(Enhancing our notation) and change them accordingly. The "breakfast" rule appears to be a major culprit.
Kindly fix these issues.

**Comment by munificent** [comment]
Should be fixed now, but thanks for noticing and let me know if I missed anything. :)

**Comment by cm1776** [comment]
Consider this excerpt (from the latest github code):

crispiness → "really" ;
crispiness → really "really" ;

really (as a non-terminal) is never defined. 

I guess you really wanted to say:

crispiness → "really" ;
crispiness → crispiness  "really" ;
