### ISSUE TITLE
Not Clear: Section 5 . 3 . 1 The Expression Problem

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#414]
The following is unclear:

###
They called this the “expression problem” because—like we are here—the example problem they used was about expression types in an interpreter ...
###

What does "like we are here" mean? 

Does it mean that just like we did, the nerds used an example problem about types in an interpreter?

Please clarify.

**Comment by munificent** [comment]
Took another stab at it. Let me know what you think.

**Comment by cm1776** [comment]
I think we should eliminate ourselves from this paragraph:

A bunch of smart language nerds noticed that neither style made it easy to add both rows and columns to the table. They called this difficulty the “expression problem” because—like we are now—they first ran into it when they were trying to figure out the best way to model expression syntax tree nodes in a compiler.

Result:

A bunch of smart language nerds noticed that neither style made it easy to add both rows and columns to the table. They called this difficulty the “expression problem” because they first ran into it when they were trying to figure out the best way to model expression syntax tree nodes in a compiler.
