### ISSUE TITLE
Miswording: Section 3.2.1 - Dynamic typing (Aside)

### ISSUE THREAD

**Issue by jrsnzc** [munificent/craftinginterpreters#422]
*In sentence:
After all, the two languages we’ll be using to implement Lox are both statically typed.

*Correction: Type checking.
After all, the two languages we’ll be using to implement Lox are both dynamically typed.

**Comment by merl111** [comment]
Lox is implemented in Java and C, both are statically typed not dynamically. So the original sentence seems to be correct.

**Comment by jrsnzc** [comment]
Correct. I misread the sentence. I thought it was referring to Lox implementations.
