### ISSUE TITLE
Unclear wording in solution for Chapter 7 - Challenge 3

### ISSUE THREAD

**Issue by jpcornwell** [munificent/craftinginterpreters#423]
Don't know if you are wanting corrections on the solutions (since they're not a part of the book) but came across this confusing piece of text in the solution for Chapter 7 - Challenge 3.

> On the other hand, given that Lox gives the user know what to catch and handle runtime errors, not throwing one might be more flexible.

Is this commenting on the fact that the user doesn't have any way to handle thrown exceptions, and therefore it may be a kindness to the user to allow the program to keep running? (I'm still working my way through the book, but it looked like exception handling was not a feature of Lox.)

**Comment by munificent** [comment]
Oops, that was just a typo. Thanks for point it out!
