### ISSUE TITLE
Where's the pun?

### ISSUE THREAD

**Issue by skybrian** [munificent/craftinginterpreters#424]
http://craftinginterpreters.com/jumping-back-and-forth.html

At the end of the chapter, just before the exercises: "I couldn’t resist the pun. I regret nothing."

I didn't see any pun. What did I miss?

**Comment by nareshganduri** [comment]
The pun is in the line, "We’ve taken a big leap forward in our VM," which simultaneously means "we've made big progress" and also the VM is literally leaping forward through the bytecode with jump instructions.

Hence, a pun.

**Comment by munificent** [comment]
What @nareshganduri said. :)
