### ISSUE TITLE
Typo: Design Note (Chapter 23)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#427]
Typo:  He doesn’t provide any evidence to support this claim, but I accept with it.

Correction:  He doesn’t provide any evidence to support this claim, but I agree with him.

Alternative:
 He doesn’t provide any evidence to support this claim, but I accept it.

**Comment by cm1776** [comment]
Another typo in same Design Note:

Typo: Even if the marker points inside a branch, we can still tell we are.

Correction: Even if the marker points inside a branch, we can still tell where we are.

**Comment by skybrian** [comment]
Also: consider "call stack" instead of "callstack".

At least, Wikipedia has it that way: https://en.wikipedia.org/wiki/Call_stack
