### ISSUE TITLE
Typo: Section 23.4  ( forStatement() code )

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#429]
If we only supported for loops with empty clauses like for (;;), then we could implement it like this:

Typo: 
consume(TOKEN_SEMICOLON, "Expect ')' after for clauses.");

Correction:
consume(TOKEN_RIGHT_PAREN, "Expect ')' after for clauses.");

**Comment by munificent** [comment]
Fixed by #425. :)
