### ISSUE TITLE
Suggestion: Section 23.2.1 (Logical or operator)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#433]
With regards to the implementation of the "or" operator, I agree with you when you declare that "... this isn’t the best way to do this. There are more instructions to dispatch and more overhead. There’s no good reason why || should be slower than &&. ..."

I suggest you  rewrite "static void or_(bool canAssign)" in the "best way" and relegate the original code to a side note.

**Comment by munificent** [comment]
It's not straightforward to have alternate code in a side note, and this would make for a *really* long one. I realize the current formulation is a little weird, but I think it actually makes for a slightly more interesting read. Also, I really just want to keep moving forward and get to the end of the book. :)

**Comment by cm1776** [comment]
I definitely agree with you that you should "keep moving forward and get to the end of the book". January 2020 looks like a good date for publication!

I think with the introduction of OP_JUMP_IF_TRUE opcode, you will get an or_() function that is similar to the and_() function and is as easy to understand. 

Anyway, you can come back to this when you are at the end of the book.

Thanks for all your work so far.

**Comment by cm1776** [comment]
Here's an example for another version of or_() in compiler.c:

static void or_(bool canAssign) {
  int endJump = emitJump(OP_JUMP_IF_TRUE);

  emitByte(OP_POP);
  parsePrecedence(PREC_OR);

  patchJump(endJump);
}

In the vm module, I added:

      case OP_JUMP_IF_TRUE: {
        uint16_t offset = READ_SHORT();
        if (!isFalsey(peek(0))) vm.ip += offset; // note the "!" in front of isFalsey
        break;
      }

**Comment by munificent** [comment]
> you will get an or_() function that is similar to the and_() function

That's true, but is an argument *against* doing it. :) As much as possible, I try to make each bit of code and content in the book contain unique information. If `_and()` and `_or()` are implemented the same way, the reader doesn't learn anything from `_or()` that they didn't already know. Using a suboptimal desugaring at least hints towards a different way of looking at compiling.
