### ISSUE TITLE
Typo: Challenges (Chapter 23)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#434]
Refer to challenge #2

Typo: "... A continue statement jumps to the top of the nearest enclosing loop. In a for loop, this skips evaluating the increment clause, if there is one ..."

Correction:  "... A continue statement jumps to the top of the nearest enclosing loop. In a for loop, this skips evaluating the rest of the loop body ..."

**Comment by munificent** [comment]
I think the prose was correct, though a little unclear. I do want to point out that a continue doesn't just skip the body, but also the increment clause too. Or did I get something else wrong here?

**Comment by cm1776** [comment]
Below is a snapshot of a jshell session:

jshell> for (int i = 0; i < 10; i++) {
      ...> if (i % 3 == 0) continue;
      ...> System.out.print(i + " ");
      ...> }
1 2 4 5 7 8
jshell>

As you can see, if the continue skipped the increment clause (i++), we would have an infinite loop. But we do not. Hence the increment clause is NOT skipped by the continue statement.

I think Lox ought to have the same behavior.

**Comment by munificent** [comment]
I'm clearly an expert.
