### ISSUE TITLE
Closures, section 3.8.1

### ISSUE THREAD

**Issue by smiffyusher** [munificent/craftinginterpreters#435]
I just started reading your book today.  

In section 3.8.1 in the first code block example, shouldn't:

`print identity(addPair)(1, 2); // Prints "3".`

actually be:

`print identity(addPair(1, 2)); // Prints "3".`

since you are passing a function call (and its arguments) to the function "identity"?

Thanks for taking the time to write such a great book, I like your writing style.

Scott

**Comment by munificent** [comment]
Nope, this example is correct as it is. The point is that it's *not* passing the result of a function call to `identity`. It passes the function itself (`addPair`). Then `identity()` returns that function, which is *then* invoked passing in 1 and 2. :)
