### ISSUE TITLE
Missing code: Answer to Challenge #3 (Chapter 15)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#438]
Location:
https://github.com/munificent/craftinginterpreters/blob/master/note/answers/chapter15_virtual/3.md

Problem: The VM struct below is missing a declaration for stack. (Value* stack;)

typedef struct {
  Chunk* chunk;
  uint8_t* ip;
  int stackCount;
  int stackCapacity;
} VM;

**Comment by cm1776** [comment]
On the same page as above, you state:

"you can statically determine the maximum amount of stack space a chunk of bytecode could ever use."

Question: What are the steps to take to be able to determine the maximum amount of stack space above?

**Comment by munificent** [comment]
> Question: What are the steps to take to be able to determine the maximum amount of stack space above?

During compilation, you always know how many stack slots are in use for locals and temporaries at any point in time. So you just keep a running tally of the highwater mark — the greatest amount of stack space used at any point, and then store that in with the resulting function object.
