### ISSUE TITLE
5.1.2 Enhancing our notation

### ISSUE THREAD

**Issue by smiffyusher** [munificent/craftinginterpreters#439]
Shouldn't this:

```
breakfast → protein ( "with" breakfast "on the side" )? ;
          | bread ;
```
actually read:

```
breakfast → protein ( "with" breakfast "on the side" )?
           | protein
           | bread ;
```

Thanks for any insight you can provide.

Scott

**Comment by munificent** [comment]
Nope, those two are equivalent. Note the `?` at the end of the first line. That makes everything in the parentheses optional which means that this:

```
breakfast → protein ( "with" breakfast "on the side" )?
          | bread ;
```

Is equivalent to:

```
breakfast → protein ( "with" breakfast "on the side" )
          | protein
          | bread ;
```

There is a stray semicolon in there, though. I'll fix that.
