### ISSUE TITLE
Section 17 . 6 . 1 (Parsing with precedence) missing arrowhead in diagram

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#442]
Consider: "...but as you read the code from the left to right.."

Suggested Change: "...but as you read the code from left to right..."

Note: I hope you don't think this is nitpicking!

**Comment by cm1776** [comment]
Question:

In the parsePrecedence(Precedence precedence) function, we check for the possibility that prefixRule is NULL, but we do not do the same for infixRule. Why not?

**Comment by cm1776** [comment]
A small matter:

In the first diagram of Section 17.6.1, the arrow from binary() to getRule() is missing an arrow-head.

**Comment by munificent** [comment]
> Note: I hope you don't think this is nitpicking!

Not at all!

> In the parsePrecedence(Precedence precedence) function, we check for the possibility that prefixRule is NULL, but we do not do the same for infixRule.

In the parse table, every rule with a NULL infix parser has precedence `PREC_NONE`. That's lower precedence than all possible precedences, which means the outer loop with `while (precedence <= getRule(parser.current.type)->precedence)` always exits.

> In the first diagram of Section 17.6.1, the arrow from binary() to getRule() is missing an arrow-head.

Drat! <reopens>

**Comment by woolsweater** [comment]
> In the parse table, every rule with a `NULL` infix parser has precedence `PREC_NONE`

I had the same question as cm1176. This note is very helpful to understand the implementation.

Minor suggestion, but since the parse table is not complete in this chapter, it might be worth a sentence in the sidebar that this will remain true even after the table is filled out.
