### ISSUE TITLE
Typo: Section 19 . 1 (Values and Objects)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#443]
Typo: "We can also go the other direction"

Correction: "We can also go in the other direction"

Note: Insert "in" between "go" and "the"

**Comment by munificent** [comment]
I think this one is OK as it is.

**Comment by cm1776** [comment]
In Section 19.2, you state:
"You can go in the other direction too. Given an Obj*, you can “downcast” it to an ObjString*. ..."

Why not "We can also go the other way"?

**Comment by munificent** [comment]
I like that. :)
