### ISSUE TITLE
Typo: Chapter 20 (CHALLENGES)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#445]
Challenge #1

Typo: 
If we exposed hash tables to Lox users as a first-class collection, it would useful to support different kinds of keys.

Correction:
If we exposed hash tables to Lox users as a first-class collection, it would be useful to support different kinds of keys.

Note: Add "be" between "would" and "useful"

**Comment by cm1776** [comment]
Location: https://github.com/munificent/craftinginterpreters/blob/master/note/answers/chapter20_hash/1.md

Typo: " ...  I don't think it's worthing caching the hash code. "

Correction: " ...  I don't think it's worth caching the hash code."

**Comment by cm1776** [comment]
Location: https://github.com/munificent/craftinginterpreters/blob/master/note/answers/chapter20_hash/1.md

Suggestion: 
The material that appears after the phrase "Here's the whole thing"  does not conform to the book style and is difficult to read. 

Please reformat the material.

**Comment by munificent** [comment]
I probably should walk through the diff on that last answer, but it's such a chore and the answers really are supplementary material, so I'm not going to worry about it, at least for now.

**Comment by cm1776** [comment]
I agree that it should be left for last.
