### ISSUE TITLE
Logical Operator Keywords (Chapter 23.2)

### ISSUE THREAD

**Issue by christilden** [munificent/craftinginterpreters#451]
The scanner is setup for keywords ‘and’ and ‘or’ for logical operators, but in Chapter 23.2 you refer to them as ‘&&’ and ‘||’. I used the wrong syntax in my test program and had to do some debugging to determine I was using the wrong syntax!

**Comment by munificent** [comment]
Oh, dear, that's embarrassing. I can't even remember the syntax of my own language! Thank you for pointing this out!
