### ISSUE TITLE
Using the test runner with non Java / C implementation

### ISSUE THREAD

**Issue by snowfrogdev** [munificent/craftinginterpreters#454]
I have tried to figure out how to use the test runner but I'm not familiar with Python and its ecosystem and am having a hard time figuring out how it works. I apologize in advance if what I'm asking seems trivial or obvious.

Is it possible to use the test runner to test an implementation of a Lox interpreter made in something else than Java or C, because looking at the code, and using the CLI command, it looks like `c` and `java` are your only two options?

I made a Node.js implementation, what do I need to do to use the test runner with my implementation?

**Comment by munificent** [comment]
It's currently hard-coded to run clox and jlox because that's all I need for my purposes, but it should be straightforward to get it working with your interpreter.

```python
def node_interpreter(tests):
  path = 'path/to/your/interpreter/here' # <-- Fill this in.
  INTERPRETERS['node'] = Interpreter('node', 'c', [path], tests)
```

And then right before `class Test:`, add:

```python
node_interpreter({
  'test': 'pass',

  # These are just for earlier chapters.
  'test/scanning': 'skip',
  'test/expressions': 'skip',
})
```

I haven't tested that, but something along those lines should work.
