### ISSUE TITLE
Group/Label Lox implementations by their status

### ISSUE THREAD

**Issue by tysonzero** [munificent/craftinginterpreters#455]
I was looking through the Lox implementations sections, largely to informally compare how languages compare for implementing compilers/interpreters.

I was very surprised to find that the first listed Go implementation was as concise as the first listed Haskell implementation. When I investigated further I realized that the Haskell implementation appears fully implemented, and the Go implementation is nowhere near done, fitting much more with my expectations.

If implementations were grouped/labeled based on whether or not they are feature complete and also if they comply with the spec would be fantastic, and really improve Lox's utility as a comparison tool for compiler/interpreter dev.

**Comment by munificent** [comment]
This is a good idea, but it's probably not a good use of my time to monitor the status of each of these implementations and re-sort the lists as needed. I'm trying to finish the book. :)
