### ISSUE TITLE
Book splitting

### ISSUE THREAD

**Issue by evanxg852000** [munificent/craftinginterpreters#461]
Just got the new chapter announcement newsletter.
Thank you for the hard work and for putting this resource for free. I can't wait to buy a hard copy of this book as I believe this book is one of the few I will always have on my desk. Aside from the technology the reading is just a pleasure.
I am starting to be concerned about the size of the book as well. I would like you to think about splitting into two books at the end as:
- Crafting interpreters I (includes part 1 & 2)
- Crafting interpreters II (includes part 3)

People tend to keep momentum when they feel like reaching the end when reading and coding along with a book. The other reason is that each part 2 and part 3 of the current book don't use the same programming language. Some readers will just want to stay on the Java side while not planning a deep dive into VM. 
I would just like you @munificent  to think about and maybe discuss here while the book is nearing the finish line.  Because right now the focus is to finish the book first.

**Comment by munificent** [comment]
Thanks for bringing this up! An email from a reader suggested the same thing. It's a good idea.

Once all of the chapters are done, I'll start working on the page layout for the print edition. It's going to take some time to decide on a page size and all the various metrics. From there, I'll layout a sample chapter. That will let me estimate the total page count of the book. That in turn should give me enough data to decide if it makes more sense as one or two volumes.

I had no idea the book was going to be this big when I started, but you're right that it's reaching the point where two volumes might be more manageable. At the same time, if it can fit in one book, I think that makes for a better, cheaper experience for readers. They get the whole thing for one price and it feels more like a single complete work. But I dislike books that are too huge and heavy to haul around too, so two smaller volumes might be better.

**Comment by evanxg852000** [comment]
Thanks for the update on this. A huge thanks for these resources and for all the effort you put in it. Again I think the highlight for me so far in this book is your writing style. It's just awesome 🥇👏 . Wish you all the best in every aspect of life so you can keep on delivering.

**Comment by munificent** [comment]
Closing this because there isn't any action I need to take on it. Once I start working on the print edition, I'll keep this in mind.
