### ISSUE TITLE
Bug: Section 24.3

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#464]
"Assuming we did all of that correctly, we finally got clox back to a runnable state. Fire it up and it does… exactly what it did before."

Note: At this point in the book, we get a C compiler error when we attempt to compile clox. We have NOT yet updated runtimeError(const char* format, ...).

**Comment by Moosemorals** [comment]
Also at this point, printObject (object.c) throws a NPE because function->name is NULL.

**Comment by munificent** [comment]
Thanks for pointing this out!

I've generally tried to make sure the code compiles are frequently throughout the chapters as possible but haven't built anything to verify that, even though the pieces are there in the build system. This was a good reminder to write some tooling. Now I have a script that ensures the code at least compiles at various points in each chapter. (The next step would be running the tests and pinning down which tests we expect to pass, but that's pretty tedious.)
