### ISSUE TITLE
Parameter count limit should be 255

### ISSUE THREAD

**Issue by munificent** [munificent/craftinginterpreters#468]
When I changed it from 8, I missed one part:

```c
      if (current->function->arity > 8) {
        error("Cannot have more than 8 parameters.");
      }
```

**Comment by cm1776** [comment]
Be sure to make corresponding changes in Chapter 10 - Functions (http://craftinginterpreters.com/functions.html).

For example:

        if (parameters.size() >= 8) {                                 
          error(peek(), "Cannot have more than 8 parameters.");       
        }
