### ISSUE TITLE
Typo: "initializion"

### ISSUE THREAD

**Issue by camelid** [munificent/craftinginterpreters#469]
Typo: "That's the __initializion__ side. We also need a couple of changes on the other end when we finish compiling some code:"

Should be: "That's the __initialization__ side. We also need a couple of changes on the other end when we finish compiling some code:"

Fix: Change "initializion" to "initialization"

**Comment by camelid** [comment]
Section 24.2.1

**Comment by munificent** [comment]
This is fixed now, thanks!
