### ISSUE TITLE
Constants, globals, stack etc

### ISSUE THREAD

**Issue by gummybears** [munificent/craftinginterpreters#471]
First of all thanks for providing a great resource on writing interpreters

I am reading chapter 15, where you give the example 1.2 + 3.4 but I am confused
1) Why are you pushing and popping the values in addConstant ? 

2) You use the array constants and use the index as the bytecode, but it seems
the index can become larger than 255 in writeValueArray ?

3) Quick question on OP_DEFINE_GLOBAL, chapter 19, not clear from the text as I don't see the set of bytecode instructions, you use it to declare globals AND also assign a value ? So I need to use 2 constants, 1 for the key and 1 for the value ? 

```
// example from chapter 15
int constant = addConstant(&chunk, 1.2);
  writeChunk(&chunk, OP_CONSTANT, 123);   
  writeChunk(&chunk, constant, 123);      
  constant = addConstant(&chunk, 3.4);    
  writeChunk(&chunk, OP_CONSTANT, 123);   
  writeChunk(&chunk, constant, 123);

  writeChunk(&chunk, OP_ADD, 123);    
```
Looking at the code for addConstant in chunk.c, I see you are also doing a push and a pop
```
//> add-constant
int addConstant(Chunk* chunk, Value value) {
//> Garbage Collection not-yet
  // Make sure the value doesn't get collected when resizing the array.
  push(value);

//< Garbage Collection not-yet
  writeValueArray(&chunk->constants, value);
//> Garbage Collection not-yet
  pop();
//< Garbage Collection not-yet
  return chunk->constants.count - 1;
}
```

**Comment by munificent** [comment]
> Why are you pushing and popping the values in addConstant ?

We don't do that in chapter 15. That code gets added later in the "Garbage Collection" chapter. Like the comment says, it ensures that the new constant value can still be found by the GC if one happens while it is resizing the constant array.

> You use the array constants and use the index as the bytecode, but it seems
the index can become larger than 255 in writeValueArray ?

Yes, we check for that potential overflow in the next chapter. :)

> Quick question on OP_DEFINE_GLOBAL, chapter 19, not clear from the text as I don't see the set of bytecode instructions

`OP_DEFINE_GLOBAL` gets introduced in chapter 21 and is fully explained there.

> you use it to declare globals AND also assign a value ? So I need to use 2 constants, 1 for the key and 1 for the value ?

It defines a global variable. The name is a string stored in the constant table. It pulls the variable's value from the top of the stack.

Hope that helps! :)
