### ISSUE TITLE
Formatting Issue: Section 24.3.3

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#476]
Consider:

"The last piece of code referring to the old VM fields is runtimeError(). We’ll revisit that later in the chapter, but for now, let’s change it to:    

  fputs("\n", stderr);                                         

  CallFrame* frame = &vm.frames[vm.frameCount - 1];            
  size_t instruction = frame->ip - frame->function->chunk.code;
  int line = frame->function->chunk.lines[instruction];        
  fprintf(stderr, "[line %d] in script\n", line);              

"
The last last line of code in the snippet is grayed out, even though it replaced previous code.

**Comment by munificent** [comment]
I think the greyed out line of code is already there. It appears in [Types of Values 18 . 3 . 1](http://craftinginterpreters.com/types-of-values.html#unary-negation-and-runtime-errors). Is it the wording of the sidebar that's confusing? It means "remove 2 lines and add all the non-grey lines here".

**Comment by cm1776** [comment]
Sorry for the false negative.

I have just checked the latest release of your book. You are right when you say the grayed out line is already present from Chapter 18.
