### ISSUE TITLE
Missing word(s)?

### ISSUE THREAD

**Issue by evg** [munificent/craftinginterpreters#478]
Hi Bob,

Thanks for the great book. I am reading it right now while on vacation, it beats any novel imho  :-)

Just a small note: the chapter about functions has this line

We know we’ll be done with c and d before we are a. 

I guess it should be something like

We know we’ll be done with c and d before we are done with a. 

Regards
Edwin

**Comment by cm1776** [comment]
Your issue has already been fixed. 

See https://github.com/munificent/craftinginterpreters/pull/460

**Comment by munificent** [comment]
@cm1776 is right, though this is a good reminder for me to actually push those changes to the site. :)
