### ISSUE TITLE
Code insertion mistake 16.1

### ISSUE THREAD

**Issue by jptemplin** [munificent/craftinginterpreters#479]
Last code insertion in 16.1 (16.1.2 to be exact):

<< scanner.c
add after struct Scanner

but the code illustration shows the insertion after the definition "Scanner scanner;" not the struct.

It doesn't change the semantics of the code, but it might confuse someone as they edit.

![Section 16 1](https://user-images.githubusercontent.com/51379861/62430245-f1169380-b6e7-11e9-9ac5-9b8cecd5a23d.png)

**Comment by munificent** [comment]
Nice catch, thanks!
