### ISSUE TITLE
Question: Section 14.3.1

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#480]
Consider:
[Begin Quote]

Dynamic arrays provide:

Cache-friendly, dense storage.
Constant-time indexed element lookup.
Constant-time appending to the end of the array.

Those features are exactly why we used it all the time in jlox under the guise of Java’s ArrayList class.

[End Quote]

Question: What did we use?

If the answer is "dynamic arrays" then you need to update the last sentence in the above excerpt as follows:

"Those features are exactly why we used them all the time in jlox under the guise of Java’s ArrayList class."

Is this being pedantic? I hope not.

**Comment by munificent** [comment]
Not pedantic at all! Overuse of pronouns is a perennial problem in technical writing. I really appreciate you pointing these out.
