### ISSUE TITLE
Suggestion: 20.4.4

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#482]
Consider this snippet:

```c
bool tableGet(Table* table, ObjString* key, Value* value) {      
  if (table->entries == NULL) return false;

  Entry* entry = findEntry(table->entries, table->capacity, key);
  if (entry->key == NULL) return false;                          

  *value = entry->value;                                         
  return true;                                                   
}
```

There are two ways in which table can be empty. Either table->entries == NULL or table->count == 0. You considered only one of the possibilities. 

I suggest the above code be changed to:

```c
bool tableGet(Table* table, ObjString* key, Value* value) {      
  if (table->entries == NULL || table->count == 0) return false;

  Entry* entry = findEntry(table->entries, table->capacity, key);
  if (entry->key == NULL) return false;                          

  *value = entry->value;                                         
  return true;                                                   
}
```

Note: Your tutorial on hash tables is awesome!

**Comment by cm1776** [comment]
Using the same argument, the code in Section 20.4.5 should be:

`bool tableDelete(Table* table, ObjString* key) {                 
  if (table->entries == NULL || table->count == 0) return false; // <--- Change made here

  // Find the entry.                                             
  Entry* entry = findEntry(table->entries, table->capacity, key);
  if (entry->key == NULL) return false;                          

  // Place a tombstone in the entry.                             
  entry->key = NULL;                                             
  entry->value = BOOL_VAL(true);                                 

  return true;                                                   
} `

**Comment by cm1776** [comment]
Ditto ObjString* tableFindString(Table* table, const char* chars, int length, uint32_t hash) in Section 20.5

`
ObjString* tableFindString(Table* table, const char* chars, int length, uint32_t hash) {
   // If the table is empty, we definitely won't find it.
   if (table->entries == NULL || table->count == 0) return NULL; // <--- Change made here

   uint32_t index = hash % table->capacity;

   for (;;) {
      Entry* entry = &table->entries[index];

      if (entry->key == NULL) {
         // Stop if we find an empty non-tombstone entry.
         if (IS_NIL(entry->value)) return NULL;
      } else if (entry->key->length == length &&
         entry->key->hash == hash &&
         memcmp(entry->key->chars, chars, length) == 0) {
         // We found it.
         return entry->key;
      }

      // Try the next slot.
      index = (index + 1) % table->capacity;
   }
}
`

**Comment by munificent** [comment]
Oh, good catch! In fact, we can do something even smarter. We don't need to check for a null bucket array at all. If the count is ever non-zero, we know the bucket array will not be null.
