### ISSUE TITLE
Section 21.2: This could be clearer.

### ISSUE THREAD

**Issue by jptemplin** [munificent/craftinginterpreters#483]
The text asks you to add the definitions of parseVariable() and identifierConstant() after parsePrecedence(). When working through the chapter, I initially added them after the definition of parsePrecedence(), not after the forward declare (which is really what you meant). After scratching my head over the C compiler errors I got, I realized where they should have gone instead.

Attached is the text snippet. You usually surround the insertions with code context before and after. It's unusual in this case that you just get the bare functions here without any context. That would have kept me out of trouble. This could be clearer. 

![Froward Declare](https://user-images.githubusercontent.com/51379861/62667823-65a33980-b957-11e9-9341-1714be5adfd0.PNG)

**Comment by cm1776** [comment]
Hello jptemplin:

Here is how I avoid the troubles you've been through.

I create an auxiliary header file and then make a forward declaration of ALL functions not already declared in the main header file (e.g. compiler.h). To aid in searching for a function, I arrange the declarations in alphabetical order. Then I include this auxiliary header file in the corresponding .c module file (e.g. compiler.c). 

Below is an example auxiliary header file for the compiler.c module (Applicable to the code in Chapter 21):

`#ifndef clox_compilerfd_h
#define clox_compilerfd_h

#include "common.h"
#include "chunk.h"
#include "scanner.h"
#include "value.h"


typedef struct {
   Token current;
   Token previous;
   bool hadError;
   bool panicMode;
} Parser;


typedef enum {
   PREC_NONE,
   PREC_ASSIGNMENT,  // =
   PREC_OR,          // or
   PREC_AND,         // and
   PREC_EQUALITY,    // == !=
   PREC_COMPARISON,  // < > <= >=
   PREC_TERM,        // + -
   PREC_FACTOR,      // * /
   PREC_UNARY,       // ! -
   PREC_CALL,        // . () []
   PREC_PRIMARY
} Precedence;


typedef void (*ParseFn)(bool canAssign);

typedef struct {
   ParseFn prefix;
   ParseFn infix;
   Precedence precedence;
} ParseRule;



static void advance();

static void binary(bool canAssign);

static bool check(TokenType type);

static void consume(TokenType type, const char* message);

static Chunk* currentChunk();

static void declaration();

static void defineVariable(uint8_t global);

static void emitByte(uint8_t byte);

static void emitBytes(uint8_t byte1, uint8_t byte2);

static void emitConstant(Value value);

static void emitReturn();

static void endCompiler();

static void error(const char* message);

static void errorAtCurrent(const char* message);

static void errorAt(Token* token, const char* message);

void expression();

static void expressionStatement();

static ParseRule* getRule(TokenType type);

static void grouping(bool canAssign);

static uint8_t identifierConstant(Token* name);

static void literal(bool canAssign);

static uint8_t makeConstant(Value value);

static bool match(TokenType type);

static void namedVariable(Token name, bool canAssign);

static void number(bool canAssign);

static void parsePrecedence(Precedence precedence);

static uint8_t parseVariable(const char* errorMessage);

static void printStatement();

static void statement();

static void string(bool canAssign);

static void synchronize();

static void unary(bool canAssign);

static void varDeclaration();

static void variable(bool canAssign);

#endif
`
I hope you find this suggestion helpful.

**Comment by jptemplin** [comment]
I read each chapter in 2 passes:

1) I sit in a quiet corner with one or both of my dogs napping next to me, and I read Bob's wonderful prose. I read every code snippet to get a deep understanding of what each does, and Bob's prose helps a lot here. At the end of this pass, I understand the main compiler techniques, data structures and algorithms used in the chapter. I could actually stop here and feel like I've learned a ton.

2) I go to my computer and fire up Visual Studio and the book in side-by-side windows. I now <skim> the chapter again to refresh in my mind what each code snippet does, and because typing is for the birds at this point (Hitchcock [see what I did there? Birds?] said that once he's story boarded a movie, actually shooting it is a dull, boring formality) I copy and paste the code from the book window into Visual Studio as I encounter each snippet. By the time Bob says, "We've implemented enough {X} to try {this code}" I expect no compiler errors because presumably, Bob's code has been debugged and is correct. Compiler errors are a real annoyance at that point because I have to context switch from "learning mode" to "debugging C errors mode". If Bob can help prevent those annoyances with a line or two more of code insertion context, that's a big benefit to the readers of the book. In pass two, I really just want to get the code working to try out examples of what I've just learned, explore edge cases, and perhaps run the code through the debugger to trace through algorithms. Fixing compiler errors (especially when I'm not a veteran C programmer) stops me cold.

Jon T.

**Comment by munificent** [comment]
Thanks for bringing this up!

> You usually surround the insertions with code context before and after.

Right. I try to ensure there is enough location information so that a reader can unambiguously determine where to put the code. There are two ways I do this:

1. By showing some of the preceding and/or following lines. I do this mostly for snippets that get placed inside an existing function or structure.

2. Using the location description on the side, like "After function foo()".

I prefer (2) because it's more terse and doesn't waste space with code you've already seen. It doesn't work for snippets inside existing functions because there's no easy textual description. But when adding an entirely new function, usually all that's required is saying what declaration it follows, so those usually don't show any surrounding lines.

However, there is an ambiguity I didn't realize. In cases where a function is both forward declared and defined in the same file "after function foo()" doesn't make it clear which is intended. I could probably tweak the build script so that it says "after forward declaration foo()" or something, but that feels a little verbose.

Instead, I just fixed these two cases by including the previous lines so that it's clear that it follows the declarations.

> By the time Bob says, "We've implemented enough {X} to try {this code}" I expect no compiler errors because presumably, Bob's code has been debugged and is correct. Compiler errors are a real annoyance at that point because I have to context switch from "learning mode" to "debugging C errors mode".

Yes, that's absolutely my goal. In particular, I don't want you to have to switch into "is the book correct?" mode.
