### ISSUE TITLE
Section 24.5.1 - Change is "in" not "add after"

### ISSUE THREAD

**Issue by jptemplin** [munificent/craftinginterpreters#485]
The attached code change is "in call()" not "add after call()"

![24 5 1](https://user-images.githubusercontent.com/51379861/62777445-8ebcea80-ba7b-11e9-8471-c8a02e19ecf0.png)

**Comment by munificent** [comment]
Good catch. This is a weird little edge case in the build script. Fortunately, the tweaked snippets in the in-progress "Closures" chapter fix this. Once that chapter's done, I'll close this.

**Comment by munificent** [comment]
This is fixed now.
