### ISSUE TITLE
Section 5.2.2 - Overlap between a 'blurb' and an 'aside'

### ISSUE THREAD

**Issue by b-boechat** [munificent/craftinginterpreters#491]
In the code snippet below "Inside Expr, we define each subclass:"

There's an overlap ocurring, at least in Chrome's current Windows version 76.0.3809.132.

**Comment by munificent** [comment]
Yeah, something happened in a recent Chrome update where empty spans lost their location. This is fixed now by bde3d9bd08115d86d5a44a04d5275bcf4ce32fe8.
