### ISSUE TITLE
§14 typos/comments

### ISSUE THREAD

**Issue by beoboo** [munificent/craftinginterpreters#496]
§14.4
[...] we dispatch to a little *utlity* [...] (*utlity* instead of *utility*)

§14.5.2
"And another include over in the “chunk.c” implementation file:"

We don't need to add "value.h" here, since it's already in the chunk.h file included above.

**Comment by munificent** [comment]
> [...] we dispatch to a little utlity [...] (utlity instead of utility)

Fixed that one with #495.

> We don't need to add "value.h" here, since it's already in the chunk.h file included above.

Oops, not sure how I didn't see that. Thanks!
