### ISSUE TITLE
§21.4 uint8_t cast not needed

### ISSUE THREAD

**Issue by beoboo** [munificent/craftinginterpreters#503]
In the namedVariable() func, there's a cast to uint8_t that's not useful now. I see that it will be replaced in a future paragraph, but it's a bit misleading. I'm referring to this:

```
  uint8_t arg = identifierConstant(&name); 

  if (match(TOKEN_EQUAL)) {                
    expression();                          
    emitBytes(OP_SET_GLOBAL, (uint8_t)arg);
  } else {                                 
    emitBytes(OP_GET_GLOBAL, (uint8_t)arg);
  }                                        
```

**Comment by beoboo** [comment]
After further analysis, those lines are going to be overwritten, so there's no need for the cast at all.

**Comment by munificent** [comment]
You're right! I think that variable used to have type `int` but someone pointed out that it didn't need to be, so I fixed that bug forgot to remove the casts.
