### ISSUE TITLE
Closures 25.2.2 debug.c missing #include

### ISSUE THREAD

**Issue by christilden** [munificent/craftinginterpreters#511]
The following appears to be a required include in debug.c in order to use AS_FUNCTION(...), I don't see it in the chapter's code samples.

--- a/c/debug.c
+++ b/c/debug.c
@@ -1,6 +1,7 @@
 #include <stdio.h>

 #include "debug.h"
+#include "object.h"
 #include "value.h"

 static int simpleInstruction(const char* name, int offset) {

**Comment by munificent** [comment]
You're right! I thought my build script would have caught this, but I guess not. Thanks!
