### ISSUE TITLE
25.1.(0) ... a working but empty representation...

### ISSUE THREAD

**Issue by JLPLabs** [munificent/craftinginterpreters#518]
The last sentence before 25.1.1 (so end of 25.1.(0)) says... 

> With that out of the way, we have a working but empty representation for closures.

I'm not sure that is true. Since 

```
case OBJ_CLOSURE:                            
      printFunction(AS_CLOSURE(value)->function);
      break;   
```
refers to a function that isn't implemented (yet? maybe part of another in-flight fix?).
The compile process fails, complaining about printFunction

**Comment by munificent** [comment]
Sorry about this. After I published the "Calls and Functions" chapter, someone suggested a cleaner way to handle debug printing the functions. So `printFunction()` is now defined in that previous chapter, but it probably wasn't there when you first read it.

As much as I possible, I try to avoid making substantive changes in chapters that I've already "shipped", but this was one that I thought was worth doing.
