### ISSUE TITLE
Not understood (Freeing upvalues in closures) Section 25.3.1

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#519]
"When we create an ObjClosure, we allocate an upvalue array of the proper size ..."

ObjUpvalue** upvalues = ALLOCATE(ObjUpvalue*, function->upvalueCount);

"When an ObjClosure is freed, we also free the upvalue array:"
FREE_ARRAY(Value, closure->upvalues, closure->upvalueCount);

Question: If the type of the allocated object is ObjUpvalue*, how come when its time to free the same object, the type is now Value?

What am I missing? Please kindly provide an answer, preferably in the book itself.

**Comment by munificent** [comment]
> What am I missing?

You're not missing anything. It was a bug. :) `ARRAY_FREE()` only uses the type to keep track of how many bytes are freed, which in turn is just used to know when to trigger a GC. So it's easy for me to copy/paste some code and have the wrong type in there without realizing.

**Comment by cm1776** [comment]
"FREE_ARRAY(ObjUpvalue, closure->upvalues, closure->upvalueCount);" does not seem to agree with the following:

"ObjClosure does not own the ObjUpvalue objects itself, but it does own its dynamic array that contains pointers to those upvalues."

Question: Did you mean to write 'FREE_ARRAY(ObjUpvalue*, closure->upvalues, closure->upvalueCount)'? Note the star!

**Comment by munificent** [comment]
Oops, yes!
