### ISSUE TITLE
Premature code (Section 25.1)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#520]
"And when we’re done with a closure, we release its memory:"

`    case OBJ_CLOSURE: {                         
      ObjClosure* closure = (ObjClosure*)object;
      FREE(ObjClosure, object);                 
      break;                                    
    }    `

The purpose of "ObjClosure* closure = (ObjClosure*)object;" remains a mystery until much, much later in Section 25.3.1

"When an ObjClosure is freed, we also free the upvalue array:"

Suggestion: Delete "ObjClosure* closure = (ObjClosure*)object;" from Section 25.1 as it is premature and can cause confusion.

**Comment by munificent** [comment]
Good suggestion, thank you!
