### ISSUE TITLE
Extraneous `expression()` call

### ISSUE THREAD

**Issue by severb** [munificent/craftinginterpreters#527]
https://github.com/munificent/craftinginterpreters/blob/6b67bcd5432e2c89242d2d8ddf6551f42a120586/c/compiler.c#L1020

I believe this call to `expression()` is extraneous—the syncronize logic advances the scanner to the start of the next statement. In case I'm wrong, I think it would be worthwhile to include a small clarification in the following paragraph in `global-variables.md`:

_Then parsePrecedence() silently returns back to the caller. That also isn't right. If the = doesn't get consumed as part of the expression, nothing else is going to consume it. It's an error and we should report it:_

**Comment by munificent** [comment]
You're exactly right, it's not needed. I think I may have initially written that before error synchronization was in.
