### ISSUE TITLE
Change parsing challenge from increment operators to shift

### ISSUE THREAD

**Issue by munificent** [munificent/craftinginterpreters#53]
It's a little weird to parse "--" and "++" when we don't have identifiers yet. The shift operators aren't super interesting, but at least they make sense.

**Comment by aggsol** [comment]
How about `+=`, `-=`, `*=`, `/=`? With the shift operator it is not clear what they are going to do. Shift strings or numbers?

**Comment by munificent** [comment]
The self-assignment operators have the same problem (increment and decrement basically *are* self assignment operators) -- they don't mean anything without syntax for identifiers. :-/

**Comment by munificent** [comment]
After a little further thought, I decided the comma operator would work.
