### ISSUE TITLE
Question: Section 17.4.3

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#530]
"In order to take the “precedence” as a parameter, we define it numerically:"

In the typedef enum for Precedence, the comment for PREC_CALL shows this: "// . () [ ]"

Why do we have [ ] since Lox does not have [ ] operator?

**Comment by munificent** [comment]
Good point! clox began its life as a fork of the Wren VM and apparently there are still a few vestiges in there that don't make sense for Lox.
