### ISSUE TITLE
Two small errors (10.1.2 and 10.5)

### ISSUE THREAD

**Issue by mehaase** [munificent/craftinginterpreters#537]
This is an _extremely_ well written book. Thank you so much!

Two potential errors:

1. In section 10.2.1 "Telling Time", we add a global function called `clock()` that implements `LoxCallable` and overrides 2 of its methods, but the `LoxCallable` interface was defined in 10.1.2 with a single method. It's missing `arity()`.

2. In 10.5 "Return Statements", an object is constructed with `return new Stmt.Return(keyword, value);`, but later in 10.5.1 the constructor is defined as `Return(Object value) { ... }`. The `keyword` argument is omitted and apparently isn't needed in Parser.java's `returnStatement()` either. (Although maybe its significance will be revealed later?)

**Comment by munificent** [comment]
>     1. but the `LoxCallable` interface was defined in 10.1.2 with a single method. It's missing `arity()`.

`arity()` is added to LoxCallable at the tail end of [10.1.4](https://www.craftinginterpreters.com/functions.html#checking-arity).

>     2\. an object is constructed with `return new Stmt.Return(keyword, value);`, but later in 10.5.1 the constructor is defined as `Return(Object value) { ... }`.

Those are two different classes. (I should have maybe used a less-confusing name for the latter...) `Stmt.Return` is the AST class created by the parser to represent a return statement. It is produced by the AST generator at the beginning of 10.5. The `Return` class (not inside `Stmt`) represents a runtime value being returned by the interpreter.

:)

**Comment by mehaase** [comment]
Derp, sorry for posting two non-issues! It's a great text. Thanks, again.
