### ISSUE TITLE
Mismatch between images and prose: Section 25.2 and others

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#539]
In several images (starting at Section 25.2), ObjUpvalue is shown as having a "value" field. ObjUpvalue has no such field. It has a field "location" that is of type "Value*". 

The images referred to are the following:

https://craftinginterpreters.com/image/closures/open-upvalue.png
https://craftinginterpreters.com/image/closures/linked-list.png
https://craftinginterpreters.com/image/closures/closing.png

**Comment by munificent** [comment]
Oh, curses. I changed the name of that field because I felt `value` was confusing. I didn't think about the fact that it means I need to redo a bunch of images. 😭 Thanks for the reminder.
