### ISSUE TITLE
Glossary of tech terms

### ISSUE THREAD

**Issue by JoshuaJHall** [munificent/craftinginterpreters#54]
A glossary of the technical terms used throughout the book would be useful. E.G. I had to go back to find what the acronym AST meant as it was only defined in the foot/sidenotes of the page.

**Comment by munificent** [comment]
I was trying to decide if this was worth doing, but I think you've convinced me it is. It might take a while, but I'll try to get one started.

**Comment by munificent** [comment]
Repeating my comment from @michaelmalonenz's very nice pull request:

> OK, I spent some time thinking about this, and I've come to the conclusion that I'm going to omit a glossary. The book is already quite long as it is, and I don't think unordered reference material is particularly well-suited to a book. For me, the big reason I like learning from books over accumulating knowledge from the web is that a book a single a coherent linear narrative.
>
> If I just want a three-sentence description of a thing, it's just as well to Google it. Maybe it would be nice if you could find said three-sentence summary in my voice and writing style, but there's only so many hours in the day (or pages in the book), and I think mine are best suited for the chapters. Thank you for starting this thought process!
