### ISSUE TITLE
Prototype breakfast example

### ISSUE THREAD

**Issue by timsneath** [munificent/craftinginterpreters#543]
Feel free to close without comment; this is purely feedback. 

I confess that I was confused when I first read the section on prototypes (3.9.3) because I didn't fully understand the breakfast analogy. Specifically, when you say inherit from ("delegates to"), I didn't understand the point you were trying to make in parentheses. Is "delegates to" a synonym for inherit from? I _think_ you're saying that `porkProduct` contains all the state in `classyBrunch`, as well as some extra state -- is that right?

**Comment by munificent** [comment]
>  Is "delegates to" a synonym for inherit from? I _think_ you're saying that `porkProduct` contains all the state in `classyBrunch`, as well as some extra state -- is that right?

That's right. I went ahead and tried to word things more clearly. Let me know if that helps. :)

**Comment by timsneath** [comment]
This is much stronger and tighter and I'm vastly clearer on what you're saying as a result! Thank you :)
