### ISSUE TITLE
Dear Aunt Sally?

### ISSUE THREAD

**Issue by timsneath** [munificent/craftinginterpreters#545]
I had to Google this to understand what on earth you were talking about with the reference to Aunt Sally at the start of chapter 5.

For what it's worth, this is a very US-centric reference. In the UK, we learned BODMAS as the acronym for operator precedence, so the letters don't even give it away. A fun read for all the worldwide variants among English-speaking countries: https://en.wikipedia.org/wiki/Order_of_operations#Mnemonics

**Comment by munificent** [comment]
I had no idea this wasn't universal! Added that link to clarify for the confused.
