### ISSUE TITLE
Advice on native functions

### ISSUE THREAD

**Issue by pollen5** [munificent/craftinginterpreters#546]
I'm following along while also making a different language, a lexer/parser with flex/bison creating an AST and seperate compile step, so far i did great and applied some optimizations, now in function calls, at the end where natives are introduced, well from globals chapter i did the optimization that made globals resolved only at compile time and at runtime it's basically just an index to the array, but this makes it hard to define globals at runtime currently I'm not sure how to modify defineNative to work in my case, should i just forget about the globals optimization? Or do you have a workaround, one idea i had is to define them at compile time but it sounds weird and i might need more runtime-defined variables in the future aswell (e.g when implementing modules) so i appreciate some feedback on this.

**Comment by munificent** [comment]
>  should i just forget about the globals optimization?

That's the way dynamically typed languages like Lox do it. Names are resolved at runtime.

> one idea i had is to define them at compile time

...and that's the way statically-typed languages do it. :)

Basically it's up to you whether you resolve identifiers at compile time or runtime. And, like you note, the choice you make will impact how your module system works. If the language is statically-typed, then you'll want to resolve everything at compile time. If the language is dynamically-typed, you could still bind *top level identifiers* at compile-time, but it's typical to defer that to runtime too.

**Comment by pollen5** [comment]
@munificent thanks, i actually figured it out, just had to check if that native function is in globalNames at runtime and bind the value to that name, this allowed me to still keep the optimization while still being able to bind values at runtime.
