### ISSUE TITLE
Suggestion: Section 25.1.1

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#549]
Excerpt:
"The next step is getting the compiler to emit instructions
to tell the runtime when to create a new ClosureObj to wrap a given FunctionObj."

Suggestion:
1. Replace "ClosureObj" by either "ObjClosure" or "closure object"
2. Replace "FunctionObj" by "ObjFunction" or "function object"

**Comment by munificent** [comment]
Thanks!
