### ISSUE TITLE
Does the interpreter need to be recompiled after small adjustments to script?

### ISSUE THREAD

**Issue by JamaicanFriedChicken** [munificent/craftinginterpreters#550]
Hi Robert, I like your tutorial! it's well thought out and concise. Initially, I had trouble getting the interpreter going until I realized I needed to download your code, build and then compile it. 
Had a bad start, didn't really understand Java's packaging until I looked at the issues on github then realized again my wrong doings.  

One thing I don't understand though, since I am using your lox interpreter and following your guide, don't I have to recompile every time once I have made changes to your code? Can anyone guide me or explain the process? I am very confused. Or do I make a separate script and use it like this " jlox *script* " to actually see if it works.

**Comment by munificent** [comment]
> One thing I don't understand though, since I am using your lox interpreter and following your guide, don't I have to recompile every time once I have made changes to your code?

Yes, any time you change the Java code that implements the interpreter, you'll need to recompile it before you can see the changes working in jlox. If you've cloned this GitHub repo and are using the Makefile that comes with it, then `make jlox` will do that for you.

**Comment by JamaicanFriedChicken** [comment]
May I ask another question @munificent ?  If I were to not use the Makefile and try to compile it manually ie.
- For chapter 4 (Interpreter's Scanner), trying to make a JAR File to test it the snippets of code with REPL, however I always end up with 
```
Error: Could not find or load main class com.craftinginterpreters.lox
Caused by: java.lang.ClassNotFoundException: com.craftinginterpreters.lox
```
when I am trying to run it.

However, I've asked others who have done it and saw that they built the .JAR file in order to test it manually. However, when I run my .JAR file ( just clicking run, it always show the above error). 

My gut is telling me to build it using the Makefile like you said to compile it,  that is, build .JAR file, then go onto running Makefile to build the interpreter. 

IDE being used is:` IntelliJ 2019.4`

Thanks! really love your work.

**Comment by munificent** [comment]
> However, I've asked others who have done it and saw that they built the .JAR file in order to test it manually. However, when I run my .JAR file ( just clicking run, it always show the above error).

You might need to pass in the proper classpath when you run your jar, but I'm not the right person to provide general Java tech support. :)
