### ISSUE TITLE
Suggestion: move null checks into methods

### ISSUE THREAD

**Issue by h2oboi89** [munificent/craftinginterpreters#554]
The following methods in the JLox Interpreter:
- `Interpreter.Evaluate`
- `Interpreter.Execute`
- `Resolver.Resolve`

all have null checks before passing values into them. Consider moving the null check into the method and centralizing a lot of duplicated code.

**Comment by munificent** [comment]
> `Interpreter.evaluate()`

I only see two places where the call to this checks for null and doesn't do other interesting work if the expression is null: `visitReturnExpr()` and `visitVarStmt()`. There's a minor performance benefit to not checking for null in all the other places where we know it won't be null, so I'm hesitant to move the check into the body.

> `Interpreter.execute()`

I only see a single call to that that checks for null first, in `visitIfStmt()`, so I don't think hoisting the null check would be helpful.

> `Resolver.resolve()`

Likewise. `resolve(Expr expr)` only has two calls that are guarded on null checks, and `resolve(Stmt stmt)` only has one.

Thanks for suggesting this! If there were more places that did these null checks, I would agree with you, but it's just on the side where I think it's cleaner to leave them at the callsites.
