### ISSUE TITLE
Minor nitpicks on memcmp/memcpy

### ISSUE THREAD

**Issue by shdown** [munificent/craftinginterpreters#555]
Hello,

in the “bytecode virtual machine” chapter of this great book that I enjoy very much, you use memcmp and memcpy functions a couple of times. However, there is a quirk of the C standard in that is says, if one of the pointer arguments to those functions can not be dereferenced, then the behavior is undefined, even if the ‘size’ argument is zero. That is, it’s undefined behavior to call, for example, `memcmp(NULL, NULL, 0)`.

So, for example, it's undefined behavior to call `copyString(NULL, 0)` or `tableFindString(table, NULL, 0, hash)`. Note that it’s pretty easy to get a pointer that can not be dereferenced: for example, when taking a suffix of length N, where N=0, of some string, or a result of `malloc(0)`, or something like that.

Proof that memcmp/memcpy can not be called with invalid pointers, even if size is zero:

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf

Subclause 7.1.4 Use of library functions, point 1:

> Each of the following statements applies unless explicitly stated otherwise in the detailed descriptions that follow: If an argument to a function has an invalid value (such as a value outside the domain of the function, or a pointer outside the address space of the program, or a null pointer, or a pointer to non-modifiable storage when the corresponding parameter is not const-qualified) or a type (after promotion) not expected by a function with variable number of arguments, the behavior is undefined. If a function argument is described as being an array, the pointer actually passed to the function shall have a value such that all address computations and accesses to objects (that would be valid if the pointer did point to the first element of such an array) are in fact valid.

It’s not OK to call any function defined in `<string.h>` with a pointer that can’t be dereferenced:

Subclause 7.21.1 String handling conventions, point 2:

> Where an argument declared as size_t n specifies the length of the array for a function, n can have the value zero on a call to that function. Unless explicitly stated otherwise in the description of a particular function in this subclause, pointer arguments on such a call shall still have valid values, as described in 7.1.4. On such a call, a function that locates a character finds no occurrence, a function that compares two character sequences returns zero, and a function that copies characters copies zero characters.

**Comment by munificent** [comment]
Yes, you are correct. I'm not sure what errors you are pointing out, though. As far as I can tell, `copyString()` and `tableFindString()` are never called with NULL pointers, and neither are `memcmp()` and `memcpy()`. Can you point to places where the VM gets this wrong? I might be missing something.

**Comment by shdown** [comment]
The problem is in the contract of those functions. If the behavior is undefined if the pointer is not dereferenceable, even with zero size, this needs to be documented, doesn’t it?

**Comment by munificent** [comment]
> this needs to be documented, doesn’t it?

These functions aren't part of any public API. They're just used by the VM itself. Since we also implement every single call to those functions in the book, I think readers can see that NULL never gets passed in.
