### ISSUE TITLE
Not clear: Section 26.2.0

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#561]
Excerpt: "We walk the entry array and mark every key string and value, uh, value."

Question: What does "uh, value" mean?

**Comment by GreenLightning** [comment]
`entry->key` has type `ObjString*`, while `entry->value` has type `Value`.

The text tries to describe both the name of each field ("key", "value") and its type ("string", "value") and runs into the problem that it's the same word for second field ("key string and value value"). The author recognized this fact by inserting the "uh" like he is searching for a better word, but failing to do so, turning the phrase into a joke.

**Comment by munificent** [comment]
What @GreenLightning said. :)

**Comment by cm1776** [comment]
@GreenLightning 
Thanks for your explanation.
