### ISSUE TITLE
Typo and unclear sentence: Section 26.5.1

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#562]
Typo: "Evvery managed language has pays a performance price compared to explicit, user-authored deallocation."

Correction: "Every managed language pays a performance price compared to explicit, user-authored deallocation."

Action: Replace "Evvery" by "Every" and delete "has".

Farther down, we have this UNCLEAR passage:

"In our implementation, that’s the entirety the mark phase falls under this."

**Comment by munificent** [comment]
Those are both fixed now, thanks!
