### ISSUE TITLE
Possible off by one bug in function invoke

### ISSUE THREAD

**Issue by blk2020** [munificent/craftinginterpreters#564]
I think there is a bug in line 300 of vm.c in function invoke.

If it finds a field shadowing a method it overwrites the first parameter to be passed to the method.

    // First look for a field which may shadow a method.
    Value value;
    if (tableGet(&instance->fields, name, &value)) {
        vm.stackTop[-argCount] = value;    <------ should be -argCount - 1
    return callValue(value, argCount);
    }

**Comment by munificent** [comment]
Wow, great catch! I thought I had pretty good test coverage, but this one slipped through. I had tests that covered that code path, but they didn't actually use a function with parameters, so the test didn't show that the wrong stack slot had been clobbered.

Thank you!
