### ISSUE TITLE
Possible NAN Tagging issue

### ISSUE THREAD

**Issue by blk2020** [munificent/craftinginterpreters#565]
I know it hasn't made it into the book as yet, but I have been studying the implementation of the VM.

It took me a little while to understand NAN Tagging, but I think there is a possible issue with the way the `IS_BOOL` macro is testing the value. It is possible for a random pointer to a VM object to match `QNAN | TAG_FALSE`. The result depends on the code using the macro, but it could generate a strange runtime error.

Also, the macro doesn't check for a `true` value.

I think the macro should be like the `IS_NIL` macro and compare the value with `TRUE_VAL` and `FALSE_VAL`

**Comment by munificent** [comment]
The code is correct, but not obviously so. :)

It helps to work through the actual bits. Here are the base constants:

```
QNAN             = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000000
TAG_FALSE        = 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000010
TAG_TRUE         = 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000011
FALSE_VAL        = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000010
TRUE_VAL         = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000011
```

Note that the only difference between `FALSE_VAL` and `TRUE_VAL` is that the lowest bit is set in the latter.

We also have:

```
QNAN | TAG_FALSE = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000010
```

(Which, now that I think about it, can be simplified to just use `FALSE_VAL` instead.)

So if `v` is `TRUE_VAL`:

```
v                    = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000011
QNAN | TAG_FALSE     = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000010
v & QNAN | TAG_FALSE = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000010
```

That is indeed equal to `QNAN | TAG_FALSE`, so `IS_BOOL(TRUE_VAL)` correctly evaluates to true.

Now if `v` is `FALSE_VAL`:

```
v                    = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000010
QNAN | TAG_FALSE     = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000010
v & QNAN | TAG_FALSE = 01111111 11110000 00000000 00000000 00000000 00000000 00000000 00000010
```

And that works out to true as well. So both cases work as desired. The trick is `TRUE_VAL` and `FALSE_VAL` both have their second bit set and only bools have that bit set. Masking `v` with `FALSE_VAL` basically means "check the one bit that means 'bool'".

I'll make sure to explain this in the prose.
