### ISSUE TITLE
Comment: Scanning on Demand

### ISSUE THREAD

**Issue by blk2020** [munificent/craftinginterpreters#566]
I wanted to add `val` as the keyword to indicate that a variable has a constant value.

I found it tricky to change the `identifierType` function to handle both `var` and `val` as these keywords break the pattern, since the difference is in the last character of the keyword.

So I changed `identifierType` to first switch on the length of the identifier, and then switch on the actual characters in the identifier. This allows the code to avoid the `if` statements to check if there is another character in the identifier and the length check in the `checkKeyword` function.

I think the resulting code is a little easier to understand, and it may also perform a little better as it avoids testing identifiers that couldn't possibly be a keyword.

**Comment by munificent** [comment]
> So I changed `identifierType` to first switch on the length of the identifier, and then switch on the actual characters in the identifier.

Yeah, that's not a bad way to do it either.

I think of it like this: we want a very cheap hash function that lets us quickly winnow down an identifier to one of a few possible keywords. The implementation I use treats the first character as the hash. There are a few collisions on `f`, `t`, and (in your case) `v` that it then has to resolve with a few more branches.

Your suggestion is to use the length as a hash *first* and then start looking at characters to disambiguate. The good thing, like you note, is that when looking at individual characters you don't need to check for running past the end of the string.

I think either approach is reasonable. The nice thing about checking the first character is that there are fewer collisions. When using the length as the hash, you end up with only five buckets (ignoring identifiers longer than any keyword of course):

```
if or
and for fun nil val var
else this true
class false print super while
return
```

So you'll end up hitting the second level of disambiguation more often unless the identifier is longer than six characters. It would be fun to profile this and see what's fastest. Doing it well would require a corpus of real-world identifiers too. The statistics around those might lead towards one solution or the other. I could imagine there possibly being a third approach where you make a hash out of `firstChar | (length << 8)` and then switching on that.

For the book, I think the current approach is sufficient. In particular, I like that it gives me an excuse to introduce tries, which are a really cool data structure. :)

Thanks for the suggestion!
