### ISSUE TITLE
typo in II.6.3

### ISSUE THREAD

**Issue by sauer2** [munificent/craftinginterpreters#57]
>**Minimize cascaded errors**. Once a single error is found, the parser no longer really knows what's going on. It tries to get itself back on track and keep going, but if it gets confused, it may report a slew of ghost errors that don't indicate other real problems in the code. When the first error is fixed, they disappear, because they merely represent the parser's own confusion. These are annoying because they can scare the user into thinking their code is in a **_worst_** state than it is.

**Comment by munificent** [comment]
Thanks for noticing this! I took [a fix for this](https://github.com/munificent/craftinginterpreters/pull/49) a while back but somehow managed to re-introduce the typo afterwards. :(

I have it fixed on a branch that I'll try to land soon.
