### ISSUE TITLE
Highlight marking keys in tables

### ISSUE THREAD

**Issue by henke37** [munificent/craftinginterpreters#571]
At the end of Marking the Roots(26.2) there is a chunk of code that marks the elements in a table.

However, it doesn't just mark the values for each element, it also marks the key. This detail is worth pointing out since it is easy to forget to account for the keys.

**Comment by congoman2019** [comment]
In https://github.com/munificent/craftinginterpreters/commit/b99674014ce023280fa70818e97c21c64002278f there is  this fragment: "For each one, we its value." What did you mean by that?
