### ISSUE TITLE
Suggestion: Make GC debug logging messages more informative (Section 26.1.2)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#572]
When executed, the following code: 
         printf("%p allocate %ld for %d\n", (void*)object, size, type);
produces a result like this:
       "00660548 allocate 12 for 2"
What does the above cryptic message mean?

By reading the source code (object.h and object.c), the message can be decoded thus:
"allocated 12 bytes to OBJ_NATIVE object at address 00660548".

I suggest we display the decoded message (or something much clearer). We can do something similar to the following:

printf("allocated %ld bytes to %s object at address %p \n", size, object_type_name[type], (void*)object);

In object.c, define: 
   const char* object_type_name[] = {
  "OBJ_CLOSURE",
  "OBJ_FUNCTION",
  "OBJ_NATIVE",
  "OBJ_STRING",
  "OBJ_UPVALUE",
  };

In object.h, declare:
       extern const char* object_type_name[];

**Comment by cm1776** [comment]
Other culprits:

#ifdef DEBUG_LOG_GC                                        
  printf("%p free type %d\n", (void*)object, object->type);
#endif 

Suggestion: printf("free %s object at %p\n", object_type_name[object->type], (void*)object);

**Comment by pollen5** [comment]
I was thinking of this too, the numbers doesn't help i have to open the file and count the enum members to find out which type is it.

**Comment by munificent** [comment]
Yeah, I agree this makes the debug output nicer and is certainly what I would do if I were just maintaining an interpreter. But for the book, the constraints are a little different. If I add an array to look up type names from enums then every time we introduce a new object type, we also need another snippet to add the new name to the array. There's already quite a lot of not-very-interesting code in the book like that—things like imports and includes, disassembly supports, etc.—so I try to eliminate it whenever possible.

This is one where I think it's simplest to just leave it out.
