### ISSUE TITLE
What is causing this behavior? (Section 26.4 -- sweep())

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#575]
Consider the following lox code:
```
var x = "0123456789ABCDEF ";  // there is a single space between 'F' and '"'
var y = "0123456789ABCDEF "; 
for (var i = 0; i < 32; i = i + 1) y = x + y;
```

When the above is run, the lox prompt returns almost immediately, and Visual Studio 2019 Diagnostic Tools shows that the process memory is 1MB.

Now let us restart our repl and attempt to run the following:

```
var x = "0123456789ABCDEF "; 
for (var i = 0; i < 32; i = i + 1)  x = x + x;

```

In the above case, we notice that:

-      Process memory (MB) rises sharply to 900MB
-      realloc() runs out of memory
-      Program is terminated ( after (assert(allocation != NULL) fails)

Further debugging reveals that at some point in sweep(), the object->type of some object is NEGATIVE (if you don't check for this, your program simply crashes without any warning).

Questions arising:
1. Why do the two "programs" exhibit different behavior? Apparently they do the same thing.
2. Why does object->type become NEGATIVE? No function is EVER passed a negative object->type.

**Comment by cm1776** [comment]
As part of my debugging effort, I modified reallocate() in memory.c as follows:
`
  void* allocation = realloc(previous, newSize);

  if (allocation == NULL) {
    if (parachute != NULL) free(parachute); // parachute: pre-allocated memory 
    logger(LOG_FATAL,
      "\n\n############\nFATAL ERROR:\nUnable to allocate more memory to the VM.\nProgram TERMINATED\n\n",
      111);
  }
`

With the modification in place, I did not expect any object to have invalid memory allocation since the program will be terminated in the case of out-of-memory errors.

**Comment by degustaf** [comment]
@cm1776 In the first version of your code there will be 33 copies of "0123456789ABCDEF " because you are appending the same x each time, which gives linear growth.

In the second version you are doubling the length of x at each step, so there will be 2^32 (about 4.3 billion) copies of "0123456789ABCDEF ". This looks like a valid Out of Memory error to me.

**Comment by cm1776** [comment]
@degustaf  You are absolutely right. I also discovered I could NOT reproduce the "corrupted object" problem when using the original code from github. I must have introduced some errors into the code.

I will close this issue now.
