### ISSUE TITLE
Suggestion: Notify user of out of memory error (Chapter 26)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#577]
Consider this last line from reallocate():
`
return realloc(previous, newSize);
`
The above line does NOT check for the possibility of realloc() returning NULL due to memory exhaustion. The result is a program that simply terminates -- on some systems this happens without any error message.

On the system I am running, the following wall cause the program to terminate:

```
var x = "0123456789ABCDEF ";
for (var i = 0; i < 32; i = i + 1) {
   x = x + x; 
}

```

To alert the user to out-of-memory errors, I suggest the following modification (or something better) be made to reallocate():

```
void* allocation = realloc(previous, newSize);
  if (allocation == NULL)  {
    fprintf(stderr, "\nFATAL ERROR:\n    Out of memory.\n    Program TERMINATED.\n\n");
    exit(111);
  }
```

**Comment by cm1776** [comment]
The worklist of gray objects (Section 26.3.2) has a similar problem:

```
vm.grayStack = realloc(vm.grayStack,                   
                           sizeof(Obj*) * vm.grayCapacity);
```

While attempting to increase the capacity of vm.grayStack, we might run out of memory.

**Comment by michaelmalonenz** [comment]
If you're unable to allocate memory, there's a good chance that you can't do anything meaningful other than exit with an error code - `printf` is a surprisingly gnarly function that allocates memory.
