### ISSUE TITLE
Hide navigation bar in CSS when rendering the page for printing

### ISSUE THREAD

**Issue by serialhex** [munificent/craftinginterpreters#58]
Hey, so I'm really enjoying reading this, but as I have very little access to the interwebz, getting all the libs for the python build system is a pain, and printing it from a browser looks like shit (and removes all the fun side-comments) I was wondering if you could add a PDF version? I don't care if it's not super-pretty, but just having a version I can dl easily and read on my ereader would be nice!

Thanks and keep up the awesome book!! :smiley_cat:

**Comment by munificent** [comment]
I do intend to have a PDF version, but—like my last book—I probably won't do it until after the book is complete and the print edition is done. It probably won't be free either.

Printing it *shouldn't* remove the asides. If it does, there may be something wrong going on.

**Comment by serialhex** [comment]
Ahh, okay.  Printing *doesn't* remove them, it just clips them, because the 8.5 inch "paper" isn't wide enough... Thanks for the response though! I'll figure something out...

**Comment by munificent** [comment]
>  it just clips them, because the 8.5 inch "paper" isn't wide enough... 

Dang. The CSS should be responsive enough to handle that, but I haven't tried it myself. I'll see if I can improve that.

**Comment by serialhex** [comment]
I think it would be solved if you could minimize the left-side bar.  Here's a clip of what it looks like in chrome when I try: 
![book](https://cloud.githubusercontent.com/assets/500833/24810937/1fb65ca0-1b92-11e7-9758-b54b45f667f7.png)

**Comment by munificent** [comment]
Yeah, the right thing for me to do is have a CSS media query for printing that hides the navigation column completely. I'll re-open this issue and retarget it towards that.

**Comment by serialhex** [comment]
Sweet!!! Thanks! :smiley_cat:
