### ISSUE TITLE
PDF Version 

### ISSUE THREAD

**Issue by enderger** [munificent/craftinginterpreters#581]
The book may benefit from a downloadable PDF version to allow offline reading.

**Comment by TomerShech** [comment]
Then why don't you do it yourself and make a PR?
https://html2pdf.com/

**Comment by munificent** [comment]
Hi, I plan to create and sell a PDF version once the book is complete, like I did with my previous book. :)

**Comment by TomerShech** [comment]
Yo Bob I just wanna say thank you for your work, your book, and especially your writing style - are amazing.
