### ISSUE TITLE
Text overlap

### ISSUE THREAD

**Issue by xavierlefevre** [munificent/craftinginterpreters#585]
Hello,

Reporting a micro issue here http://www.craftinginterpreters.com/evaluating-expressions.html:
<img width="332" alt="Screenshot 2020-01-05 at 19 04 37" src="https://user-images.githubusercontent.com/14938214/71783966-53a0f200-2fee-11ea-854e-97fc9c0043ec.png">
Device: Desktop (Macbook) on latest Chrome version

Taking this opportunity to thank you for this book, sooo much. I have been in web development for the past 4 years, did not go through CS at school before, and really wanted for quite some time to understand more core language concepts... you are just giving me what I was looking for. Thanks 🙏

Update: It's not always reproducible on my side, the display gets glitchy, and sometimes places the text well above.

**Comment by munificent** [comment]
I can't repro this. I do recall seeing some weird behavior from Chrome not too long ago and I tweaked a few things to try to fix that. If you're still seeing this sometime, would you mind taking a screenshot of the whole page and I'll reopen the bug? Thanks!
