### ISSUE TITLE
Prompt reader too early to try something

### ISSUE THREAD

**Issue by munificent** [munificent/craftinginterpreters#586]
From a kind reader:

> In section 8.3, after implementing `public Object visitVariableExpr(Expr.Variable expr)` in Interpreter.java, you prompt the reader to test out variable declarations. However, the code won't yet compile, because at this point, we haven't implemented that method in the AstPrinter.

**Comment by goromlagche** [comment]
Yeah I have been through this too 😅 

Actually, with the help of an IDE, we can generate the method and let it return `null`(since AstPrinter is not much of a use in that particular example), silently sweeping things under the rug.🙊

**Comment by foodstuff** [comment]
We never update the AstPrinter again, so I ended up removing it from the build path.

**Comment by munificent** [comment]
Ah, right. Now I remember what's going on here. At the end of chapter 5, I say:

> Also, as we add new syntax tree types, I won’t bother showing the necessary visit methods for them in AstPrinter. If you want to (and you want the Java compiler to not yell at you), go ahead and add them yourself. It will come in handy in the next chapter when we start parsing Lox code into syntax trees.

So this is "working as intended", though a bit frustrating if you overlooked or forgot that part.
