### ISSUE TITLE
Performance problem "binary_trees.lox"

### ISSUE THREAD

**Issue by mingodad** [munificent/craftinginterpreters#587]
I'm not sure what can be wrong but testing "clox test/benchmark/binary_trees.lox" takes for ever.

**Comment by munificent** [comment]
Do you have `DEBUG_STRESS_GC` defined? The binary_trees benchmark exist to stress test object creation and GC tracing. It creates huge trees of thousands of objects. If that flag is enabled, every time it creates a node, it does a full GC. It's *very* slow.
