### ISSUE TITLE
Bibliography?

### ISSUE THREAD

**Issue by alexkowalenko** [munificent/craftinginterpreters#601]
Hello Bob, 

Firstly, I would to say how great your book is, the way it is written, illustrated and even formatted on the web. Looking forward to getting a copy in hardcopy when it is finished. 

I was wondering if you are thinking of doing a bibliography of articles or books, which someone can go on to read for further understanding on topics. It could be at the end of the chapters, or an annotated bibliography at the end of the book.

Again, congrats on a great work, 
Alex

**Comment by munificent** [comment]
That's a good idea, though I can't promise I'll get around to adding it. Leaving this open to remind me too think about it once the chapters are done. :)

**Comment by munificent** [comment]
OK, I thought about it. And if I'm ever going to get this book out the door, I have to decide to *not* do some stuff, and this didn't make the cut.

**Comment by alexkowalenko** [comment]
I understand. Looking forward to the book.
