### ISSUE TITLE
Multi-valued logics?

### ISSUE THREAD

**Issue by virusdaemon** [munificent/craftinginterpreters#606]
This is not an issue but a query. Do you have any plans to include evaluation of any ternary or other n-valued logics?

Why? In 2018 I coded a fairly concise Java class Ternary.java to handle ternary logic objects (this solved a specific problem for the legal and quantified financial risk analyses I was automating for multi-jurisdictional data protection non-compliance). I can lob a copy of this class to you if you're interested.

References: originally I was inspired by my college studies of the philosopher [Susan Haack](https://en.wikipedia.org/wiki/Susan_Haack)'s post-grad research (later recycled into the non-smash-hit book Deviant Logic). However on specifics I went for the mathematician / computer scientist [Stephen Kleene](https://en.wikipedia.org/wiki/Stephen_Cole_Kleene)'s ternary logic, (which also has a "respectability" advantage in that it's partly built into the SQL standard). For a concise summary of the way it works, see [Kleene logic](https://en.wikipedia.org/wiki/Three-valued_logic#Kleene_logic).

(Many thanks for your work-in-progress book, at first sight it looks like it'll be a great assist in dealing with mixed boolean and arithmetic expressions!)

**Comment by munificent** [comment]
No, no plans for that. The book is definitely big enough as it is. :)
