### ISSUE TITLE
Botanically, legumes and cereals are fruit

### ISSUE THREAD

**Issue by ram6ler** [munificent/craftinginterpreters#608]
What a brilliant book this is! ... which makes me feel a bit pedantic bringing up this point.

In chapter 2, _A Map of the Territory_, there is a discussion and a Venn diagram illustrating the overlap between _fruit_, a botanical term, and _vegetable_, a culinary term. In this sense, what defines a thing as a fruit is whether it develops from the ovaries of flowers, in which case there are a few mistakes.

- Something that is clearly a legume (looks like a pea pod), and hence a fruit, is illustrated in V \ F, whereas it should be in V ∩ F.
- The peanut (a legume), which also develops from the ovaries (which are then pressed underground by "pegs"), is botanically a fruit.
- Cereals, which the text says are neither vegetables (in a culinary sense) nor fruit (in a botanical sense), are also technically fruit.
- Nuts (which do not, as you say, contain peanuts) are also either fruit (like the hazelnut) or the seeds of fruit (like the almond and brazil nut).

**Comment by munificent** [comment]
Oh, dear. You're right. And I put so much love into that illustration. 😢 

I'm going to focus on finishing the end of the book first, but I'll probably circle back and redo this after that.

**Comment by ram6ler** [comment]
Of course - please spend your time on the important stuff! :)

In case it helps, I think the image could just be changed (a very little) to the following - that way, your love won't have gone in vain. (I don't think it matters that the peanut and grain are outside the Venn diagram itself - they are tricky things to categorize, which was the point.)

![fruit-veg](https://user-images.githubusercontent.com/7264235/77035139-ccf19380-69e6-11ea-899f-621032fd3b81.png)

**Comment by munificent** [comment]
Thanks for the suggestion! That's an excellent fix. :)
