### ISSUE TITLE
New challenge for Chapter 3

### ISSUE THREAD

**Issue by meadori** [munificent/craftinginterpreters#61]
[Section 1.3](http://craftinginterpreters.com/introduction.html#the-first-interpreter) gives a great description of bootstrapping.  After the description of Lox in [Chapter 3](http://craftinginterpreters.com/the-lox-language.html) I think an interesting challenge would be:

```
Is it possible to bootstrap Lox with one of the given Lox implementations?
Why or why not?
```

I spent some time actually trying this and it was a very interesting exercise in terms of discovering the limits of the language.  As I hit limits I would alter the jlox implementation (via a builtin or language feature) to keep going.  We'll see how far I get :-)

**Comment by munificent** [comment]
That's a fun challenge, but I think it might a wee bit too intense to ask people to do. :)

**Comment by meadori** [comment]
Understood.  Thank you for considering it!
