### ISSUE TITLE
Source code organization suggestion

### ISSUE THREAD

**Issue by haifenghuang** [munificent/craftinginterpreters#611]
When I started to learn from your book, I wrote the code according to the chapter.

When I downloaded the source code from this GitHub repository, I got all the sources. That's good for the whole book. But I think it might be better to supply the code according to the chapter.

Every chapter should have a working code which could run by itself. So I could study what I've learned so far, and at the same time digest what I've learned.

**Comment by munificent** [comment]
> Every chapter should have a working code which could run by itself. So I could study what I've learned so far, and at the same time digest what I've learned.

If you clone the repo and run `make c_chapters java_chapters`, it will create a `gen` directory. That contains a subdirectory for each chapter with the code as it appears by the end of that chapter.
