### ISSUE TITLE
Two GC bugs in compiler

### ISSUE THREAD

**Issue by munificent** [munificent/craftinginterpreters#612]
```c
static uint8_t identifierConstant(Token* name) {
  return makeConstant(OBJ_VAL(copyString(name->start, name->length)));
}
```

And:

```c
static void string(bool canAssign) {
//< Global Variables string
  emitConstant(OBJ_VAL(copyString(parser.previous.start + 1,
                                  parser.previous.length - 2)));
}
```

In both of these, `copyString()` produces a new string which could get collected if growing the constant table causes a GC.

**Comment by Jason2605** [comment]
The constant is pushed onto the stack here: https://github.com/munificent/craftinginterpreters/blob/master/c/chunk.c#L63 and popped after the call to `writeValueArray` meaning the VM has reference to the object - Wouldn't this mean the GC would avoid a cleanup?

**Comment by munificent** [comment]
Ah, right! My past self and you are smarter than my present self, apparently. :)

**Comment by iamkroot** [comment]
@munificent Correct me if I'm wrong, but I think there's one more case where the `copyString()` produces a new string and it might get collected. This would happen in the `emitByte()` function, where the chunk code and lines arrays are grown. At this point, the string won't be on the VM stack, and will get collected.

This exact situation arises in the [example code](https://github.com/munificent/craftinginterpreters/blob/b7dbae3/book/methods-and-initializers.md#L468) of the Methods chapter, where the `scone` string gets collected just before the variable declaration on line 7 finishes.
