### ISSUE TITLE
Possible Off-by-One Error: Section 18.3.1

### ISSUE THREAD

**Issue by congoman2019** [munificent/craftinginterpreters#616]
In Section 18.3.1, as part of the definition of the runtimeError() function, we have the following line of code:

`size_t instruction = vm.ip - vm.chunk->code;`

However, by the time runtimeError() is called, vm.ip no longer points to the instruction that caused the error. You made a note to this point in Section 24.5.2 in the following snippet:

`
// -1 because the IP is sitting on the next instruction to be
// executed.
size_t instruction = frame->ip - function->chunk.code - 1; 
`

If I am correct in my thinking, then you need to update Section 18.3.1 as follows:

`size_t instruction = vm.ip - vm.chunk->code - 1;`

**Comment by congoman2019** [comment]
In Section 24.3.3 we have:

"The last piece of code referring to the old VM fields is runtimeError(). We’ll revisit that later in the chapter, but for now, let’s change it to:" ...

`size_t instruction = frame->ip - frame->function->chunk.code;`

We need to change the above to:

`size_t instruction = frame->ip - frame->function->chunk.code - 1;`

**Comment by munificent** [comment]
You're correct, thanks!
