### ISSUE TITLE
Spelling error in fourth paragraph of representing-code.html

### ISSUE THREAD

**Issue by Monotoba** [munificent/craftinginterpreters#618]
Current text:
Because you understand the order or operations—the old “Please Excuse My Dear Aunt Sally” stuff—you know that the * is evaluated before the + or -. 

Should read:
Because you understand the order << of >> operations—the old “Please Excuse My Dear Aunt Sally” stuff—you know that the * is evaluated before the + or -. 

Note: << >> are edit marks and not literal characters.

**Comment by munificent** [comment]
Nice catch, thanks!
