### ISSUE TITLE
Clarify associativity of double arithmetic

### ISSUE THREAD

**Issue by meadori** [munificent/craftinginterpreters#62]
[Section 6.1](http://craftinginterpreters.com/parsing-expressions.html#ambiguity-and-the-parsing-game) has a side-note that says:

> Ignoring issues around floating-point roundoff and overflow,
> it doesn’t really matter whether you treat multiplication as
> left- or right-associative — you’ll get the same result either
> way. Division definitely does matter.

While this is a true statement, maybe the wording could be stronger to say that such things should **not** be ignored in practice?  Properly programming floating-point arithmetic takes a certain amount of care.  It is easy to come wth "surprising" examples.  Like this one in `jlox`:

```
$ ./jlox 
> print(0.1 + (0.2 + 0.3));
0.6
> print((0.1 + 0.2) + 0.3);
0.6000000000000001
>
```

This side-note also might not be a bad place to refer folks to [What Every Computer Scientist Should Know About Floating-Point Arithmetic](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html).

**Comment by munificent** [comment]
Good idea!
