### ISSUE TITLE
Missing argument: Section 29.3

### ISSUE THREAD

**Issue by congoman2019** [munificent/craftinginterpreters#627]
Look at the following declaration:

```
class Doughnut {
  cook() {
    print "Dunk in the fryer.";
    this.finish();
  }

  finish(ingredient) {
    print "Finish with " + ingredient;
  }
}
```

In the cook() method, the call to finish() does NOT have an argument, but the definition of finish(ingredient) requires one argument.

**Comment by munificent** [comment]
The example program does work because Cruller overrides `finish()` and that's the method that ends up being called. But it is confusing looking code. Fixed it.
