### ISSUE TITLE
Typo: Section 29.3.2

### ISSUE THREAD

**Issue by congoman2019** [munificent/craftinginterpreters#628]
Typo: "Otherwise, if we don’t find a (, then we continue to compile ..."

Correction: "Otherwise, if we don’t find a (, we continue to compile..."

Action: Delete "then"

**Comment by congoman2019** [comment]
In the next paragraph, we have another typo.

Typo:  "Drifting down compilation pipeline, our first stop is a new instruction:"

Correction: "Drifting down the compilation pipeline, our first stop is a new instruction:"

Action: Insert "the" between "down" and "compilation"

**Comment by iahmed5** [comment]
I have submitted the amended code for review after updating the above mentioned typos

#633 

![Fix 628](https://user-images.githubusercontent.com/56458394/77376629-ab870380-6d68-11ea-9720-e44f78c2e742.PNG)
