### ISSUE TITLE
Does the comma operator really need its own syntax tree node?

### ISSUE THREAD

**Issue by mattwildig** [munificent/craftinginterpreters#63]
In the chapter 6 challenge to add comma expressions it says

> ...(You will have to define a new syntax tree node for a comma expression too.)...

and this is how it’s done in the answers too.

Is this really true—isn’t it just another binary operator? In my solution I have used `Expr.Binary` with `,` as the operator and everything (as far as I can tell) works fine.

Looking at the history, this challenge was [recently changed](#2354bea020c41d8b85fa33215630a1fda4f88b45) from implementing increment and decrement operators, which _would_ need a new tree node (or at least changing the existing unary node).

So is the current language a remnant from the original challenge, or is the comma operator so special that it gets it own node whilst all the other binary operators have to share one between them?

**Comment by munificent** [comment]
Great catch! You're exactly right.
