### ISSUE TITLE
Installation of the Interpreter

### ISSUE THREAD

**Issue by codermet** [munificent/craftinginterpreters#630]
Hey everyone,
Please, Can someone help in installing whatever is required. I'm finding it difficult to understand.
What should one do from scratch??

**Comment by wjl** [comment]
Basically, the book assumes you either know how -- or can search up tutorials on the web -- to compile and run both Java and C programs.

I'd suggest just doing a web search for "java tutorial", but here are some links that might help you:

https://javatutorial.net/java-eclipse-tutorial

https://www.jetbrains.com/help/idea/creating-and-running-your-first-java-application.html#

https://netbeans.org/kb/docs/java/quickstart.html

https://www.tutorialspoint.com/java/index.htm

For the book author: you might consider putting some generic suggestions on how to get started in an early sidebar -- even if it does nothing but tell people to go search the web for specific terms and technology, it might help people know where to start.

**Comment by munificent** [comment]
The introduction does say:

> What this book doesn’t contain is the machinery needed to compile and run the code. I assume you can slap together a makefile or a project in your IDE of choice in order to get the code to run.

My impression is that that's sufficient for the majority of the readers. :)
