### ISSUE TITLE
Suggestion: I got lost in section 5

### ISSUE THREAD

**Issue by JEBailey** [munificent/craftinginterpreters#635]
I followed along with the guide. However when I got to 5.4 where it suggested I run the debugger It failed because it wasn't clear that I had to run the tool and provide the path to the lox folder to generate the AST. 

It didn't take much for me to figure out what I needed to do, but it was the first time I encountered a hurdle in your writing style.

**Comment by daneelsan** [comment]
Right, the same happened when I didn't know how to run jlox. I had to check the repository to find 
```
java -cp build/java com.craftinginterpreters.lox.Lox
```
worked. I never programmed in Java so :)

**Comment by munificent** [comment]
Yeah, I was pretty vague here. I don't want to include explicit instructions for *how* to invoke the Java compiler, because those tend to vary widely across platform, time, and IDE. But I did make sure now to at least tell you *when* to run it.
