### ISSUE TITLE
Adding Path and issue in Chapter 4

### ISSUE THREAD

**Issue by codermet** [munificent/craftinginterpreters#637]
In Chapter 4 : Scanning
What is meant by "start jlox from the command line and give it a path to a file, it reads the file and executes it:"
And how can i add path to a file as mentioned above.

**Comment by coderaccords** [comment]
I think it implies to do something like `./jlox <filename/path to a file>`

**Comment by munificent** [comment]
Hi, @codermet, the book does assume you are somewhat familiar with the command line and running programs from within a terminal. If you're not there yet, that's perfectly OK, but you may want to search for something like "how to use command line" and then come back to the book once you've got that figured out. :)
