### ISSUE TITLE
Chapter 7 interpreter.interpret(expression) needs to check if the expression is null

### ISSUE THREAD

**Issue by baileyandmark** [munificent/craftinginterpreters#64]
very simple fix on the last line
(in JLox.java)

private static void run(String source) {
	Scanner scanner = new Scanner(source);
	List<Token> tokens = scanner.scanTokens();
	Parser parser = new Parser(tokens);
        Expr expression = parser.parse();
	if (expression != null) interpreter.interpret(expression);
}

**Comment by munificent** [comment]
Ah, nice catch! The problem was fixed in later chapters, but I needed to move the error checking earlier.

**Comment by Kabirov7** [comment]
But I think that better solution is to check if size of list of the tokens more than 1. If it is 'truthy' so we can go forward and parse and then evaluate expressions.
