### ISSUE TITLE
Chapter 30 - Optimization: Faster Boolean Representation

### ISSUE THREAD

**Issue by ChayimFriedman2** [munificent/craftinginterpreters#644]
> There’s probably a more clever bitwise way to do this, but my hunch is that the compiler can figure one out faster than I can.

I'm not sure, because you can use different and probably more efficient representation which the compiler can't: instead of relying on _numbers_ as type kinds, you can rely on _bits_. That is to say, `nil` is signaled by setting the 10th bit (for instance), boolean is the 11th etc.. Then checking for certain type is simple, intuitive and fast:

```c
#define NIL_BIT 0x0200
#define BOOL_BIT 0x0400

#define NIL_VAL NIL_BIT
#define IS_NIL(v) (v & NIL_BIT) // Or v == NIL_BIT, should benchmark which is faster

#define IS_BOOL(v) (v & BOOL_BIT)
```

To store true and false, you can use any bit you want: 0 is false, 1 is true. This way, to retrieve the C's value of boolean, we just need to mask it against the chosen bit - since in C, 0 is false and any other number is true.

```c
#define BOOL_VAL_BIT 0x0001

#define TRUE_VAL 0x0401
#define FALSE_VAL 0x0400

#define BOOL_VAL(v) (v & BOOL_VAL_BIT)
```

**Comment by munificent** [comment]
That won't do the right thing if the value is a Lox number whose mantissa happens to set that bit. Remember, the mantissa bits are only free for our use if we've already established that the value is a NaN. Otherwise, it could be any old floating point number with some arbitrary set of mantissa bits. :)
