### ISSUE TITLE
Chapter 1: Challenges,  #3, seriously?

### ISSUE THREAD

**Issue by merriam** [munificent/craftinginterpreters#645]
I open up a hoopyfroop book and read the introductory chapter.  It says, "hey, we're going to make a couple languages in Java, and later, we will learn about the structures to do it in C.  No problem; we'll take it slow".   Then I get to the challenges, #1 is a 'look at the repo and notice all the little languages', #2 is 'go get a Java Environment set up, you can figure that out.', and then we get #3:  'oh, also set up a C environment because we might need that if you stay with the book for a dozen chapters, and you should write some link lists in it, with helper functions, and tests.'

Are you sure it's not a typo and should say:  "3.  As a challenge, implement your own version of Linux in C. "

**Comment by jerguslejko** [comment]
@merriam no need to be rude. there are plenty of online tutorial on how to write a _linked list_.

**Comment by merriam** [comment]
Sorry, trying be humorous over rude.  And yes, I fat-fingered linked list.

The issue is that challenges should be somewhat consistent in time or should clearly indicate that they are seriously longer.  The most frustrating challenge is one where one spends a week, grinds through an area without learning terribly much, and then figures out the challenge was to use a few lines of library not yet introduced.

In this case, there isn't really a short-cut.   But also, there is nowhere near a clear path.   Just 'writing a few tests' can drag one down into various methods of writing tests.  I recommend postponing the challenge until the part of the book where a C environment will be needed. 

Perhaps replace the challenge code with more about the mini-languages?  "Look at each of the mini-languages used in the project.   What is common among them?  How do they use words, line breaks, and punctuation? "

**Comment by jerguslejko** [comment]
@merriam yeah, I see where you're coming from. However, programming in C is much more complicated than programming in Java so difference in difficulty is not that big. 

If making a linked list takes a week, I'm not sure if writing a compiler in C is even feasible. Not trying to be demeaning - just real.

**Comment by merriam** [comment]
Ok, which test methodology and framework are use for the tests?  Writing a one-off linked list and checking it take an hour, getting a test framework up is a 'not-related-to-compilers' bear.

**Comment by jerguslejko** [comment]
@merriam right, I think we can leave the conversation :) I'm sure doing it *however* will benefit the reader in improving their C skills.

**Comment by wjl** [comment]
Just to add to this discussion and generalize a bit. I feel like there are at least two audiences for this book with a huge gap between them:

1. Experienced engineers, computer scientists, etc, that are basically already **expert programmers**, and just want to read the book to expand their knowledge about interpreters and compilers -- which might not be their forte, but they probably already know a lot about.

2. Relative programming newbies who may don't know a lot about how computers work, but are smart folks and can at least follow programming tutorials.

The great thing about the book is that it serves both audiences. The **challenges** on the other hand, for group #1 they sound like "oh, that might be a fun little side project" and for group #2 some (not all) of them may be so daunting and far beyond reach that they feel like a poke in the eye and may be discouraging.

I'd suggest a way to make both groups happy is simply to make it clear in the challenges section(s) which challenges are about "learn and explore" and which ones are about "for profession engineers / advanced students".

Maybe just little markers like [EASY] or [ADVANCED] on them?

Anyway, that's my 2 cents as both a profession engineer and an educator. =)

**Comment by munificent** [comment]
> then we get #3: 'oh, also set up a C environment because we might need that if you stay with the book for a dozen chapters, and you should write some link lists in it, with helper functions, and tests.'

On a POSIX machine, you already have a C environment. All you need to do is create a text file named "main.c" and type "gcc main.c" at the command line. On my Mac, with Xcode it's:

1. Choose "New Project...".
2. Select "Command Line Tool".
3. Type a name and select "C" as the language.
4. Choose a location to save it.

That gives me a main.c already containing `main()` that I can immediately run. Visual Studio is similar on Windows. I don't think this is a particularly hard challenge. If it *is*, that's probably a sign that the reader isn't ready for this book yet.

> Maybe just little markers like [EASY] or [ADVANCED] on them?

I considered that, but I'm not an educator and I honestly don't know how well calibrated I am to judge the difficulty of a problem. My hunch too is that the difficulty will vary pretty widely across readers. I'd rather not intimidate a reader by marking a challenge "hard" or give them imposter syndrome if one they happened to struggle with is marked "easy".
