### ISSUE TITLE
Typos: section 30.1

### ISSUE THREAD

**Issue by gfetterman** [munificent/craftinginterpreters#654]
1. Original line: "Our program is a border collie sprinting through the hardware’s **obstactle** course."
Correction: **obstactle** -> **obstacle**

2. Original line: "If we want her to reach the end faster, we can’t just sit and ruminate on canine physiology until **enlightnment** strikes."
Correction: **enlightnment** -> **enlightenment**

3. Original line: "Much of that process is particular to one dog on one **obstactle** course."
Correction:  **obstactle** -> **obstacle**

4. Original line: "Sophisticated ones track each instruction and data cache misses, memory allocations, and all sorts of other metrics."
Correction: not sure, but something doesn't feel right about this sentence. Is there a word missing?
Maybe something like "Sophisticated ones track each instruction and **log** data cache misses, memory allocations, and all sorts of other metrics."?

**Comment by munificent** [comment]
Those are great, thanks! The first few I had already fixed, but 4. is a good observation. That sentence was awkward. It's better now.
