### ISSUE TITLE
isAtEnd missing for Scanner.java

### ISSUE THREAD

**Issue by fzakaria** [munificent/craftinginterpreters#658]
Current commit of `Scanner.java` is https://github.com/munificent/craftinginterpreters/blob/f07ab5815b9d1721d539a31d335bf94fd35fe6cd/java/com/craftinginterpreters/lox/Scanner.java

It references `isAtEnd` method; but it is never declared anywhere.

**Comment by KHN190** [comment]
It's defined [here](https://github.com/munificent/craftinginterpreters/blob/f07ab5815b9d1721d539a31d335bf94fd35fe6cd/java/com/craftinginterpreters/lox/Scanner.java#L218).

**Comment by fzakaria** [comment]
Hmm weird. 
Swear I did a ctrl-f ...
Sorry for the issue.
