### ISSUE TITLE
Typo Section 30.3.1: “IEE 754”

### ISSUE THREAD

**Issue by camelid** [munificent/craftinginterpreters#660]
In an aside: “and, indeed, **IEE** 754”

Typo: IEE

Correction: IEEE

Really enjoying the in-depth look at computer architecture in this chapter!

**Comment by munificent** [comment]
That would be the lesser-known "I double-E". :) Fixed.

**Comment by camelid** [comment]
:)

**Comment by camelid** [comment]
Your book has inspired and enabled me to work on lots of compilers, so thank you!
