### ISSUE TITLE
type punning

### ISSUE THREAD

**Issue by ratchetfreak** [munificent/craftinginterpreters#661]
memcpy is the proper way to pun from one type to another. At least in the newest C++ where strict aliasing is a thing. `char` pointers are explicitly exempted from the UB resulting from the pun and memcpy is explicitly defined to interpret the passed pointers as `char*`.

Then the conversions end up as.

```static inline double valueToNum(Value value) {
  double num;
  memcpy(&num, &value, sizeof(double));
  return num;                            
}   ```

```static inline Value numToValue(double num) {
  Value value;
  memcpy(&value, &num, sizeof(double));
  return value;                            
}   ```

**Comment by munificent** [comment]
Thank you!
