### ISSUE TITLE
2.1.3 "operator precedence" confusing

### ISSUE THREAD

**Issue by dandavison** [munificent/craftinginterpreters#663]
> ### 2.1.3
> ### *Static Analysis*
> ... At this point, we know the syntactic structure of the code—things like operator precedence and expression nesting—but we don’t know much more than that.

Minor issue, but I found this slightly confusing. To my mind, "operator precedence" refers to the tables you get in programming language specs/books that tell you what the semantics are of an expression involving binary operators when it is not fully parenthesized. So, in that meaning, it's a property of the language spec. In contrast, the paragraph in 2.1.3 seems to use it to refer to something that is a property of a particular program.

**Comment by daneelsan** [comment]
What do you mean by 'a property of a particular program'?

**Comment by kandersen** [comment]
I take the sentence to mean that the the structure of the code has been deduced _according to the rules of operator precedence_. I.e. precedence is, as you say, a property of a language, that can then be used to analyse a particular program.

**Comment by munificent** [comment]
Yeah, I agree that phrase is confusing. Fixed.
