### ISSUE TITLE
Typos: sections 30.2.2 & 30.2.3

### ISSUE THREAD

**Issue by gfetterman** [munificent/craftinginterpreters#665]
1. Original line: "There's going to be a lot of `+ 1` **in** and `<=` in this section."
Correction: delete first **in**

2. Original line: "That's much more **inline** with what we'd like to see..."
Correction: **inline** -> **in line**

**Comment by munificent** [comment]
That second one is a very good catch. Are you a copy editor? :)

**Comment by gfetterman** [comment]
Ha, no, I am not a member of that ancient and noble order. Just glad to be helpful.
