### ISSUE TITLE
Fibonacci takes 1.5 hours

### ISSUE THREAD

**Issue by Dmunch04** [munificent/craftinginterpreters#667]
Hi.

I have a little problem. After completing the <http://craftinginterpreters.com/calls-and-functions.html> section, I wanted to try out the fibonacci stress test you showed. Although it ended up taking 1.5 hours to run. I'm pretty certain it's a problem with the functions, since this works just fine:
```
var ppNum = 0;
var pNum = 0;
var cNum = 1;
for (var i = 1; i < 35; i = i + 1) {
    ppNum = pNum;
    pNum = cNum;
    cNum = ppNum + pNum;
}
print cNum;
```
Do you have any idea what may cause this? Let me know if there's any other info needed.

Thanks

**Comment by munificent** [comment]
The Fibonacci stress test is, by design, an incredibly inefficient way of calculating Fibonacci numbers. It's expected that it gets exponentially slow as N increases.
