### ISSUE TITLE
Chaper 1: DESIGN NOTE: WHAT'S IN A NAME?

### ISSUE THREAD

**Issue by klaushauschild1984** [munificent/craftinginterpreters#669]
At https://craftinginterpreters.com/introduction.html#design-note you suggest in the third point to choose a name that is rare enough to be found via Google. "for" is named as a bad example. But Google themself provide with "Go" or "Golang" the perfect counter example.

Sometimes and if your company is big enough you can get away with even "for".

**Comment by munificent** [comment]
Fair enough. But I assume if the reader has the backing of a company as big as Google, they also know which rules they are the exception to. :)
