### ISSUE TITLE
2.1 diagram (mountain)

### ISSUE THREAD

**Issue by augerhandle** [munificent/craftinginterpreters#670]
Shouldn't the top of the mountain have a "node" in the path. After all, you do say something at some point about "having reached the peak".

I know. This is a terribly nitpicky thing. Feel free to ignore.

**Comment by augerhandle** [comment]
I concede that your notes are places where something "exists". Evidently the peak is not. :-)

**Comment by munificent** [comment]
Yes, the latter is what I had in mind. :)
