### ISSUE TITLE
2.1.8 embedding the runtime

### ISSUE THREAD

**Issue by augerhandle** [munificent/craftinginterpreters#671]
You say

"...Go’s runtime directly embedded in it..."

How about a marginal comment that elaborates on this. For example,

_Actually it's not necessary for the runtime code to be physically duplicated into each compiled application. Most modern systems have so-called "shared libraries" which allow a single runtime to be shared by many compiled applications, thereby avoiding the need to duplicate the runtime over and over._

**Comment by munificent** [comment]
That's a fair point, but feels a little *too* tangential, even for me. :)
