### ISSUE TITLE
4 . 2 "Tokens and Lexemes" uses the word "token" before defining it

### ISSUE THREAD

**Issue by belkadan** [munificent/craftinginterpreters#672]
It's not *too* serious, but right now it feels like the reader is supposed to know what a "token" is after you've spent a small paragraph defining "lexeme". This is both in prose and in the use of "TokenType" for the code snippet.

(I don't think you can get around the latter, so maybe leave a comment that says `we'll get to what a "token" is down below` or something?)

**Comment by augerhandle** [comment]
Another possible solution to this is to say something like "We use the word 'token' for a lexeme that we recognize as a legimtate element of a jlox program."

**Comment by augerhandle** [comment]
The diagram might also be another way to clarify the process of scanning text->lexemes->tokens. Something like this?

[https://photos.smugmug.com/Misc/Lox/i-QGfXh4s/0/28fdb9f2/M/IMG_9285_heic-M.jpg](url)

**Comment by munificent** [comment]
Yeah, I don't know why the chapter hesitated so long to clarify the term. Reorganized a bunch to make that read more naturally.
