### ISSUE TITLE
[Feature] Automatic VM generation section

### ISSUE THREAD

**Issue by kenavolic** [munificent/craftinginterpreters#673]
Hi,

Your book is a great work. Thanks a lot.

There have been attempts to develop virtual machine engine with no great success. An example is vmgen. I also developed a very limited toy project with static description in c++ ([mvm](https://github.com/kenavolic/mvm)). 

I started a discussion in [reddit](https://www.reddit.com/r/Compilers/comments/bwnd39/usefulness_of_automatic_generation_of/) about it.

I don't know if the subject deserved a section in your book. But some people might be interested in reading about it. One area of interest could be automatic code obfuscation with the selection of a set of interpreters for simple operations to add a layer of complexity in the code.

Best Regards and thanks for your book!

**Comment by munificent** [comment]
I think this is a little out of scope for the book, but thanks for bringing it to my attention. :)
