### ISSUE TITLE
17.6 [suggestion] Use designated field initializers for the Pratt parser table

### ISSUE THREAD

**Issue by belkadan** [munificent/craftinginterpreters#676]
Since Chapter 18 already uses C's designated initializer feature, it might make sense to use them for the Pratt parser table:

```
ParseRule rules[] = {                                              
  [TOKEN_LEFT_PAREN] = { grouping, NULL,    PREC_NONE },
  [TOKEN_MINUS]      = { unary,    binary,  PREC_TERM },
  [TOKEN_PLUS]       = { NULL,     binary,  PREC_TERM },
  [TOKEN_SLASH]      = { NULL,     binary,  PREC_FACTOR },
  [TOKEN_STAR]       = { NULL,     binary,  PREC_FACTOR },
  [TOKEN_NUMBER]     = { number,   NULL,    PREC_NONE },
};                                                                 
```

While it might be useful to show the whole table for educational purposes, I'd argue that this is still a better form for the actual source (and for the incremental additions in later chapters). Besides moving the comments into the code itself, it also means that you can't get the order wrong.

**Comment by munificent** [comment]
Good idea, thanks!
