### ISSUE TITLE
24.1 printFunction talks about implicit top-level function before it's introduced

### ISSUE THREAD

**Issue by belkadan** [munificent/craftinginterpreters#678]
> While we’re here, there’s a funny little edge case to handle. The implicit function that the compiler creates to contain the top level code for a script doesn’t have a name.

But the "implicit function" being talked about is a design decision made in 24.2, so either this should be presented as defensive code, or perhaps just moved into 24.2's miscellanea.

**Comment by munificent** [comment]
Ah, great catch. Thank you! This book is so much better because of your keen eye. :)
