### ISSUE TITLE
24.5.2 Line numbers don't match code snippet

### ISSUE THREAD

**Issue by belkadan** [munificent/craftinginterpreters#679]
> For example, if you run this broken program:
>
> ```
> fun a() { b(); }
> fun b() { c(); }
> fun c() {
>   c("too", "many");
> }
>
> a();
> ```
> It prints out:
> ```
> Expected 0 arguments but got 2.
> [line 10] in c()
> [line 6] in b()
> [line 2] in a()
> [line 13] in script
> ```

Guessing you had different spacing when you generated the message first. :-)

**Comment by munificent** [comment]
You are right! I originally had `a()` and `b()` formatted like `c()`, but that was a lot of mostly empty lines. Thanks!
