### ISSUE TITLE
24 [suggestion] Challenge: Arity checking for native functions

### ISSUE THREAD

**Issue by belkadan** [munificent/craftinginterpreters#680]
I noticed that native functions don't have any arity checking, and it's certainly not interesting to show it in the source. However, that could be a possible Challenge: "what benefits are there from *not* having arity checking for native functions? do you think this is worth the inconsistency with normal Lox functions? bonus: implement variadic Lox functions as well [somehow]"

Alternately, if you don't want to add a Challenge, I think it's still worth lampshading in a side note. "Native functions probably have an expected arity too, but the code to check it would be exactly the same as before, so I'm leaving it out."

**Comment by munificent** [comment]
A challenge is a great idea, thanks!
