### ISSUE TITLE
NaN self-equality tests fail with openjdk-11

### ISSUE THREAD

**Issue by rlipscombe** [munificent/craftinginterpreters#682]
(at 3dc7cc2)

`default-jdk` on Ubuntu 18.04 installs `openjdk-11-jdk`; when I use it to compile jlox and run the tests, I get the following:

```
roger@rlipscombe:~/Source/munificent/craftinginterpreters [master] $ ./util/test.py jlox
FAIL: test/number/nan_equality.lox
      Expected output "false" on line 7 and got "true".
      Expected output "true" on line 8 and got "false".

238 tests passed. 1 tests failed.
```

**Comment by munificent** [comment]
Oh, dang. Looks like Java [only implements NaN equality correctly on primitives](https://stackoverflow.com/questions/1408569/why-does-double-nan-equal-itself-when-wrapped-in-a-double-instance). I don't want to drag users through that corner of the world until later in the book, so I'll just skip that test on jlox.
