### ISSUE TITLE
30.3.5 IS_BOOL needs to be updated for NaN-embedded objects

### ISSUE THREAD

**Issue by belkadan** [munificent/craftinginterpreters#683]
At the end of the section on objects, `IS_BOOL` looks like 

```
#define IS_BOOL(v)      (((v) & FALSE_VAL) == FALSE_VAL)
```

However, that just tests that we're not in the NUMBER representation and that the second bit is set; if there are any non-aligned objects, they could have the second bit set too. (You do talk about pointer tagging in a side note, but if you *don't* want to rely on that this would be better.)

A safer way to define `IS_BOOL` from the start might be

```
#define IS_BOOL(v)      (((v) | 1) == TRUE_VAL)
```

**Comment by belkadan** [comment]
It looks like this was brought up in #565 as well. I think the original raiser is correct! You demonstrated that `IS_BOOL` returns true for both booleans, but not that it returns false for all objects.

**Comment by munificent** [comment]
Thank you for havingthe patience to get me to understand this. You'd think after a couple of decades I'd be better at my bit twiddling. :)
