### ISSUE TITLE
Please provide a printed example of visitor interface for an Expression

### ISSUE THREAD

**Issue by gkjpettet** [munificent/craftinginterpreters#69]
I've never coded in Java but I've been able to follow along the code in the book and translate it to my language of choice (Xojo). Where I'm struggling (and I think others might too) is visualising the output of your helper tool GenerateAst as I can't figure out how to compile the visitor interfaces for the various Expression subclasses. Trying to visualise this:

```
private static void defineVisitor(
      PrintWriter writer, String baseName, List<String> types) {
    writer.println("  interface Visitor<R> {");

    for (String type : types) {
      String typeName = type.split(":")[0].trim();
      writer.println("    R visit" + typeName + baseName + "(" +
          typeName + " " + baseName.toLowerCase() + ");");
    }

    writer.println("  }");
  }
```

in my head hurts. Would it be possible to either provide a compiled binary of the GenerateAst tool for those of us who have never used Java or at least provide a few more code snippets of completed classes for easier visualisation?

**Comment by munificent** [comment]
Sure. The repo here contains the output of GenerateAst for the final version of the interpreter. Here is [Expr.java](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Expr.java) and [Stmt.java](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Stmt.java). I hope that helps!

I thought about having some of the output in the chapter text itself, but didn't find a natural place to work it in.
