### ISSUE TITLE
Typo: Section 30.2.3

### ISSUE THREAD

**Issue by Owlblocks** [munificent/craftinginterpreters#695]
"Finally, the garbage collector tracks the amount of memory it frees so needs an accurate count of the entry array size:"

"Finally, the garbage collector tracks the amount of memory it frees**,** so **it** needs an accurate count of the entry array size:"

Changes:
1) Comma after "frees"; I don't think it's grammatically necessary, but it sounds more natural when reading the sentence in my head. This change is up for debate, I guess.
2) Added "it" after "so" (grammatically necessary in this case).

**Comment by wjl** [comment]
Although the suggestion correction is probably better writing style, the original one reads just fine and mostly just sounds a little more like informal speech (which may have been an accident, or may have been what the author was going for).

Either way, I'd vote for the comma as well. =)

**Comment by munificent** [comment]
Thanks, yeah the original sentence was technically grammatical, but not exactly a joy to read. :)
