### ISSUE TITLE
Trailing comma in "Metaprogramming the trees" causes a syntax error

### ISSUE THREAD

**Issue by tmcw** [munificent/craftinginterpreters#70]
Loving the book so far, thank you!

I think I found a minor syntax error:

In the code snippet from: http://www.craftinginterpreters.com/representing-code.html#metaprogramming-the-trees

```js
    defineAst(outputDir, "Expr", Arrays.asList(
      "Binary   : Expr left, Token operator, Expr right",
      "Grouping : Expr expression",
      "Literal  : Object value",
      "Unary    : Token operator, Expr right",
    ));
```

The comma after Unary causes (at least my javac 1.8.0_121) to emit

```
Error(24, 9) java: illegal start of expression
```

**Comment by munificent** [comment]
Ah, nice catch.
