### ISSUE TITLE
24.5.2 Printing stack traces example has wrong line numbers

### ISSUE THREAD

**Issue by wjl** [munificent/craftinginterpreters#700]
The code given is this:

```
fun a() { b(); }
fun b() { c(); }
fun c() {
  c("too", "many");
}

a();
```

The expected error given in the text of the book is this:

```
Expected 0 arguments but got 2.
[line 10] in c()
[line 6] in b()
[line 2] in a()
[line 13] in script
```

However, all of the line number are incorrect given the input code! Instead, it appears that the error shown is only correct if the code is this instead (which maybe what it originally was, and it was changed later?):

```
fun a() {
  b();
}

fun b() {
  c();
}

fun c() {
  c("too", "many");
}

a();
```

Bottom line: you should either:

- change either the input code by adding whitespace, or 
- change the line numbers in the error message to line up with the code.

**Comment by wjl** [comment]
Looks like someone already reported this in issue #679.

**Comment by munificent** [comment]
Yes, thanks! Fixed.
