### ISSUE TITLE
Why naming the language 'Lox'?

### ISSUE THREAD

**Issue by MatheusRich** [munificent/craftinginterpreters#703]
I'm pretty in the begging of the book and I didn't saw an explanation for this. I'm not a native english speaker so I may have missed something here.

**Comment by wjl** [comment]
To be fair, the background of this is covered in the introduction's end note with the heading "Design Note: What's in a Name?". Although it doesn't explain exactly why he chose "Lox" it does explain a lot of things that go into choosing a name and ends with the advice "If the names of the world’s other successful languages teach us anything, it’s that the name doesn’t matter much. All you need is a reasonably unique token."

**Comment by MatheusRich** [comment]
Yeah, I read that. I was just curious why Lox in particular. I think it don't matter in the end.

**Comment by WanderingStar** [comment]
I read it as a breakfast joke. There are a lot of references to breakfast, and "lox" is smoked cured salmon that is commonly eaten on bagels for breakfast.

**Comment by munificent** [comment]
There's no strong reason. The original name was "Vox", which is Latin for "voice" and seemed fitting for a programming language and especially one in a book teaching languages. But it's apparently so fitting that someone else had already claimed the name. "Lox" was lexicographically nearby, and I like breakfast food. :)
