### ISSUE TITLE
8.5: missing rational for difference in return of block()

### ISSUE THREAD

**Issue by jnmonette** [munificent/craftinginterpreters#706]
The book makes generally a very good job to explain why everything is as it is in the code. However, in Section 8.5, the code to parse a block is different from the code to parse other statements and the reason is not explained there: instead of building a new instance of Stmt.Block inside the method block(), block returns a List<Stmt> and the Stmt.Block instance is created in the calling code (in the statement() method).

I would assume this is to be able to reuse the method block() in later chapters more easily but at this point one can only wonder, so I would suggest adding a short explanation about that discrepancy in Section 8.5.

**Comment by munificent** [comment]
Good call.
