### ISSUE TITLE
Suggestion: online book would benefit from links to prior chapter and TOC

### ISSUE THREAD

**Issue by tallforasmurf** [munificent/craftinginterpreters#708]
At the end of each chapter of the online book there is a link "Next Chapter: whatever". However it would be useful to have both a "Prior Chapter" link, and a link to the Table of Contents.

Without these links, the only way to go to another chapter, or to the previous chapter, is to go to http://craftinginterpreters.com/ and click "START READING!". (Yes, alright, probably you can find the previous chapter in the dropdown from your browser's back button.) These "back" and "up" links have been standard in online docs forever, and for good reason.

**Comment by munificent** [comment]
There isn't a previous link at the end of the page, but there is one on the navigation bar. :)
