### ISSUE TITLE
minor annoyance: snippets copy/pasted from online book have many trailing spaces

### ISSUE THREAD

**Issue by tallforasmurf** [munificent/craftinginterpreters#709]
Related to #276 but I think not a true duplicate. Copying passages of Java code from Chapter 6 and 7 (at least) gives long strings of trailing spaces on some, but not all, lines. Actual paste with ends of line marked manually:

```
        if (left instanceof Double && right instanceof Double) {
          return (double)left + (double)right;                  <-
        } 

        if (left instanceof String && right instanceof String) {
          return (String)left + (String)right;                  <-
        }                                                       <-
```

**Comment by munificent** [comment]
Yeah, it's annoying. See #276. I'll see if I can find a fix but so far I haven't been able to. CSS is... ugh.
