### ISSUE TITLE
Object types

### ISSUE THREAD

**Issue by egordorichev** [munificent/craftinginterpreters#71]
Can you please explain, what are those object types:

```c
typedef enum {
//> Methods and Initializers not-yet
  OBJ_BOUND_METHOD,
//< Methods and Initializers not-yet
//> Classes and Instances not-yet
  OBJ_CLASS,
//< Classes and Instances not-yet
//> Closures not-yet
  OBJ_CLOSURE,
//< Closures not-yet
//> Calls and Functions not-yet
  OBJ_FUNCTION,
//< Calls and Functions not-yet
//> Classes and Instances not-yet
  OBJ_INSTANCE,
//< Classes and Instances not-yet
//> Calls and Functions not-yet
  OBJ_NATIVE,
//< Calls and Functions not-yet
  OBJ_STRING,
//> Closures not-yet
  OBJ_UPVALUE
//< Closures not-yet
} ObjType;
```

_[Source code](https://github.com/munificent/craftinginterpreters/blob/master/c/object.h)_

`OBJ_STRING` is string,  `OBJ_INSTANCE`, `OBJ_FUNCTION` and `OBJ_CLASS` are understandable, but what are all other for?

**Comment by egordorichev** [comment]
> OBJ_CLOSURE is a closure, a function and the enclosing local variables it accesses.
> OBJ_BOUND_METHOD is a reference to a method, OBJ_NATIVE is the FFI — a C function callable from Lox, OBJ_UPVALUE is a closed-over variable.

Thanks, @munificent

**Comment by munificent** [comment]
And, of course, all of this will be explained in detail in the later chapters that I haven't written yet. :)

**Comment by egordorichev** [comment]
Yeah. Will they all be in java? It looks so, by the book contents.

**Comment by munificent** [comment]
The book walks through two interpreter implementations, one in Java and one in C. This will be in the second one. (The Java interpreter uses a different object representation.)
