### ISSUE TITLE
Minor: Chapter 5, parenthesize function calls accept instead of print

### ISSUE THREAD

**Issue by Rjblaauboer** [munificent/craftinginterpreters#710]
Pretty minor but the parenthesize function in the ASTPrinter class in Chapter 5 calls `expr.accept(this)` instead of calling `print(expr)`. Both achieve the same but the latter reads marginally easier.

(The Reverse Polish Notation printer in the challenges answer does the same)

**Comment by munificent** [comment]
I agree it reads better and is what I tend to do in real code. For the book, I went with `expr.accept()` to make it very explicit that the we are calling back into the same visitor interface. I didn't want readers to have to go back and look at the definition of `print()` to realize where the recursion happens.
