### ISSUE TITLE
Answers for investigation exercises

### ISSUE THREAD

**Issue by joshiraez** [munificent/craftinginterpreters#712]
I was wondering if there was any chance you could add an Appendix for the investigation answers? Because some of them are quite vague and Im not sure what you mean with them (for example, Lisp has an interpreter because it was the first thing it had, not because of any reason in psrticular. Or Im not sure what you mean by nested comments either)

Thanks!

**Comment by munificent** [comment]
My answers to most of the challenges are [here](https://github.com/munificent/craftinginterpreters/tree/master/note/answers) in the repo. I don't intend to include them in the book, mainly for time/size reasons. Hope that helps. :)
