### ISSUE TITLE
Possible Error on "Design Notes: Implicit variable declaration"

### ISSUE THREAD

**Issue by sney2002** [munificent/craftinginterpreters#716]
First of all thanks you for such a great book, I have learn a lot and I haven't even finished the first half.

In the design notes of chapter 8 you say:

> JS, Ruby, and CoffeeScript use the presence of an existing variable with the same name—even in an outer scope—to determine whether or not an assignment creates a new variable or assigns to an existing one. That means adding a new variable in a surrounding scope can change the meaning of existing code. What was once a local variable may silently turn into an assignment to that new outer variable.

I think that is not possible in javascript:

- if you forget to add the var/let keyword the variable is a global variable.
- if you add the var/let keyword, the variable is local and adding a variable with the same name in an outer scope will not change that.

Example:

```
function f() {
    var x = x + 2;
    console.log(x);
}
x = 10;
f(); // NaN
console.log(x) // 10
```

**Comment by munificent** [comment]
>     * if you forget to add the var/let keyword the variable is a global variable.

Not always:

```js
function outer() {
  var a = "outer";
  function inner() {
    a = "inner";
  }
  inner();
  console.log(a);
}
outer();
```


>     * if you add the var/let keyword, the variable is local and adding a variable with the same name in an outer scope will not change that.

Yes, using `var` or `let` means you're *explicitly* declaring the variable, which is what the design note is about. :)
