### ISSUE TITLE
Confusion about the interpreters globals and current environment

### ISSUE THREAD

**Issue by Sammyalhashe** [munificent/craftinginterpreters#718]
Correct me if I'm wrong, but isn't it not correct that you pass globals as the surrounding environment in LoxFunction's `call` (https://www.craftinginterpreters.com/functions.html#function-objects)? If I understand this correctly, globals holds a fixed reference to the outer global environment, and it doesn't appear to change. Maybe I missed something, but when you define a recursive call, like your Fibonacci example, Fibonacci is not defined in the global environment. It only runs if you instead pass the current environment in for me.

**Comment by munificent** [comment]
>  If I understand this correctly, globals holds a fixed reference to the outer global environment, and it doesn't appear to change. 

The reference to the global environment doesn't change, but the contents of the global environment itself will. When a declaration is interpreted at the top level of a program, it will add new bindings to the global environment's `values` map.

> Maybe I missed something, but when you define a recursive call, like your Fibonacci example, Fibonacci is not defined in the global environment.

It *should* be in the global environment, assuming you define the function at the top level and not inside a block or some other function.
