### ISSUE TITLE
`!found and` should be replaced with `!found &&` in the second aside of the Design Note "Considering Goto Harmful"

### ISSUE THREAD

**Issue by bvanrijn** [munificent/craftinginterpreters#719]
First of all, thank you for writing *Crafting Interpreters*!

While reading through the second part of the book, I stumbled upon a small mistake:

In the second aside of the [Design Note "Considering Goto Harmful"](http://craftinginterpreters.com/jumping-back-and-forth.html#design-note), you write:

> You could do this without `break` statements—themselves a limited goto-ish construct—by inserting `!found and` at the beginning of the condition clause of each loop.

However, `!found and` seems like Lox, while the code next to it is likely C (because the book's version of Lox does not support static typing, and because of `printf`).

So, to make the code and the aside agree, `!found and` should be replaced with `!found &&` (or the example code should be converted to Lox, but the former seems like less work).

**Comment by munificent** [comment]
You are correct! Sometimes I forget what language I'm programming in. :)
