### ISSUE TITLE
A Map of the Territory

### ISSUE THREAD

**Issue by colms** [munificent/craftinginterpreters#72]
https://youtu.be/_t8hpEKb4gk

The old rules apply. Rather than edit and pull request, I'll just point out some stuff with bullet points and let you decide which make sense. Much of what I say may be too picky so feel free to ignore any number of the bullet points.

#### possible errors
- "languages designers" => "language designers"
- "Then target backends" reads like a sentence fragment, consider "Target backends then"
- "YARV is A Bytecode Virtual Machine." - unusual casing in this sentence.
- "artifical" - typo.
- "virtual machine (“VM”)" - VM being in quotes just struck me as odd.

#### clarifications
- what's the difference between a VM and interpreter? I'm still not sure after reading.

**Comment by munificent** [comment]
Colm! 😀 🎉 🤘
