### ISSUE TITLE
Section 14.3.1: Replace "chunk->capacity < chunk->count + 1" with "chunk->capacity = chunk->count"

### ISSUE THREAD

**Issue by ElessarDunadan** [munificent/craftinginterpreters#720]
In the definition of "writeChunk", there is a check to see if the capacity of the array needs to be increased. Currently, this is checking if adding one more to the count will exceed the capacity of the array. This can be more simply understood by checking to see if the capacity and count are the same value (thus, whether the array is full).

I suggest for "writeChunk" replacing:
`  if (chunk->capacity < chunk->count + 1) {`
with 
`  if (chunk->capacity == chunk->count) {`

**Comment by munificent** [comment]
I don't think it makes much difference one way or the other, but I slightly prefer the way I have it now. In particular, there are a few other similar comparisons in the VM, and I'd want them to all take the same style. But for the hash table where we have to take the load factor into account, using `==` is a little dubious and I think it's clearer to use `<`.
