### ISSUE TITLE
Section 14.3.1, confusion of "count" and "capacity" in GROW_ARRAY, FREE_ARRAY, & ALLOCATE

### ISSUE THREAD

**Issue by ElessarDunadan** [munificent/craftinginterpreters#721]
When GROW_ARRAY is called from "writeChunk", the old and new capacities are passed in:
`GROW_ARRAY(chunk->code, uint8_t, oldCapacity, chunk->capacity);`

However, in the definition of GROW_ARRAY, it calls these numbers the "count", instead of the "capacity".

I suggest that this:
```
#define GROW_ARRAY(previous, type, oldCount, count) \
    (type*)reallocate(previous, sizeof(type) * (oldCount), \
        sizeof(type) * (count))
```

should be replaced with this:
```
#define GROW_ARRAY(previous, type, oldCapacity, capacity) \
    (type*)reallocate(previous, sizeof(type) * (oldCapacity), \
        sizeof(type) * (capacity))
```

Similarly, in FREE_ARRAY, I suggest that:
```
#define FREE_ARRAY(type, pointer, oldCount) \
    reallocate(pointer, sizeof(type) * (oldCount), 0)
```

should be replaced with this:
```
#define FREE_ARRAY(type, pointer, oldCapacity) \
    reallocate(pointer, sizeof(type) * (oldCapacity), 0)
```

Again, in ALLOCATE (Section 19.3), I suggest that:
```
#define ALLOCATE(type, count) \                       
    (type*)reallocate(NULL, 0, sizeof(type) * (count))
```

should be replaced with this:
```
#define ALLOCATE(type, capacity) \                       
    (type*)reallocate(NULL, 0, sizeof(type) * (capacity))
```

**Comment by munificent** [comment]
I only use "capacity" to refer to dynamic arrays managed by some surrounding data structure. So an array doesn't have a capacity, but a *Chunk* does, and the backing storage for that capacity happens to be an array. From the array's own perspective, all it knows and cares about is how many elements it has. There are other arrays in the VM that are not dynamic arrays and where "capacity" isn't meaningful, like the upvalue array in a closure. For that, the array really just has a count.

Likewise, with `ALLOCATE()`, it used for things that aren't even arrays, so "capacity" isn't a meaningful concept. It's just "how many bytes do you want?" I think "count" is a better general term for that. (I could use "size" but then it's ambiguous as to whether the value is bytes or elements.)
