### ISSUE TITLE
Section 14.3.1: Inconsistent argument order in memory.h macros

### ISSUE THREAD

**Issue by ElessarDunadan** [munificent/craftinginterpreters#722]
When looking at the arguments for the macros in memory.h, it looks like there is an inconsistency:

```
#define ALLOCATE(type, count) // type is first argument

#define FREE(type, pointer) // type is first argument

#define GROW_ARRAY(previous, type, oldCount, count) // type is *second* argument

#define FREE_ARRAY(type, pointer, oldCount) // type is first argument
```

I suggest changing the order of the first two arguments of GROW_ARRAY to be consistent with the other macros, as such:

```
#define GROW_ARRAY(type, previous, oldCount, count) // type is first argument
```

To go one step further, the "previous" could also be changed to "pointer", so as to match the other macros:

```
#define GROW_ARRAY(type, pointer, oldCount, count)
```

**Comment by munificent** [comment]
Yes, that was inconsistent. Thanks for the suggestions! It should be more rational now.
