### ISSUE TITLE
Challenge 6.2 answer

### ISSUE THREAD

**Issue by Stals** [munificent/craftinginterpreters#724]
I was looking through answers and noticed something in 6.2
https://github.com/munificent/craftinginterpreters/blob/master/note/answers/chapter06_parsing.md

So the rule is: `conditional → equality ( "?" expression ":" conditional )? ;`
and the implementation seems to follow it, but shouldn't it be
`conditional → equality ( "?" conditional ":" conditional )? ; `
to allow both branches to have nested conditionals?
Is it related to the left-recursion? And leaving it only in the last branch is fine because of the tail call optimization?

**Comment by munificent** [comment]
The `expression` rule is the lowest precedence rule, so it includes all others, including conditionals. Using:

```
conditional → equality ( "?" conditional ":" conditional )?
```

Would forbid using an assignment in the then branch:

```
var x = cond ? b = c : d;
```

That's a little odd, but C allows it.
