### ISSUE TITLE
Section 18.2: small typo?

### ISSUE THREAD

**Issue by ElessarDunadan** [munificent/craftinginterpreters#725]
In the aside comment, it currently reads:

> There’s no AS_NULL macro because there is only one nil value, so a Value with type VAL_NIL doesn’t carry any extra data.

However, as Lox uses "nil" instead of "null", I believe the intent was to call the non-existent macro AS_NIL, thusly:

> There’s no **AS_NIL** macro because there is only one nil value, so a Value with type VAL_NIL doesn’t carry any extra data.

**Comment by munificent** [comment]
You're right, thanks!
