### ISSUE TITLE
Some explanation needed in 10.1

### ISSUE THREAD

**Issue by tallforasmurf** [munificent/craftinginterpreters#726]
Reading Ch.10.1 I am startled by the syntax, `call  → primary ( "(" arguments? ")" )* ;` because, and this is backed up by the code, any *primary* followed by '(' is treated as a call.

I can see that invoking primary is what permits `(function-yielding-expression)(args)`, but it also permits any of these: `nil()`, `7(of9)`,  `"hello?"(foo)`, `false(true)` etc. etc.

Can we have a few words in 10.1 explaining why this is not a problem?

N.B. I see later on that we do an instance check at runtime ("Can only call functions and classes.")  I see why, also: the callee could legitimately be any expr, so we can't limit it at parse time. Still, a sentence under the grammar discussion "You might have noticed... but we'll sort it out later" would be good.

**Comment by munificent** [comment]
I spent some time trying to figure out where to weave this in, but didn't come up with anything that didn't feel like too much of a distraction. I think most readers are able to figure this out like you did, so I'm just going to leave it as is.
