### ISSUE TITLE
Create a 404 page

### ISSUE THREAD

**Issue by munificent** [munificent/craftinginterpreters#727]
Probably don't want to use my host's default one.

**Comment by 0xdw** [comment]
@munificent I can involve with this,
But on Windows, I can't build the book. :|

![image](https://user-images.githubusercontent.com/12568779/81629642-3c04ca80-9421-11ea-80bd-3a39b1ff58b9.png)

**Comment by 0xdw** [comment]
@munificent I can involve with this,
But on Windows, I can't build the book. :| Any idea?

![image](https://user-images.githubusercontent.com/12568779/81629996-188e4f80-9422-11ea-8e30-f7179eba0199.png)

**Comment by 0xdw** [comment]
@munificent I can involve with this :)

**Comment by munificent** [comment]
Fixed by 25951a17547b0fdb501cdda4416d4195eb302bb7.
