### ISSUE TITLE
Missing (but important) semicolon in book/a-virtual-machine.md

### ISSUE THREAD

**Issue by WhoaWhoa** [munificent/craftinginterpreters#734]
In the book/a-virtual-machine.md section dealing with macro expansion, there is the following section:

> Imagine if you defined:
> 
> ```c
> #define WAKE_UP() makeCoffee(); drinkCoffee();
> ```
> 
> And then used it like:
> 
> ```c
> if (morning) WAKE_UP();
> ```
> 
> The intent is to execute both statements of the macro body only if `morning` is
> true. But it expands to:
> 
> ```c
> if (morning) makeCoffee(); drinkCoffee();
> ```

The last line should actually be

```c
if (morning) makeCoffee(); drinkCoffee();;
```

Note the double semicolon at the end. Alternatively, the macro itself should be

```c
#define WAKE_UP() makeCoffee(); drinkCoffee()
```
(No semicolon at the end)

This is somewhat trivial, but the whole section talks about the unintuitive behavior caused by the semicolon in the middle of the macro, so it's kind of important to show the actual behavior of the C preprocessor.

**Comment by munificent** [comment]
Nice catch! I agree it's important to be precise here.
