### ISSUE TITLE
Missing break on error token in compile fn in 16.2

### ISSUE THREAD

**Issue by Samrose-Ahmed** [munificent/craftinginterpreters#738]
In [section 16.2](https://craftinginterpreters.com/scanning-on-demand.html#a-token-at-a-time) in the `compile` function, should also break on an error token in addition to an EOF, otherwise the repl runs indefinitely after error;

```c
if (token.type == TOKEN_EOF || token.type == TOKEN_ERROR ) break;
```

**Comment by munificent** [comment]
I took your suggestion and then changed my mind. You are right that this makes for more robust code. But we haven't introduced `TOKEN_ERROR` yet, and it feels weird to explain it then. Since this code will get replaced soon anyway, I'm just going to leave it as is.
