### ISSUE TITLE
Conflict between Ch.11 challenge 3 and Ch. 12.5

### ISSUE THREAD

**Issue by tallforasmurf** [munificent/craftinginterpreters#739]
I note there's no "answer" file for Chapter 11 challenge 3 (issue a message if a variable is never referenced in its scope). Perhaps I implemented it wrong, but I think however one does it, it has to be the case that "this" may legitimately pass un-referenced in its scope. As soon as I entered a minimal class to test my code changes for section 12.5, I got that message from my resolver.

It appears the only way around is to special-case the lexeme "this" in the check for unreferenced names. Is this worth a side-note somewhere in section 12.5?

**Comment by munificent** [comment]
Yes, you'd have to special case `this`. From the resolver's perspective, it works like a local variable, but to users (and to me when I wrote the challenge in 11), I don't think of `this` as a local variable.

I don't think it's worth a side note, since this is just a challenge exercise anyway. :)
