### ISSUE TITLE
Scanning

### ISSUE THREAD

**Issue by colms** [munificent/craftinginterpreters#74]
#### possible changes
- why System.exit with 65?
- "parenthsized" typo
- "then do…” That" - should there be a period after the end-quote mark?
- "determine that from" - "that" refers to something in the previous paragraph so I had to do a double take to figure out what "that" was as my mind had removed that mental stack frame.
- the word "token" is used a few paragraphs before being defined. Unfortunately, I totally understand why. There's a chicken and egg situation here. Still, it felt odd.
- "identifier" used but I didn't understand what it meant. The word is also defined in "A Map of the Territory" but I'd forgotten what it might altogether. In fact, I'd forgotten I'd ever read it and only found it through Ctrl+F.
- "It works its" => "The scanner works its"
- "close cousins the reserved words" - maybe add comma after "cousins"

#### questions and comments
- The grayed out code with only the important line in black works really well. Very easy to read.
- This is out there. Is it possible to have an entirely unicode language? Like imagine all keywords and variables name and everything in Chinese. Is that just as easy nowadays as ASCII based? Think of the line character count if everyone used Chinese variable names!

**Comment by munificent** [comment]
> why System.exit with 65?

There are no real strong standards for exit codes. The closest I could find was [sysexit.h](https://www.freebsd.org/cgi/man.cgi?query=sysexits&apropos=0&sektion=0&manpath=FreeBSD+4.3-RELEASE&format=html) which says 65 is for a data error. I guess that's close enough for a syntax error? It felt like minutia to actually explain this in the text.

> "then do…” That" - should there be a period after the end-quote mark?

I *think* you can end a sentence with an ellipsis and then just start the next one.

> the word "token" is used a few paragraphs before being defined. Unfortunately, I totally understand why. There's a chicken and egg situation here. Still, it felt odd.

Yeah. I do define "token" a couple of chapters earlier in "A Map of the Territory", so I gave myself a little slack here.

> "identifier" used but I didn't understand what it meant. The word is also defined in "A Map of the Territory" but I'd forgotten what it might altogether. In fact, I'd forgotten I'd ever read it and only found it through Ctrl+F.

Good point. Explained it very briefly.

Everything else is done: fc73565a86c82d92f238c3649a254c4f940467a6

Thanks!
