### ISSUE TITLE
Alternate terms suggestion for Visitor pattern.

### ISSUE THREAD

**Issue by Retnuhytnuob** [munificent/craftinginterpreters#742]
I got to the section of the book where the Visitor pattern is described, and read 'the Trouble starts with terminology.'

Given that, I looked at what it's doing and, after obtaining an understanding of what it was doing, I looked for whether a different set of terms would help. 

Here's a suggested renaming that might help with the conceptual barrier that's part humorous, and part serious.
Visitor -> FirstResponder
visit -> respondTo
accept -> shoutOutsTo

Example (using that same section of the book):
```
abstract class Expr {                       
  interface FirstResponder<R> {                    
    R respondToBinaryExpr(Binary expr);         
    R respondToGroupingExpr(Grouping expr);     
    R respondToLiteralExpr(Literal expr);       
    R respondToUnaryExpr(Unary expr);           
  }                                         

  // Nested Expr classes here...            

  abstract <R> R shoutOutsTo(FirstResponder<R> firstResponder);
} 

class AstPrinter implements Expr.FirstResponder<String> {                     
  String print(Expr expr) {                                            
    return expr.shoutOutsTo(this);                                          
  }  

  @Override                                                          
  public String respondToBinaryExpr(Expr.Binary expr) {                  
    return parenthesize(expr.operator.lexeme, expr.left, expr.right);
  }

  @Override                                                          
  public String respondToGroupingExpr(Expr.Grouping expr) {              
    return parenthesize("group", expr.expression);                   
  }                                                                  

  @Override                                                          
  public String respondToLiteralExpr(Expr.Literal expr) {                
    if (expr.value == null) return "nil";                            
    return expr.value.toString();                                    
  }                                                                  

  @Override                                                          
  public String respondToUnaryExpr(Expr.Unary expr) {                    
    return parenthesize(expr.operator.lexeme, expr.right);           
  }    

  private String parenthesize(String name, Expr... exprs) {
    StringBuilder builder = new StringBuilder();

    builder.append("(").append(name);                      
    for (Expr expr : exprs) {                              
      builder.append(" ");                                 
      builder.append(expr.shoutOutTo(this));                   
    }                                                      
    builder.append(")");                                   

    return builder.toString();                             
  }  
} 
```

**Comment by jube** [comment]
`Visitor`, `visit`, `accept` are the terms that everyone uses when implementing the... [visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern). Changing the terms would be confusing in fact.

**Comment by Retnuhytnuob** [comment]
In terms of the book, I agree. - If those are the terms understood for the visitor pattern, those are the terms that should be used, at least after the initial explanation. 

On the other hand, if the terms are problematic for teaching the concept, I'd like to discuss whether it would be beneficial to change the terms used when teaching the pattern, (Anywhere, not just this book) even if, after the concept is groked, you then show and use the terms the industry is already familiar with.

I don't believe I've suggested the best possible terms either, (I thought of 'callsForAide' as a better alternate for 'accepts' in my example above after posting) I just want to bring up the idea of potentially changing the terms used while teaching the pattern. My goal in posting here is to hopefully have the idea of using different terms being introduced, and potentially then be relayed to a group that might find it useful for teaching others.

**Comment by munificent** [comment]
Yes, I agree @Retnuhytnuob that the terms used by the visitor pattern aren't great. I've never liked them. But they have been enshrined by the Gang of Four since 1994 and we're basically stuck with them. For me, one of the major benefits of design patterns is having a consistent shared language. So even when the terms aren't great, I think it's important to stick with them. Otherwise, we don't have a *shared* language.
