### ISSUE TITLE
(25.4.2) Are Local.isCaptured and OP_CLOSE_UPVALUE really necessary?

### ISSUE THREAD

**Issue by fengxueem** [munificent/craftinginterpreters#746]
Hi, Bob
When I finished learing chapter 25, I played clox with a couple of homemade tests and found no occurrence of **OP_CLOSE_UPVALUE** in the output bytecodes. Then I dug a little bit, the first thing I did is to comment out everything related to **Local.isCaptured** and **OP_CLOSE_UPVALUE**, and clox worked just fine. This makes me wonder that if **VM.openUpvalues** and **ObjClosure.upvalues** are enough to answer the question mentioned in 25.4.2: “Does any function capture this local variable?" or does a compiler need to maintain infomation of locals being captured by upvalues? Here are my thoughts:

- **Upvalues** are used to convey memory address located outside current function (to be specific located/defined before current function). If this chunk of memory is going to be poped out from the stack, then in the user code there is no following statement that's capable of accessing it, simply because its block scope ends. And this is the moment, like the book says, `"So the logical time to hoist the variable to the heap is as late as possible."`, to make an open upvalue to a closed one. And it happens to be the time of OP_RETURN. 

- **Function** is not treated like a normal **block** in clox, it has its own **chunk**. And after compiling a function, it's packed into a **constant** just like a variable. This also makes endScope() to be unpaired with a beginScope() at compiling stage, like the book says, `Because we end Compiler completely when we reach the end of the function body, there’s no need to close the lingering outermost scope.`. If endScope() is not exsited for the sake of a function, then maybe we should not worry about closing a upvalue inside endScope().

Thus, I think that although **VM.openUpvalues** and **ObjClosure.upvalues** definitely cannot answer the question "Does any function capture this local variable?", it might not be necessary for a compiler to maintain captured locals just for the sake of closing upvalues.

And thx so much for this huge project. BIG BIG BIG thumb up. I really learned a lot from you. It's a missing puzzle of my CS knowledge base.

**Comment by 0x7ffc** [comment]
It's also meant for the 'break' statements. See [wren_compiler.c/L1334](https://github.com/wren-lang/wren/blob/6ab4abe9e3a2767ced01589e9a3d583c840f54c3/src/vm/wren_compiler.c#L1334)

**Comment by fengxueem** [comment]
> It's also meant for the 'break' statements. See [wren_compiler.c/L1334](https://github.com/wren-lang/wren/blob/6ab4abe9e3a2767ced01589e9a3d583c840f54c3/src/vm/wren_compiler.c#L1334)

@0x7ffc Thx for the  reply :)
Currently, this book has not implemented 'break' yet, but it rather encourages us to implement 'break' as a Challenge (Chapter 9, Challenge 3). So, I assume the OP_CLOSE_UPVALUE mentioned in the main part of Chapter 25 is not existed for 'break'.
Sorry about that I don't read the _wren_ implementation you refered thoroughly before wrting this comment. If I miss anything, please point it out. And now, let's say a 'break' was implemented. What is does is to pop out all locals and emit a jump to the loop exit. And I see there's a chance we will pop out open upvalue while doing 'break'. But is it also true for _clox_ ? In _clox_, >An upvalue refers to a local variable in an enclosing function. So, the only chance for a 'break' pop out open upvalue is where a 'break' get called before current function ends. However, this is illegal since given the requirement of  'break' provided in Chapter 9, Challenge 3, >It should be a syntax error to have a break statement appear outside of any enclosing loop. 'break' must live inside a loop. Then, as people may wonder, a loop could live inside a function, and a function could live inside a loop. As we close upvalues when a function returns at runtime, a 'break' will never get in touch with open upvalues.

**Comment by munificent** [comment]
You can get to `OP_CLOSE_UPVALUE` even without break. Any time you have a local variable inside a block that gets captured by a closure and then the block later goes out of scope. Here's an example:

```
var f1;
var f2;

{
  var i = 1;
  fun f() {
    print i;
  }

  f1 = f;
}

{
  var j = 2;
  fun f() {
    print j;
  }

  f2 = f;
}

f1();
f2();
```

For this program to work, `f1` and `f2` need to capture different variables, even though `i` and `j` both live in the same stack slot. The `OP_CLOSE_UPVALUE` instruction emitted at the end of the first block is what moves `i` into the closure for `f1`.

:)

**Comment by fengxueem** [comment]
Thanks a lot for the answer. This is the right scenario where OP_CLOSE_UPVALUE emitted in endScope() comes into play. At compile time, a function's compiler only knows the function needs to work with an upvalue, (which could be open or closed). It's the job of the enclosing compiler to make sure every local variable that's been captured by internal function should be properly closed when their life scope ends. Then, a life scope could end in 2 cases.
Case 1: local variable **j** ends its life with the end of a block.
```
var f1;
{
  var j = 2;
  fun f() {
    print j;
  }
  f1 = f;
}
```
In this case, a compiler needs to emit OP_CLOSE_VALUE within endScope().
Case 2: local variable **a** ends its life with the end of a function **block2**.
```
var globalSet;
var globalGet;
fun block1() {
  fun block2() {
    var a = "initial";
    fun set(new) { a = new; }
    fun get() { print a; }
    globalSet = set;
    globalGet = get;
  }
  block2();
}
block1();
globalGet();
globalSet("global");
globalGet();
```
In case 2, VM should close the open upvalue **a** when function **block2** returns.
