### ISSUE TITLE
Representing Code

### ISSUE THREAD

**Issue by colms** [munificent/craftinginterpreters#75]
#### potential changes
- "there is a long ton of theory" - was "long ton" meant to be "lot". I just want to make sure this is intentional.
- "next heavier" - "next heaviest"? Like "next best" instead "next better".
- "I’m using all those quotes because the terms get a little confusing as you move from lexical to syntactic grammars." - This was the sentence where I felt I had lost grasp of all of the new terms in the interpreter building vocabulary. I don't know how to fix it but I feel it wouldn't be easy. Either more time spent explaining terms or some kind of glossary.
- "are eggs”… probably not" - should there be a space before that ellipsis?
- if I didn't know what regex * meant prior to meaning, I think I'd still feel in the dark after the brief explanation. Maybe after the line `protein → protein ( "and" protein )*`, have example like:
  - protein → protein
  - protein → protein ("and" protein
  - protein → protein "and" protein "and" protein
  - the problem here is that the chapter is already pretty big. Also, you could argue that such a small point does't deserve the extra lines. Maybe another approach would be to point to a somewhere else with a more in depth regex explanation.
- the original rule group (after "for breakfast menus") doesn't vertically align the ->, but the final one does
- I noticed "grep" and all class names aren't in `backticks`. I just wanted to make sure that this is the intentional style as I noticed your `functions()` were in backticks.
- the word "elide" is being used without definition. I just discovered that it's earliest use was in the "Scanning" chapter.
- "Would they have methods related to parsing, where the trees are produced?" - It might just be me but I had to read this sentence twice.
- "The Visitor pattern" - in this first sentence, a capital "V" is used and then not capitalized anywhere else.
- It might be worth bolding or adding "visitor pattern" to the index. I'm just guessing that you're bolding terms that will be in the index.
- "abstract syntax tree (or AST)" - somewhere else, maybe "VM or "GC" if I remember, the "or" isn't there.
- "The pattern isn’t about “visiting” and “accept” doesn’t really conjure up any helpful imagery either." - I was a bit lost when I read "accept" here. I didn't know what it referred to. It's only a few paragraphs later that I saw it was a method name.
- "RPN" acronym used but not explicity defined.

#### questions and comments
- it's kind of a shame that the final rule set (the one after "condenses down to") doesn't feature * of +, as that would've helped clear them up.
To better understand what you were referring to when you were referring to "letters" and "words" in regular expressions, I tried to build a couple of tables (that maybe be completely wrong:

**Scanner Grammar**

category | example
----------------- | -------------------
alphabet | {a, b, ..., Z, _} 
letter | 'f'               
string | {'f', 'o', 'r'} 
word | 'for'         

**Syntactic Grammar**

category | example
----------------- | -------------------
alphabet | { FOR, NUMBER, STRING, ... }
letter | MULTIPLY
word | NUMBER MULTIPLY NUMBER

Are these tables at all close to the reality?

**Comment by munificent** [comment]
> "there is a long ton of theory" - was "long ton" meant to be "lot". I just want to make sure this is intentional.

[Long ton](https://en.wikipedia.org/wiki/Long_ton) :)

> "I’m using all those quotes because the terms get a little confusing as you move from lexical to syntactic grammars." - This was the sentence where I felt I had lost grasp of all of the new terms in the interpreter building vocabulary. I don't know how to fix it but I feel it wouldn't be easy. 

Yeah, it is confusing. I added a table. Maybe that will help?

> "are eggs”… probably not" - should there be a space before that ellipsis?

Not sure. Got rid of it entirely.

> if I didn't know what regex * meant prior to meaning, I think I'd still feel in the dark after the brief explanation. Maybe after the line protein → protein ( "and" protein )*, have example like:
> protein → protein
> protein → protein ("and" protein
> protein → protein "and" protein "and" protein

Added a link to Wikipedia.

> the problem here is that the chapter is already pretty big.

Yeah, that's exactly my concern too. :(

> I noticed "grep" and all class names aren't in backticks. I just wanted to make sure that this is the intentional style as I noticed your functions() were in backticks.

Yes, there's a little [in-progress style guide](https://github.com/munificent/craftinginterpreters/blob/master/note/style%20guide.txt). Code is in backticks, but class names and application names are not.

> the word "elide" is being used without definition. I just discovered that it's earliest use was in the "Scanning" chapter.

It is a perfectly cromulent word.

> "Would they have methods related to parsing, where the trees are produced?" - It might just be me but I had to read this sentence twice.

Reworded.

> It might be worth bolding or adding "visitor pattern" to the index. I'm just guessing that you're bolding terms that will be in the index.

More or less, yes.

> "abstract syntax tree (or AST)" - somewhere else, maybe "VM or "GC" if I remember, the "or" isn't there.

Better memory than me!

> it's kind of a shame that the final rule set (the one after "condenses down to") doesn't feature * of +, as that would've helped clear them up.

Oh, yeah. I meant to. Tweaked it to get `*` in there.

> To better understand what you were referring to when you were referring to "letters" and "words" in regular expressions, I tried to build a couple of tables (that maybe be completely wrong:
> Scanner Grammar
> 
> category	example
> alphabet	{a, b, ..., Z, _}
> letter	'f'
> string	{'f', 'o', 'r'}
> word	'for'
> Syntactic Grammar
> 
> category	example
> alphabet	{ FOR, NUMBER, STRING, ... }
> letter	MULTIPLY
> word	NUMBER MULTIPLY NUMBER
> Are these tables at all close to the reality?

Yes! Added something similar. Anything I didn't quote is fixed too. Thanks!
