### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by jcostasilva** [munificent/craftinginterpreters#752]
I suppose this sentence:

The match() method is defined in terms of two more fundamental operations

should start with:

The check() method...

**Comment by jcostasilva** [comment]
In Chapter 6.

**Comment by fengxueem** [comment]
Hi jcostasilva,
It is actually not a typo. According to the author's writing style, code comes first and then follows the explanation. In Chapter 6, the code of **match** first comes out, and if you take a closer look, there are 2 undefined method inside  **match** : **advance** and **check**. This is what's meant by 

> The match() method is defined in terms of two more fundamental operations

**Comment by jcostasilva** [comment]
Hi fengxueem,
Yes, thank you very much! I should have taken a closer look.
Thanks!
