### ISSUE TITLE
Newlines are missing from Scanning: Implicit Semicolons

### ISSUE THREAD

**Issue by dnmfarrell** [munificent/craftinginterpreters#755]
https://craftinginterpreters.com/scanning.html#design-note

![Screenshot from 2020-06-12 20-18-29](https://user-images.githubusercontent.com/1469333/84555439-fcb0ee80-acea-11ea-8d0b-4b4f22af35f2.png)

I see the same behavior in Firefox and Chrome, neither emit a JS console error or a network error from loading a resource. I can see the newline in the source code:

```html
<pre><code class="language-js">  return
  "value"
</code></pre>
```

It is just not being formatted properly.

**Comment by munificent** [comment]
Ah, I'm glad you spotted this! This is a bug I recently introduced when I rewrote the build system in Dart. Fixed now. Thanks!
