### ISSUE TITLE
Typo in Chapter 5.2.2

### ISSUE THREAD

**Issue by deepforce** [munificent/craftinginterpreters#756]
**Screenshot:** 
![image](https://user-images.githubusercontent.com/10813672/84607999-2a21a780-ae65-11ea-9973-fd21d361a3a7.png)

**Suggestion:** It should be changed to definition.
**Link:** https://github.com/munificent/craftinginterpreters/blob/master/book/representing-code.md#metaprogramming-the-trees

**Comment by munificent** [comment]
I'm always a little surprised when people find obvious typos in early chapters. Thank you for being the one to finally file an issue for it. :)

**Comment by deepforce** [comment]
No problem! I just found it by accident. :)
