### ISSUE TITLE
Build command `pub get` does not work from project root

### ISSUE THREAD

**Issue by timmyjose** [munificent/craftinginterpreters#758]
Details: Running `pub get` from the project root gives the following error:

```~/dev/forks/craftinginterpreters$ pub get
Could not find a file named "pubspec.yaml" in "/Users/z0ltan/dev/forks/craftinginterpreters".
~/dev/forks/craftinginterpreters$
```

Fix: run `pub get` from inside the tools directory. (I looked for an option to pass in the `pubspec` file to the `pub get` command, but there doesn't appear to be one).

I have created a PR with the fix: https://github.com/munificent/craftinginterpreters/pull/757

**Comment by munificent** [comment]
Landed now, thanks!
