### ISSUE TITLE
`jlox` script does not work properly even when in PATH

### ISSUE THREAD

**Issue by timmyjose** [munificent/craftinginterpreters#760]
Description: After adding the project root to `PATH`, `jlox` is available. However, because of the relative paths used for the class files (`build/java`) in the `jlox` script, running `jlox` from anywhere outside the project root gives the following error:

```
~/dev/projects/lox.vim/samples$ jlox hello.lox
Error: Could not find or load main class com.craftinginterpreters.lox.Lox
Caused by: java.lang.ClassNotFoundException: com.craftinginterpreters.lox.Lox
```

Fix: instead of hardcoding the absolute path of the built Java classes, it would be easier to simply set the classpath to a path relative to the `jlox` script (instead of the directory from where `jlox` is invoked).

The proposed fix in in this PR: https://github.com/munificent/craftinginterpreters/pull/759

With this fix, invoking `jlox` from any path should work (save for some corner cases, since getting the original script location reliably and compatibly is a surprisingly hard problem!)

```
~/dev/projects/lox.vim/samples$ jlox hello.lox
Hello, world
```

**Comment by munificent** [comment]
Fixed now that the PR is landed.
