### ISSUE TITLE
Chapter 14: Missing header for "size_t" in "reallocate"

### ISSUE THREAD

**Issue by mradionov** [munificent/craftinginterpreters#761]
I am completely new to C, so my issue might be unjustified.

Although the project compiles successfully, my IDE highlights an error that `size_t` is an unknown type when `reallocate` declaration is being added to `memory.h`.

```c
void* reallocate(void* previous, size_t oldSize, size_t newSize);
```

`size_t` is originally included in `common.h`, but `common.h` is never included to `memory.h`.

For me the error is fixed by adding:

```c
#include "common.h"
```

after `#define ...` in `memory.h`

**Comment by munificent** [comment]
In practice, it doesn't matter much. It's hard to write any C code that doesn't eventually end up including something that eventually dumps `size_t` into your global scope. But it's better to do so deliberately and precisely. :)
