### ISSUE TITLE
Section 26.3.1: Minor typo in a color name: "fuschia" -> "fuchsia"

### ISSUE THREAD

**Issue by mradionov** [munificent/craftinginterpreters#764]
In the note for the section 26.3.1 (Garbage collection) about possible color abstractions in GC algorithms you mention a nice color bouquet "puce-chartreuse-fuschia-malachite". I started googling those and it seems like there is a typo in `fuschia`, which should be `fuchsia`.

**Comment by munificent** [comment]
Yes, thank you! I usually spell that word correctly. The trick is to know that it was named after Leonhart Fuchs.
