### ISSUE TITLE
Ch. 6 Parsing Expressions - "appropriate precedence" in challenge 3

### ISSUE THREAD

**Issue by daneelsan** [munificent/craftinginterpreters#766]
I was trying to resolve this challenge but couldn't really understand what it meant with "appropriate precedence".

Looking at the solution in `notes/answers`:
> The precedence for each operator is one level higher than it is for the **normal correct**. We also don't parse a sequence, just a single RHS. Using the same precedence level handles a sequence for us and helps us only show the error once?

Why is that parsing the rhs as an expression (with the same precedence as the operator) be equivalent to handling sequences?

Thanks!

**Comment by munificent** [comment]
Yeah, a whole lot of words were missing there. Rewrote it. :)
