### ISSUE TITLE
Section 23.1 [question]: Pointless unconditional jumps? 

### ISSUE THREAD

**Issue by katjonathan** [munificent/craftinginterpreters#769]
For `if` statements, why are there an `OP_JUMP` and `OP_POP` involved even when there is no `else` statement in the source code? Couldn't these pointless instructions be removed when compiling a lone `if`?

I'd think the implementation would look something like this instead:
```c
static void ifStatement() 
{
        consume(TOKEN_LEFT_PAREN, "Expect '(' after 'if'.");
        expression();
        consume(TOKEN_RIGHT_PAREN, "Expect ')' after condition."); 

        int thenJump = emitJump(OP_JUMP_IF_FALSE);
        emitByte(OP_POP);
        statement();

        if (match(TOKEN_ELSE))
        {
                int elseJump = emitJump(OP_JUMP);
                patchJump(thenJump);
                emitByte(OP_POP);
                statement();
                patchJump(elseJump);
        }
        else
        {
                patchJump(thenJump);
        }
}
```

If the `else` statement is absent, then it expands to:
```c
int thenJump = emitJump(OP_JUMP_IF_FALSE);
emitByte(OP_POP);
statement();
patchJump(thenJump);
```
But if there indeed _is_ an `else` statement, then it expands to:
```c
int thenJump = emitJump(OP_JUMP_IF_FALSE);
emitByte(OP_POP);
statement();

int elseJump = emitJump(OP_JUMP);
patchJump(thenJump);
emitByte(OP_POP);
statement();
patchJump(elseJump);
```

**Comment by fengxueem** [comment]
Hi katjonathan,
This is a good question to point out. And it indeed looks very confusing at first that a `OP_JUMP` and `OP_POP` get involved. Here is a simple test lox program to illustrate this, hope it will make some sense.
`var a = 'False';
if (false) {
  a = "True";
}
print a;`

**Comment by munificent** [comment]
@fengxueem is exactly right. There's never an entirely empty else because you at least need to pop the condition.

We *could* change `OP_JUMP_IF_FALSE` so that *it* pops then condition. In that case, then, yes, we could elide the `OP_JUMP` over the empty else entirely. But then we would need a different instruction to use for `and` and `or`, since those expressions need to leave the result on the stack.

**Comment by katjonathan** [comment]
@munificent: Why did we reuse `OP_JUMP_IF_FALSE` for short-circuiting expressions instead of letting them have their own opcodes as you've suggested above? (Looking at [SpiderMonkey's bytecode specification](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Internals/Bytecode), this is exactly what they do.) Wouldn't having separate instructions make it easier for us implementers to debug? In the same fashion, we could have added a `OP_JUMP_IF_TRUE` used for `or` statements instead of the convoluted set of jumps we did.
