### ISSUE TITLE
Chapter 22.1: Superfluous identifier?

### ISSUE THREAD

**Issue by foodstuff** [munificent/craftinginterpreters#772]
Just something that caught my eye - the typedef for the `Compiler` struct has two mentions of the identifier "Compiler":

```c
typedef struct Compiler {
  Local locals[UINT8_COUNT];
  int localCount;
  int scopeDepth;
} Compiler;
```

My knowledge of C is pretty shaky (mostly based on my shaky knowledge of C++) but I'm reasonably sure that the first instance of "Compiler" doesn't need to be there? If it didn't have the same name I might've dismissed it as something that will pay off later (and this is to note that I haven't read ahead).

It's incongruous with how struct types are declared elsewhere in the book:
![image](https://user-images.githubusercontent.com/12169005/86024137-f43d0f80-ba6f-11ea-8ced-53b4398a2555.png)

If it's necessary maybe a note is needed for people who are less confident with C, otherwise I recommend it be changed to be more inline with the rest of the book.

**Comment by munificent** [comment]
It's not necessary in the chapter where that struct is first introduced, but it becomes necessary later when it gets a field of its own type.
