### ISSUE TITLE
Chapter 10: Variable declartions overwrites functions declartions.

### ISSUE THREAD

**Issue by MarkusWessjohann** [munificent/craftinginterpreters#774]
Howto define und interpret Function is really great. I love the soulution, but I would check if there is an function and variable with the same name or to functions, in one enviroment, with the same name.

At least that I would check.

**Comment by munificent** [comment]
Declarations can only overwrite each other at the top level. Inside a block, this is a compile error:

```
{
  fun a() {}
  var a = 0;
}
```

It is a little loose to allow top-level declarations to overwrite each other, but it's basically to make the REPL more user-friendly.
