### ISSUE TITLE
Build warning (error) at end of "Compiling Expressions"

### ISSUE THREAD

**Issue by mattbruv** [munificent/craftinginterpreters#776]
I am getting this error at the end of the "Compiling Expressions" chapter in clox:

```
src/compiler.c: In function 'makeConstant':
src/compiler.c:110:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (constant > UINT8_MAX) {
                ^
cc1.exe: all warnings being treated as errors
make: *** [Makefile:16: build/compiler.o] Error 1
```

With the following compiler/flags:
`gcc.exe (MinGW.org GCC-6.3.0-1) 6.3.0`
```
CC := gcc
CFLAGS := -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter
```

 stdint.h defines it as this: `#define UINT8_MAX        0xffui8` or `(unsigned char)255U`

I guess the compiler doesn't like comparing a signed 32bit integer with an unsigned 8 bit. When I replace `UINT8_MAX` with the literal `255` it builds and runs fine.
Edit: Also, changing it to `(int)UINT8_MAX` works too.

A snapshot of this source code with my makefile that produces this error can be found [here](https://github.com/mattbruv/clox/tree/003d34a10e28aebe4f4e07ebe75640da5f51a60d).

**Comment by munificent** [comment]
The C spec is a little opaque here:

> Each instance of any defined macro shall be replaced by a constant expression suitable for use in `#if` preprocessing directives, and this expression shall have the same type as would an expression that is an object of the corresponding type converted according to the integer promotions. Its implementation-defined value shall be equal to or greater inmagnitude (absolute value) than the corresponding value given below, with the same sign, except where stated to be exactly the given value.

But I believe that's a bug in your version of GCC. The `UINT8_MAX` macro should not have an explicit sign or size. If you look at other stdint.h headers, they all define it as simply `255`. Your version of GCC is about four years old, so it may be worth upgrading.
