### ISSUE TITLE
Argument limit is different in jlox and clox

### ISSUE THREAD

**Issue by johnf9896** [munificent/craftinginterpreters#778]
This is a really good book. Thank you!

I noticed the limit in jlox is 254 while limit in clox is 255.

In [10.1.1](https://craftinginterpreters.com/functions.html#maximum-argument-counts):
```
if (arguments.size() >= 255) {
    error(peek(), "Cannot have more than 255 arguments.");
}
```
And in [10.3](https://craftinginterpreters.com/functions.html#function-declarations)
```
if (parameters.size() >= 255) {
    error(peek(), "Cannot have more than 255 parameters.");
}
```

In [24.4](https://craftinginterpreters.com/calls-and-functions.html#function-declarations):
```
if (current->function->arity > 255) {
    errorAtCurrent("Cannot have more than 255 parameters.");
}
```

So it seems the problems is in jlox that it's using `>=` instead of `>`

**Comment by fengxueem** [comment]
Hi johnf9896,
Actually, this 255-limit error is handled correctly in both jlox and clox. In jlox, parameters.size() is added by 1 **after** the if check. In clox, function->arity is added by 1 **before** the if check. This is a teeny-tiny coding difference. Maybe you could changed the limit to 1 and play it with a simple Lox program with a Lox function. In this way, things might be much clearer.

**Comment by munificent** [comment]
What @fengxueem said. :) In jlox, the limit is checked before parsing and in clox it happens after.
