### ISSUE TITLE
Minor grammatical improvement

### ISSUE THREAD

**Issue by halberman** [munificent/craftinginterpreters#779]
In section 23.3 on While Statements, I think the sentence that includes "...easier to sidestep the annoying bit juggling required to manually..." would be improved by either a) dropping "bit" or b) making it "bit of juggling".

Great book! Can't wait for the printed version.
Best,
  Hal

**Comment by munificent** [comment]
That was deliberate, but maybe not the clearest verb.

**Comment by halberman** [comment]
I thought about this further after my submission; what you really meant to say was "bit-juggling"; you need the hyphen to make this an adjective.
Best,
Hal
