### ISSUE TITLE
27.4 and 28.3 Errors in parse table code

### ISSUE THREAD

**Issue by halberman** [munificent/craftinginterpreters#781]
In section 27.4, the first code block to update compiler.c says to update to the following:
`    [TOKEN_DOT]           = { NULL,     dot,    PREC_CALL },`
But the existing code uses a different technique for the parse table; the line it is updating looks like:
`{ NULL,     NULL,    PREC_NONE },       // TOKEN_DOT`
So the update should be to:
`{ NULL,     dot,     PREC_CALL },       // TOKEN_DOT`

The same type problem appears in section 28.3 where it says to update `TOKEN_THIS` to:
`[TOKEN_THIS]          = { this_,    NULL,   PREC_NONE },`

Not too hard to translate, but thought you should know.
Best,
Hal

**Comment by munificent** [comment]
Ah, yes, I'm sorry about that. I recently changed how the parse table is built (5c31fe0df66e6927a9c0d3f6253594e57d29301b). I've updated the previous chapters to be consistent with the new form, but if you're in the middle of following along with the book, I've left you in an inconsistent state. Sorry. :(
