### ISSUE TITLE
Incorrect Python example in Chapter 25, Design Note

### ISSUE THREAD

**Issue by TheGreatCookieMachine** [munificent/craftinginterpreters#782]
In the design note for chapter 25, the following Python example is given:
```python
closures = []
for i in range(1, 3):
  closures.append(lambda: print(i))

closures[0]()
closures[1]()
```
It is then stated that `3` will be printed twice. This, however, is incorrect. Here is the code executed in IDLE:
```python
>>> closures = []
>>> for i in range(1, 3):
  closures.append(lambda: print(i))

  
>>> closures[0]()
2
>>> closures[1]()
2
```
It actually prints `2` twice. This is because, in Python, `range(a, b)` is the interval [a, b), not [a, b] (Since the result is always an integer, it could be said the interval is [a, b-1]). This can be seen as in the following example:
```python
>>> list(range(1, 3))
[1, 2]
```
Mixing this fact and the fact `range` is a generator and generators don't attempt to count past their last value, the last version of `i` set by the loop has a value of `2`.

One way to fix this is to increment `b` up by one (`range(1, 4)`), however that could be somewhat confusing for those who don't know how Python's range works. An alternative is to use a list, like so:
```python
for i in [1, 2, 3]:
    closures.append(lambda: print(i))
```
This shouldn't require too much explanation, while still giving the correct result.

**Comment by munificent** [comment]
Thank you! The Python example worked the way I wanted it to work, which is iterating `i` through 1 and 2 (inclusive). But the prose afterwards didn't explain it correctly. I fixed the prose to match the code. :)
