### ISSUE TITLE
Unrecognized characters not added to next token

### ISSUE THREAD

**Issue by JeffJetton** [munificent/craftinginterpreters#785]
In **_Lexical errors_ - 4.5.1**:

> What happens if a user throws a source file containing some characters Lox doesn’t use, like @#^ at our interpreter? Right now, those characters get silently added to the next token.

I might have done the coding in the wrong order or something, but at that point in my progress of building the Scanner class, those unrecognized characters were simply getting skipped.

`scanToken()` would just return back to `scanTokens()` after consuming a character and either adding a token for it or not (still only tokenizing single characters at that point). Which means `start` would always get reset to `current`, and those unrecognized characters would _not_ be added to anything.

(Oh, and I think there might need to be a comma after "like @#^")

**Comment by daneelsan** [comment]
Yeah, I think at that point any character not in the switch will get skipped.

**Comment by munificent** [comment]
You're right, thank you for noticing this!
