### ISSUE TITLE
25.4.4 opening wording?

### ISSUE THREAD

**Issue by mspraggs** [munificent/craftinginterpreters#787]
Hi Bob. Really enjoying reading Part 2, trying to follow-along with Rust.

Not sure if it's just me, but the sentence before the first code block in 25.4.4 (Closures) reads a little strange to me:
![image](https://user-images.githubusercontent.com/3777474/88488327-6ed05080-cf84-11ea-87af-9f085bb897eb.png)

Not sure if this should be "Now it's the interpreter's responsibility:" or if I'm misreading it.

Thanks again for all the work you've put into this!

**Comment by munificent** [comment]
Good catch, thanks!
