### ISSUE TITLE
Evaluating Expressions

### ISSUE THREAD

**Issue by colms** [munificent/craftinginterpreters#79]
#### possible changes
- "a few things with one" - I'd change "one" to "a value in Lox" (or something like that) but I'm a wordy guy so I'm not sure how others would feel about this.
- file descriptions say `lox/filename.java`. Should they say `jlox/filename.java`?

That's it. I might be losing my touch but I couldn't find anything else, and that's without changing my standards. That chapter is pretty tight.

**Comment by munificent** [comment]
> file descriptions say lox/filename.java. Should they say jlox/filename.java?

It felt a little redundant to me to make the Java package name "jlox" since it's, well, already inside a Java file.

> I might be losing my touch but I couldn't find anything else

Maybe I'm absorbing your powers and getting better!

> That chapter is pretty tight.

Thanks! 😁
