### ISSUE TITLE
repeated method name in jlox

### ISSUE THREAD

**Issue by garychl** [munificent/craftinginterpreters#793]
Hi Bob! Thanks for the wonderful book, I have learned a lot from you :)

I just wonder that you defined the method `static void error` twice in the `Lox` class in `Lox.java`. Is this a mistake or you do it deliberately? 

```
    static void error(int line, String message) {
        report(line, "", message);
    }

```
```
    static void error(Token token, String message) {
        if (token.type == TokenType.EOF) {
            report(token.line, " at end", message);
        } else {
            report(token.line, " at '" + token.lexeme + "'", message);
        }
    }
```

Thanks!

**Comment by kerlyson** [comment]
Hello. They have different signatures so it's probably on purpose.... If I'm not mistaken the first method is used on the character loop on the Parser to report invalid characters.

**Comment by garychl** [comment]
Got it, since I am new to Java and there is no method overloading in python so I am not aware of it. Thanks!
