### ISSUE TITLE
Suggestion: add interpreter setup instructions

### ISSUE THREAD

**Issue by louispotok** [munificent/craftinginterpreters#8]
Hi, loving the book so far. Quick suggestion. In the intro to section 3 you suggest that readers can use your interpreter while they read through the book:
> A tutorial isn’t very fun if you can’t try the code out yourself. Alas, you don’t have a Lox interpreter yet, since you haven’t built one!
> 
> Fear not. You can use mine. [ link to this repo ]

I think it would be helpful to add setup instructions to the README here, I definitely don't know where to get started.

**Comment by munificent** [comment]
Oh, yeah! I kind of threw the README together here, but I definitely will fill it in some. (The sneak preview is "run `make`" and it will build both the Java and C interpreters.)

**Comment by munificent** [comment]
I forgot to note it in the commit, but it is fixed by: f93ffe34cf117efa808a1173eb28321a87bfbfd4
