### ISSUE TITLE
I'd rather email you...

### ISSUE THREAD

**Issue by serialhex** [munificent/craftinginterpreters#80]
But there isn't a way to do so, so I'm making this an issue.

Anyway, in your latest chapter, you say:

> You could make a language that treats variable declarations as expressions that both create a binding and produce a value, but I’m not aware of any widely-used languages that do. Scheme seems like a contender, but note that after a let expression is evaluated, the variable it bound is forgotten. The define syntax is not an expression.

And since I use Common Lisp every day, I can tell you that you *can* do this in CL.  If you use one of the special forms `defvar` or `defparameter` it evaluates the value, and returns the name of the variable, which you can then do more stuff with. Like so:

``` common-lisp
? (defvar foo 5)
FOO
? (setf bar (defvar foo 5))
FOO
? bar
FOO
```

OTOH you can use `setf` and it will not only bind, but return the last value you bound like so:

``` common-lisp
? (+ (setf baz 5) 6)
11
? baz
5
```

You can even get fancy and do multiple bindings in a `setf`:

``` common-lisp
? (setf foo 0 bar 0 baz 0)
0
? foo
0
? bar
0
? baz
0
? (+ (setf foo 5 bar 3 baz 2) foo bar)
10
? foo
5
? bar
3
? baz
2
```

Now, this *is* non-standard use of `setf`, but it *is* possible.

(Once you read this go ahead and close it.  I looked everywhere I could think to find an email address, but alas, I found none... :crying_cat_face: )

**Comment by munificent** [comment]
> I can tell you that you can do this in CL. If you use one of the special forms defvar or defparameter it evaluates the value, and returns the name of the variable, which you can then do more stuff with.

Oh, interesting! I don't have much experience with CL. My understanding is those are both for dynamically scoped variables. I think there's maybe an argument that those are different from what most people would think of as a "variable declaration" since they aren't lexically scoped. They work more like mutating an existing object.

That is good to learn though. Thank you!

>  I looked everywhere I could think to find an email address, but alas, I found none...

It's hiding. Last paragraph of the [main page](http://www.craftinginterpreters.com/):

> If you want to get in touch with me, you can email bob at this site

Filing a bug is probably better though, given how far behind I am on email these days... 😭

**Comment by auduchinok** [comment]
> You could make a language that treats variable declarations as expressions that both create a binding and produce a value, but I’m not aware of any widely-used languages that do. Scheme seems like a contender, but note that after a let expression is evaluated, the variable it bound is forgotten. The define syntax is not an expression.

From a glance it seems F# and OCaml do a similar thing: all but module/type top-level `let` bindings are expressions and do require `in` expressions. F# also adds some syntax sugar that allows mutating a bound value with `mutable` keyword, so there's a least some presence of a (mutable) state during evaluation of the expressions, if we're looking for any additions to what Scheme has.
I'm not sure if you'd qualify either of them as widely-enough-used languages, though. 🙂

Some examples, just in case:
```fsharp
// inline `let` syntax with explicit `in`
[1; 2] |> List.map (fun x -> let y = 1 in x + y)
```

```fsharp
do
    // `in` is implicitly added during parsing
    // when `in` expression is aligned with `let`
    let mutable x = 1

    // set and application expressions below make up a sequence expression
    x <- x + 1 // a set expression with unit type, mutating the state
    x + x // result of the sequence expression
```
