### ISSUE TITLE
Add a break implementation for clox?

### ISSUE THREAD

**Issue by nocturn9x** [munificent/craftinginterpreters#802]
I'm reimplementing clox in nim, adding more features along the way, and I'd like to implement the break statement. I was able to "implement" continue with the power of Ctrl+V from the examples directory, but I have no idea on how to implement a break statement with an unstructured source such as bytecode. There's no flow to be interrupted with an exception (I did that with my own python implementation of jlox), and jumping requires to know how far to jump, but that can't be known until the whole loop has been compiled (maybe a similar implementation to `patchJump` is needed?)

**Comment by mcfriend99** [comment]
@nocturn9x were you able to successfully do this??

**Comment by nocturn9x** [comment]
Yep, I ended up going for a different approach however (I, uh, kind of cheated by looking at other clox implementations). Basically every break statement creates a new break "object" which stores within it the boundaries of the loop it belongs to and then I have a neat `patchBreaks` function to patch those jumps. You can see my code here: https://git.nocturn9x.space/nocturn9x/peon (`src/frontend/compiler/targets/bytecode/target.nim`, see the `Loop` object at line 59 and the implementation of `breakStmt` and `patchBreaks)
