### ISSUE TITLE
Suggestion for the end of Chapter 21

### ISSUE THREAD

**Issue by BigZaphod** [munificent/craftinginterpreters#804]
(FYI: I absolutely love this book, btw - one of the best technical books I've ever read!)

At the end of Chapter 21 when compiling global variable assignment, it felt to me like it was a bit of a reluctant hack to weave the `canAssign` bool through all of those prefix functions. As I was following along coding I decided to try a different take and it seems to be working so far, but I might be missing some edge case: Instead of changing all of those function signatures to add a pesky bool, I just added a variable to track the current precedence level.

````
static void parsePrecedence(Compiler *compiler, Precedence precedence) {
	Precedence previousPrecedence = compiler->currentPrecedence;  // NEW
	compiler->currentPrecedence = precedence;  // NEW

	advance(compiler);
	ParseFn prefixRule = getRule(compiler->parser.previous.type)->prefix;
	if (prefixRule == NULL) {
		error(compiler, "Expect expression.");
		return;
	}
	
	prefixRule(compiler);

	while (precedence <= getRule(compiler->parser.current.type)->precedence) {
		advance(compiler);
		ParseFn infixRule = getRule(compiler->parser.previous.type)->infix;
		infixRule(compiler);
	}

	compiler->currentPrecedence = previousPrecedence;  // NEW
}
````

_NOTE: As I've been following along I decided to avoid the global `scanner` and `parser` stuff the book has and actually passed it around bundled together as a `Compiler` struct so my function has a `Compiler *` argument... but of course the book introduced its own Compiler struct in Chapter 22... but alas I shall make do :).`_

Then in the `namedVariable()` function I just check if `currentPrecedence <= PREC_ASSIGNMENT` and proceed accordingly. Using this approach I didn't even need to add an additional check for `TOKEN_EQUAL` at the end of `parsePrecedence()` to catch the assignment error as mentioned at the end of the chapter.

When attempting to compile the expression `a * b = c + d` I now get an error: `Error at '=': Expect ';' after expression.` which seems good enough to me.

Obviously it is possible that there's a higher purpose to having the `canAssign` parameter, but I thought I'd share in case you were interested in an optimization to shave a few paragraphs off of that chapter. :P

**Comment by BigZaphod** [comment]
Ok I've been farther now and I see how this is an annoying issue that winds its way through and my fix doesn't really work out. Dang.

**Comment by munificent** [comment]
I'm a little surprised your fix doesn't work. It seems like a feasible approach to me. Whether it's cleaner than passing `canAssign` around is mostly a matter of taste. Making it an explicit parameter felt a little simpler, but it is annoying to have the change the function signatures.
