### ISSUE TITLE
pub: not found when calling make get

### ISSUE THREAD

**Issue by will-sloan** [munificent/craftinginterpreters#810]
When I try calling `make get`, I'm getting the error
```
/bin/sh: 1: pub: not found
make: *** [Makefile:10: get] Error 127
```
I'm on ubuntu 20.04. I installed all the prerequisites. 
I'm trying to get a compiler working so I can run the examples in the intro to lox, not sure if `make get` is necessary to get that to work.

**Comment by munificent** [comment]
Do you have Dart installed and the Dart SDK's `bin` directory on your PATH?

**Comment by will-sloan** [comment]
Dart was installed, but it didn't add `pub` on my PATH.
