### ISSUE TITLE
Typos: Chapter 24 Challenge #2

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#812]
Challenge #2 begins thus:

> Native functions calls are fast in part because we don’t validate that the call passes as many arguments as the function expects function. 

Typo #1: "Native functions calls are fast ..."
Correction: "Native function calls are fast ..."
Action: Replace "functions" by "function"

Typo #2: "...as the function expects function. "
Correction: "...as the function expects. "
Action: Delete the last "function"

**Comment by munificent** [comment]
Thanks!
