### ISSUE TITLE
Typo: Section 25.4.3

### ISSUE THREAD

**Issue by eliaperantoni** [munificent/craftinginterpreters#818]
It says

> When we move the variable **off the heap**, if we move it into only one of the upvalues, the other upvalue will have an orphaned value.

when talking about closing an open up-value.

Shouldn't that say "onto the heap" or "off the stack" since we're moving the variable from the stack to the ObjUpvalue that's allocated on the heap?.

**Comment by munificent** [comment]
Yeah, I think you're right. This is a typo.

**Comment by eliaperantoni** [comment]
Whoops. I closed it because I thought the website was an old build. I checked the source and found an "off the stack" somewhere and jumped to the wrong conclusion that it was already fixed.

**Comment by munificent** [comment]
Thank you for filing this! That was a particularly confusing error in the book.
