### ISSUE TITLE
Chapter 26: Confusing stack illustration

### ISSUE THREAD

**Issue by eliaperantoni** [munificent/craftinginterpreters#820]
I'm reading the book built using commit ef1d428b6b795c98160297fe816990df9bdf0608.

There is this snippet:
```
fun makeClosure() {
  var a = "data";

  fun f() { print a; }
  return f;
}

var closure = makeClosure();
// GC here.
closure();
```

And it says:

> Say we pause the program on the marked line and run the garbage collector. [...]. But here’s what the stack looks like when we pause the program:

![image](https://user-images.githubusercontent.com/6002855/93486907-fee7a200-f904-11ea-91b2-b76a37a63e13.png)

I think at that point in time, between the two lines, only the script is on the stack. The closure is not.

I've tried running that using clox built from the repo:

![image](https://user-images.githubusercontent.com/6002855/93487577-b4b2f080-f905-11ea-90ff-c0db2c0141d0.png)

Which shows that just before line 10 (`closure();`) only the script is on the stack.

I think it would be more clear to the reader if it said that the GC is kicking in after `OP_GET_GLOBAL` pushes the closure function on the stack, but before `OP_CALL`.

**Comment by munificent** [comment]
This is a good catch! I figured the easiest fix was to tweak the example program to make `closure` a local variable. That way it is on the stack.
