### ISSUE TITLE
Chapter 5 challenge 1

### ISSUE THREAD

**Issue by pdrolopes** [munificent/craftinginterpreters#822]
Hello! 
After checking the results for the first challenge. 
![image](https://user-images.githubusercontent.com/158610/93690274-ce426c80-faac-11ea-845a-e4ae004c9706.png)
`expr` has at least one or more `call` expressions. 
But in the example that we should de-sugar , `expr` might have itself and other expression 0 or more times. 
![image](https://user-images.githubusercontent.com/158610/93690230-7dcb0f00-faac-11ea-85cb-ea4d913dfb78.png)
Isn't that final `*` suppose to be a `+`?

:)

**Comment by munificent** [comment]
Good eye, thank you! I think the grammar I had originally also technically works in that it recognizes the same language, but I agree that using `+` follows the structure of the answer better and is a cleaner grammar.
