### ISSUE TITLE
Question: Native Functions (Section 24.7)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#827]
Consider the following function declaration:

![image](https://user-images.githubusercontent.com/44275568/94322281-ebce7500-ff89-11ea-994f-e762b49fbc4e.png)

It assumes that the vm stack is empty when it is called. (This assumption is true in the specific case of "clock")

Would it not be safer to use `tableSet(&vm.globals, AS_STRING(peek(1)), peek(0));` instead?

**Comment by munificent** [comment]
Yeah, we could. But my intent was that you would only ever call this when first initializing a new fresh VM. Assuming there were more native functions, the process would be like:

1. Create VM.
2. Define all native functions.
3. Then start running user code.

I wouldn't expect to be adding other new natives at runtime. So we can reliably assume the stack is empty.
