### ISSUE TITLE
Question: Marking the Roots (Section 26.2.0)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#828]
Consider the markTable function:

```
void markTable(Table* table) {
  for (int i = 0; i < table->capacity; i++) {
    Entry* entry = &table->entries[i];
    markObject((Obj*)entry->key);
    markValue(entry->value);
  }
}
```

When passed a hash table, the function marks all entries in the table, including empty entries. Why do we do this? Why not skip all empty buckets? See below for an example:

```
void markTable(Table* table) {
  for (int i = 0; i < table->capacity; i++) {
    Entry* entry = &table->entries[i];

    if (entry->key == NULL) continue; //  <---- addendum

    markObject((Obj*)entry->key);
    markValue(entry->value);
  }
}
```

**Comment by cm1776** [comment]
Question regarding Section 26.3.2

In order to increase the capacity of the worklist, we use the following code:

 ```
 if (vm.grayCapacity < vm.grayCount + 1) {
    vm.grayCapacity = GROW_CAPACITY(vm.grayCapacity);
    vm.grayStack = realloc(vm.grayStack,
                           sizeof(Obj*) * vm.grayCapacity);
  }

Question: What happens if realloc fails to allocate more memory? Aborting the program would be in order.
```

**Comment by munificent** [comment]
>  if (entry->key == NULL) continue;

The `markObject()` function has an equivalent check in its body, so doing an extra check here wouldn't really buy us much. It would avoid a pointless check on the value (which will be `NIL_VAL`), I guess, but I'm not sure if that's an actual perf improvement. When most entries are non-empty, the redundant `NULL` check might make it a net loss.

> Question: What happens if realloc fails to allocate more memory? Aborting the program would be in order.

Yeah, it would be bad. :)
