### ISSUE TITLE
Paragraph formatting: Section 28.3

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#829]
Take a look at the following:

![image](https://user-images.githubusercontent.com/44275568/94375903-c74fd580-010e-11eb-987d-ac9d0841889f.png)

As you can see, the space between `For example, given a method call like` and `scone.topping("berries", "cream")` is excessive. Both can fit on the same line.

**Comment by munificent** [comment]
Moved the code to its own block. It was a little too long to fit inline.
