### ISSUE TITLE
8.1.1 Rephrase

### ISSUE THREAD

**Issue by iwatakeshi** [munificent/craftinginterpreters#83]
I would probably rephrase the following sentence:

>Splitting them into separate class hierarchies let’s us use the Java compiler to help us find dumb mistakes like passing a statement to a Java method that expects an expression.

to:

>Splitting them into separate class hierarchies ~let’s us use~ [allows or helps] the Java compiler ~to help us~ find dumb mistakes like passing a statement to a Java method that expects an expression.

or, if you want to include "us":

first attempt:
>Splitting them into separate class hierarchies lets us use the Java compiler to ~help us~ find dumb mistakes like passing a statement to a Java method that expects an expression.

second attempt:
> Splitting them into separate class hierarchies ~lets us use~ [allows] the Java compiler to help us find dumb mistakes like passing a statement to a Java method that expects an expression.

Anyways, I am super excited about this book. Great work and keep it up! 😄

**Comment by munificent** [comment]
Ah, great observation. That sentence was ugly. I took your last attempt but used "enables" instead of "allows".

Thank you!
