### ISSUE TITLE
Unused ingredient parameter: Section 29.3

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#830]
In the declaration of the Cruller class, the `ingredient `parameter is never used. 

```
class Cruller < Doughnut {
  finish(ingredient) {
    // No sprinkles.
    super.finish("icing");
  }
}
```

Did you intend to pass the parameter to `super.finish()` ?

**Comment by munificent** [comment]
That's deliberate, but maybe a little confusing. The `finish()` method called by `this.finish("sprinkles")`, so the overridden method needs to accept a parameter, even though it doesn't use it.
