### ISSUE TITLE
A typo in the Native Functions text

### ISSUE THREAD

**Issue by mz-111** [munificent/craftinginterpreters#831]
In _24.7: Native Functions_, when the text describes the `defineNative` function, it reads:

> We wrap the function in an ObjFunction and then store that in a global variable with the given name.

Isn't the 'ObjFunction' in that sentence supposed to be 'ObjNative'?

**Comment by munificent** [comment]
You're right, thank you!

**Comment by mz-111** [comment]
Glad I could help, it's a great book!
