### ISSUE TITLE
Chapter 4 Section 1

### ISSUE THREAD

**Issue by micpap25** [munificent/craftinginterpreters#832]
This segment:
```java
  private static void runPrompt() throws IOException {
    InputStreamReader input = new InputStreamReader(System.in);
    BufferedReader reader = new BufferedReader(input);

    for (;;) { 
      System.out.print("> ");
      String line = reader.readLine();
      if (line == null) break;
      run(line);
    }
  }
```
I think this is somewhat confusing because `for (;;) {}` is a convoluted way to say `while (true) {}`. Additionally, the whole section could be made more clear by doing something like this: 
```java
 String line;
 while ((line = reader.readLine()) != null) { 
      System.out.print("> ");
      run(line);
    }
```
I'm not sure if this implementation causes an issue with something later on in the book though. 
Do you think either of these could be implemented for clarity?

**Comment by munificent** [comment]
>  because `for (;;) {}` is a convoluted way to say `while (true) {}`.

This is mostly a question of stylistic preference. Either is a valid way of doing an infinite loop. I tend to lean towards the former because it's shorter and doesn't require a literal.

> ```java
>  String line;
>  while ((line = reader.readLine()) != null) { 
>       System.out.print("> ");
>       run(line);
>     }
> ```

That would read the line of input before printing the "> " prompt that should precede, which isn't what we want. :)

**Comment by micpap25** [comment]
wow, can't believe I missed that on the second part. lol.
