### ISSUE TITLE
Typo in 2.2.4

### ISSUE THREAD

**Issue by jayeshathila** [munificent/craftinginterpreters#836]
Seems like you missed something in - 

"You can do the same thing the HotSpot JVM, Microsoft’s CLR and most JavaScript interpreters do."

Can be:

"You can do the same thing `using` HotSpot JVM, Microsoft’s CLR and most JavaScript interpreters do."

**Comment by munificent** [comment]
Yeah, this sentence was correct but confusing. Re-opening this issue because I want to change it to "same thing *that* the HotSpot JVM do".
