### ISSUE TITLE
Discrepancy between chapter 25 and source code

### ISSUE THREAD

**Issue by ElessarDunadan** [munificent/craftinginterpreters#838]
The code for chapter 25 currently reads:

```
typedef struct ObjUpvalue {
  Obj obj;
  Value* location;
  Value closed;
  struct ObjUpvalue* next;
} ObjUpvalue;
```

However, the source code is written with "sUpvalue" instead of "ObjUpvalue" (object.h):

```
typedef struct sUpvalue { <-- here
  Obj obj;
  Value* location;
  Value closed;
  struct sUpvalue* next; <-- and here
} ObjUpvalue;
```

**Comment by munificent** [comment]
By "source code", do you mean here in the repo? Maybe you forked it before I landed 402ec1240dbc772648c111a3ed59a05eb0e173a5. The intent is that it should be ObjUpvalue everywhere now.
