### ISSUE TITLE
8.2.1 highlighted unchanged code

### ISSUE THREAD

**Issue by alexito4** [munificent/craftinginterpreters#84]
In the part where it mentions

> Then we add an expression node for accessing a variable:

and it shows the code

```
  "Literal  : Object value",
      "Unary    : Token operator, Expr right",
      "Variable : Token name"
    ));
```

the only difference is the addition of the Variable line, as the sidenote properly mentions

> tool/GenerateAst.java
in main()
replace 1 line

but the code has the Unary line also highlighted which is quite confusing. 

<img width="850" alt="screen shot 2017-06-01 at 23 26 26" src="https://cloud.githubusercontent.com/assets/750912/26703469/c7fcad0a-4721-11e7-9aad-01fcfa7cb024.png">

**Comment by munificent** [comment]
This is confusing but correct. In the previous code, there was no comma at the end of the Unary line. So this snippet adds Variable, but also touches the previous line to add the trailing comma.

Added an aside to explain it.

**Comment by martica** [comment]
If you add the new lines at the top (or at least not at the bottom) of these lists, you can avoid the issue with modifying a line to add a comma, and having extra commas in the interim states.

**Comment by munificent** [comment]
> This messes with the nice alphabetical order of course. :/

Yeah. That was the trade-off. I liked the alphabetical order more. 🤷‍♂️

**Comment by martica** [comment]
I understand.

You've got a couple more trailing commas in 8.1.1 and 8.2.1.
8.1.1:
    defineAst(outputDir, "Stmt", Arrays.asList(
      "Expression : Expr expression",
      "Print      : Expr expression",
    ));

8.2.1:
      "Print      : Expr expression",
      "Var        : Token name, Expr initializer",
    ));
