### ISSUE TITLE
Problem: Segfault before the first page is done

### ISSUE THREAD

**Issue by Bobbbay** [munificent/craftinginterpreters#842]
Heyo! 

Just today I started reading the CLOX book. I've gotten down to the bottom of the first page. Up to logging lines, it seemed to work fine. Now, I'm getting a segfault as well as an error of `137`. 

Not sure how to approach this. Uploaded what I have [here](https://github.com/bobbbay/lang). Cheers!

**Comment by munificent** [comment]
Hi, I'm sorry but I don't have the time to help debug reader's implementations. :(

**Comment by ogregoire** [comment]
@Bobbbay If you get the full repository and type:

```
make get
make c_chapters
```

The directory `gen/chap14_chunks` will be created (among others), containing the C files as they should appear at the end of Chapter 14, and you should then be able to check the difference with your code.

**Comment by Bobbbay** [comment]
@munificent Ah that's sadly understandable, no worries. Btw, great work on Wren!

@ogregoire Ah that's useful, I'll check when I get home! Cheers!
