### ISSUE TITLE
Features && adding more types and built-ins

### ISSUE THREAD

**Issue by valkarias** [munificent/craftinginterpreters#843]
Hello Bob...I have seen your book and i'm glad i found it..its just a perfect piece of art and i'm very glad its free..i didn't found any books like yours that are _free_..my question is. Are you gonna update this book in future and add more _features_ maybe and also..i'm not mainly into c but i want to add more types and keywords like lists and more built-ins for sake of learning and practicing,so what chapter you suggest to re-start with to implement these..i'm sure i cant done them without struggles because i don't know the steps exactly but just following the guide...Thanks

-valk

**Comment by munificent** [comment]
> Are you gonna update this book in future and add more features maybe and also.

No, no plans to add any more content to it. Right now, I'm working on the print edition and after that, the goal is for this project to be done so that I can free up some time and head space to think about the next thing. :)
