### ISSUE TITLE
Should `OP_SET_GLOBAL` do a stack pop on an undefined name?

### ISSUE THREAD

**Issue by woolsweater** [munificent/craftinginterpreters#845]
#409 pointed out that an undefined variable is accidentally defined when doing `OP_SET_GLOBAL`, which is undesirable in a REPL context. Should we also be doing a `pop();` in that case to balance out the push of the value that was to be assigned? Even if the assignment were part of a larger expression, we're not going to evaluate the rest of it after the error is raised.

```c
case OP_SET_GLOBAL: {
  ObjString* name = READ_STRING();
  if (tableSet(&vm.globals, name, peek(0))) {
    tableDelete(&vm.globals, name);
    pop();    // Also drop the value we were trying to assign
    runtimeError("Undefined variable '%s'.", name->chars);
    return INTERPRET_RUNTIME_ERROR;
  }
  break;
}
```

Consider this REPL trace. `c` does not exist, and we try to assign `10` to it. The value persists on the stack after the lookup error.

```
> c = 10;

0000 0001 OP_CONSTANT         0 '10'

[ number(10.0) ]
0002    | OP_SET_GLOBAL       1 'c'

1: error: Runtime Error: Undefined variable 'c'

> print nil;

[ number(10.0) ]
0000 0001 OP_NIL

[ number(10.0) ][ nil ]
0001    | OP_PRINT
nil

[ number(10.0) ]
0002    | OP_RETURN
```

The leftover value shouldn't cause a calculation failure since all valid operations are balanced, but repeatedly doing this in a long enough REPL session could eat up the stack.

**Comment by cm1776** [comment]
Hello @woolsweater ,

The last thing that runtimeError("Undefined variable '%s'.", name->chars) does before returning is to make a call to resetStack(). This latter effectively clears the vm stack so it becomes empty. As a result, there is no need to call pop() after calling tableDelete(&vm.globals, name).

**Comment by woolsweater** [comment]
Ah-ha! Looks like I missed that call in my implementation. 😅 Thanks!
