### ISSUE TITLE
Chapter 23.1 [question] How to determine the number of bytes to skip in if statement?

### ISSUE THREAD

**Issue by harrison-nc** [munificent/craftinginterpreters#847]
Hi, using the image below to show the memory cell for each byte. 
![g1089](https://user-images.githubusercontent.com/29671297/97904720-3093bb80-1d41-11eb-9277-5a899b20946e.png)
Let's assume that `OP_JUMP_IF_FALSE` is written to cell `3`, 
and the offset is written to cells `4` and `5`, at this point `chunk->count` would be at cell `6`
(because `chunk->count` points to the cell after the last byte).
Therefore, `emitJump` returns cell `4` as the offset after subtracting `2` in the statement
`return currentChunk()->count - 2;`. 

Let's also assume that the instructions for the *then branch* ends at cell `9`,
and `chunk->count` is at cell `10` (again, pointing to the empty cell after the last byte).

Then, in `patchJump` when `jump` is calculated in `int jump = currentChunk()->count - offset - 2;`.
We get `chunk->count` `10`, minus `offset` `4`, minus `2` `=` `4`.
So, at the end the `vm` needs to skip `4` cells to continue at the instruction after *then branch*.

**My question is, from which cell should we start counting the cells to skip?**
I assume that the cells to skip start from memory cell `6` after the offset and end at cell `9`. 
So, after jumping the `vm.ip` should be at cell `10`.
However, counting 4 cells from cell `6` ends up at cell `9` which is the last instruction of the *then branch*.

*Clearly, I have missed something, because to be correct the program should jump to cell `10` instead of cell `9`. What have I missed in the calculation above.*
Thanks.

**Comment by Sidewinder1138** [comment]
I too have been very confused by this...

**Comment by munificent** [comment]
There's no real right answer here. What really matters is that the compiler and runtime agree on where the relative count starts from.

In clox, the answer is that the jump is relative to where the instruction pointer currently is at the point that the jump instruction is processed. That makes the code in the interpreter as simple and fast as possible. Since the IP gets incremented as soon as its read, its current value will be just *past* the jump instruction and its operand.

**Comment by Sidewinder1138** [comment]
@harrison-nc You said `However, counting 4 cells from cell 6 ends up at cell 9 which is the last instruction of the then branch.`
But... 6+4 = 10, not 9. So counting 4 cells from 6 should mean you land on 10, not 9, right?

When trying to reason this stuff out, I'm always amazed how bad I am at just simply counting/incrementing/etc. I guess that's one of the fundamental reasons computers are so awesome, once we get the program right they always do this right. 

I've also found that just "going with something" and then just looking at the debug output (or stepping through with debugger) ends up working better for my understanding than trying to work it all out on paper.
