### ISSUE TITLE
PLUS snippet in ch7 evaluating expressions is missing a 'break'?

### ISSUE THREAD

**Issue by mcdurdin** [munificent/craftinginterpreters#850]
The code snippet for `case PLUS` has two `if` statements but if neither matches, it will fall through to the `case SLASH` case, in https://craftinginterpreters.com/evaluating-expressions.html

**Comment by cm1776** [comment]
Hello @mcdurdin ,

If you read on till the end of the "Detecting runtime errors" section (https://craftinginterpreters.com/evaluating-expressions.html#detecting-runtime-errors), you will find the solution to the problem.

Cheers

**Comment by mcdurdin** [comment]
@cm1776 fair enough -- it's a little misleading until you get to that point though! I think a sentence noting that there is a fall through that will be dealt with later would help.

**Comment by munificent** [comment]
@cm1776, you're right that the problem does get fixed by the next section. But that fallthrough does look pretty broken, so I went ahead and put a temporary `break` in there.
