### ISSUE TITLE
Support Array of Objects

### ISSUE THREAD

**Issue by tuantdang** [munificent/craftinginterpreters#851]
Dear Bob,
Thank you for your amazing contribution.
Base on your source, I implement another version of compiler that is written in pure C++.
I also add some new features such as support array 1D, 2D, 3D,....
But I have a problem with array of objects (class) when access member of its class.
Example:

```
class A{
   func1(){}
}

class B{
    init(n){
       this.manyA = CreateArray(n);
      for(i=0; i < n; i=i+1){this.manyA[i] = A()}
   }
}

var b = B(10);
b.manyA[2].func1();  // <--- I want support this grammar like Java/C++
```

===
Did you have any suggestion?

**Comment by munificent** [comment]
I'll give you a hint: The `[]` subscript expression syntax is almost identical to how we parse `()` for function calls. It even has the same precedence. So take a look at the code for handling function calls and go from there.

**Comment by tuantdang** [comment]
I did it. Thank you for our recommendation.
Best Regards,
