### ISSUE TITLE
Typo in Chapter 3: The Lox Language - Closures snippet? 

### ISSUE THREAD

**Issue by bhagerty** [munificent/craftinginterpreters#852]
Section 3.8.1, Closures, includes this code snippet to demonstrate passing around a function as an argument:

`print identity(addPair)(1, 2); // Prints "3".`

Can that be right? Aren't the parentheses misplaced? Shouldn't this be:

`print identity(addPair(1, 2)); // Prints "3".`

**Comment by kandersen** [comment]
I think that _is_ indeed right: that is a call to `identity` with `addPair` as an argument. That returns a function, that is then invoked with `1` and `2` as arguments.

**Comment by Samasaur1** [comment]
It is correct how it is — it's passing a reference to the function `addPair` without executing it.

**Comment by kandersen** [comment]
I hate to nit, but I think the precise phrase is "it's passing the function that is the result of evaluating `addPair`" - introducing a distinction of "executing" or "not executing" and "references" would only muddy the picture.

**Comment by Samasaur1** [comment]
@kandersen No worries! You're absolutely right — I was using terminology from a different language.

**Comment by munificent** [comment]
@kandersen and @Samasaur1 are right. This code is *deliberately* funny looking. :)

**Comment by AlissonPQ** [comment]
Thanks for linking to the duplicate. I think this throws people off-guard because it is in beginning of the book and some of us might just be running the code in our heads up to that point. After this one I decided to install the interpreter so I can at least run the code from now on and avoid more confusion.
