### ISSUE TITLE
Type in Chapter 8: Statements and State

### ISSUE THREAD

**Issue by Samasaur1** [munificent/craftinginterpreters#853]
One of the asides in Chapter (`name="void"`) had seems to have a small typo (emphasis mine):
> Java doesn't let you use lowercase "void" as a generic type argument for obscure reasons having to do with type erasure and the stack. Instead, there is a separate "Void" type specifically for this use. Sort of a "boxed void", **list** "Integer" is for "int".

I think this was supposed to be this:
> Java doesn't let you use lowercase "void" as a generic type argument for obscure reasons having to do with type erasure and the stack. Instead, there is a separate "Void" type specifically for this use. Sort of a "boxed void", **like** "Integer" is for "int".

**Comment by munificent** [comment]
Good catch, thanks!
