### ISSUE TITLE
Typo in Chapter 9: Control Flow

### ISSUE THREAD

**Issue by Samasaur1** [munificent/craftinginterpreters#854]
The grammar excerpt for adding logical `or` and logical `and` modifies the assignment production, but does so incorrectly. `IDENTIFIER`, which is a literal, is lowercase, as if it were a production, instead of uppercase as literals should be. Here's what's there:
```ebnf
expression     → assignment ;
assignment     → identifier "=" assignment
               | logic_or ;
logic_or       → logic_and ( "or" logic_and )* ;
logic_and      → equality ( "and" equality )* ;
```
Here's what it should be (to keep `IDENTIFIER` consistent, as it is a literal, not a production):
```ebnf
expression     → assignment ;
assignment     → IDENTIFIER "=" assignment
               | logic_or ;
logic_or       → logic_and ( "or" logic_and )* ;
logic_and      → equality ( "and" equality )* ;
```

(note: GitHub's syntax highlighting doesn't show a color difference, but I'm pretty sure it would when rendered for the website).

**Comment by munificent** [comment]
You have a sharp eye!
