### ISSUE TITLE
design book cover

### ISSUE THREAD

**Issue by gengjiawen** [munificent/craftinginterpreters#856]
It will be good to see a cover :)

**Comment by munificent** [comment]
I don't have a cover design yet, but I'm very much looking forward to doing that once I have the chapters typeset. :)

**Comment by cm1776** [comment]
Hi @munificent ,

Don't let #608, #621, #657, and #820 get lost in the haystack of discussions, questions, and sites.

Cheers

**Comment by munificent** [comment]
I haven't forgotten them, just procrastinated them. :)

Although, I have to admit I may end up deciding not to do that design note.
