### ISSUE TITLE
Typo in illustration (a-virtual-machine/ast.png)

### ISSUE THREAD

**Issue by toebsen** [munificent/craftinginterpreters#859]
There is a very small typo in: 
- https://github.com/munificent/craftinginterpreters/blob/master/site/image/a-virtual-machine/ast.png

Instead of ``echo(6)`` it should be ``echo(9)``  as in 

```
9  // from echo(4 + 5)
12 // from print 3 + 9
```

**Comment by kandersen** [comment]
No, it's the evaluation order of expression, not results. It just happens to coincide with 1, 2, 3, 4 and 5 :)
