### ISSUE TITLE
Clarification needed ("That slot isn’t used right now") : Section 24.5.1

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#863]
Consider the following excerpt:

![image](https://user-images.githubusercontent.com/44275568/102712029-59a2e800-42be-11eb-83a0-fb787adca7e4.png)

`The funny little - 1 is to skip over local slot zero, which contains the function being called. That slot isn’t used right now, but will be when we get to methods.`

Both your text and diagram show that local slot zero contains `sum`. What then do you mean by saying `That slot isn’t used right now`?

**Comment by munificent** [comment]
Yeah, that was confusing.
