### ISSUE TITLE
Running test suite with user created interpreters

### ISSUE THREAD

**Issue by SpireFlux** [munificent/craftinginterpreters#868]
I've been looking through the docs, issues, and wiki to see if there's a discussion on how to test user created interpreters? 

Is this something built-in, or should I be looking at hacking  on `tool/bin/test.dart`?

**Comment by munificent** [comment]
There's no built-in support for custom interpreters, unfortunately. You'll want to just hack it into tool/bin/test.dart directly.

**Comment by munificent** [comment]
Re-opening this to remind me to consider adding support for this. :)

**Comment by SpireFlux** [comment]
Is this something you'd want a PR for?

**Comment by munificent** [comment]
I just saw your comment. Oops, I beat you to it! :)

**Comment by SpireFlux** [comment]
Quite all right.  I had been hacking at it in my spare time.  I did wonder if dart had a argparse module.  Thanks for adding it in.  I've been wanting to test my work after every chapter.  (Maybe add some more documentation on how the filterPath works?)  

Thanks again.
