### ISSUE TITLE
Nit: is the go tool a compiler?

### ISSUE THREAD

**Issue by skybrian** [munificent/craftinginterpreters#87]
re: http://www.craftinginterpreters.com/a-map-of-the-territory.html

At nit on the aside about the "go" tool: I believe the "go" tool runs a compiler, but doesn't contain it. If you run `go tool` it will print out all the tools in the `pkg/tool/darwin_amd64` directory (on a Mac). One of them is named `compile`, and that's the compiler.

Also, I don't think there is any special interpreter; it just runs the executable.

**Comment by munificent** [comment]
Technically correct, the best kind of correct!

From the user's perspective, it's a single holistic tool. Whether it's a couple of executables under the hood is an implementation detail, I think. The user experience is that there is this one thing, "go" that can either compile code and stop, or execute a program from source (by compiling it under the hood).
