### ISSUE TITLE
Suggestion: Relocate Aside (Section 30.3.3)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#870]
The following aside:

![image](https://user-images.githubusercontent.com/44275568/103100174-bf220c00-4611-11eb-86b9-957360c0c720.png)

which currently appears next to:

![image](https://user-images.githubusercontent.com/44275568/103100225-e4af1580-4611-11eb-9315-ed796205fbf1.png)

should be relocated next to:

![image](https://user-images.githubusercontent.com/44275568/103100261-08725b80-4612-11eb-802b-15869beba751.png)

under the definition of `static inline double valueToNum(Value value)`

**Comment by munificent** [comment]
Good idea!
