### ISSUE TITLE
Section 6 . 3 . 3 state synchronization ambiguity

### ISSUE THREAD

**Issue by benrkia** [munificent/craftinginterpreters#872]
After reading this section I thought of a use case that I think might be enhanced.
Take this first example
```bash
> print ( 3 + 8 , var b = 5
[line 1] Error at ',': Expect ')' after expression.
[line 1] Error at end: Expect ';' after variable declaration.
```
Now if we do
```bash
> print ( 3 + 8 var b = 5
[line 1] Error at 'var': Expect ')' after expression.
```
I think the later should also report 2 errors and not one.

**Comment by munificent** [comment]
I think I'm OK with that error output. If anything, I'd prefer there only be a single error on the first example too. Either way, I'm not sure what's actionable here, so I'm going to go ahead and close this out. Error recovery is always kind of ad hoc, so it's never perfect.
