### ISSUE TITLE
Section 9.5 error in foor loop grammar

### ISSUE THREAD

**Issue by DerpyJish** [munificent/craftinginterpreters#874]
If I'm not mistaken, the for loop grammar shown at the top of the section has an error. Currently it is:
```
forStmt        → "for" "(" ( varDecl | exprStmt | ";" )
                 expression? ";"
                 expression? ")" statement ;
```
where I think instead it should be:
```
forStmt        → "for" "(" ( varDecl | exprStmt ) ";" 
                 expression? ";"
                 expression? ")" statement ;
```
(the change is at the end of the first line)

I'm learning a lot from the book (it's a great read!) so apolagies if I've simply misinterpreted the grammar, but I think that's right.

**Comment by cm1776** [comment]
Hello @DerpyJish,

If you go back to [Chapter 8: Statements and State](https://craftinginterpreters.com/statements-and-state.html), you will notice the following grammar rules:

`exprStmt       → expression ";" ;` (Section 8.1)

`varDecl        → "var" IDENTIFIER ( "=" expression )? ";" ;`  (Section 8.2.1)

Note in particular that both rules terminate in` ";"`. Hence no  additional` ";"` is necessary when either rule is satisfied.

All the above is a rather long way of saying that the grammar in the book is correct.

Cheers and Compliments of the Seasons!

**Comment by DerpyJish** [comment]
Oh of course! My bad 😅

And yes, I hope the festive season is treating you well!

**Comment by DerpyJish** [comment]
Also I've just spotted the typo in my title, oh the irony!
