### ISSUE TITLE
Section 28.3.1: code placement directions incorrect?

### ISSUE THREAD

**Issue by ElessarDunadan** [munificent/craftinginterpreters#875]
The following line is to be added right after the "current" variable:

```
Compiler* current = NULL;

**ClassCompiler* currentClass = NULL;**

static Chunk* currentChunk() {
```

However, the placement directions read:

> compiler.c, add after variable Parser

The variable parser is right before the variable current, so either the placement or the directions should probably be corrected.

**Comment by munificent** [comment]
You're right. That one and a bunch of others were wrong too. Bug in the code that figures out snippet locations. Thanks!
