### ISSUE TITLE
Signed char is used in hashString

### ISSUE THREAD

**Issue by tyfkda** [munificent/craftinginterpreters#881]
Probably this causes no problem, but I want to mention because I got little confused.

`char*` is used in `hashString` function to calculate hash value:
https://github.com/munificent/craftinginterpreters/blob/master/c/object.c#L141

If a given string contains a character greater than or equal to `0x80`,
signed value is extended to `uint32_t` so
hash value becomes different from FNV1a
and not sure hash value is dispersed as expected.

**Comment by munificent** [comment]
Ah good catch. Like you say, I don't think this causes any real problems except maybe in the hash distribution, but it's definitely not intentional to sign-extend. Thanks!
