### ISSUE TITLE
clox does not compile as strict ISO C++

### ISSUE THREAD

**Issue by invertego** [munificent/craftinginterpreters#885]
This issue pertains to the fix for #676: commit 5c31fe0df66e6927a9c0d3f6253594e57d29301b. This commit added a dependency on C99's designated initializer syntax for arrays.

A side note in "Classes and Instances" mentions that clox can be compiled as either C or C++. Unfortunately, array designators are simply not a part of any C++ standard. The C++20 standard [added partial support](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0329r4.pdf) for designated initializers but excluded array designators with the rationale that they conflict with lambda-expression syntax.

GCC supports them in C++ as a nonstandard language extension, and Clang follows suit for compatibility with GCC. Other compilers, such as MSVC and ICC, support designated initializers for data members (as defined by the ISO standard) but not the GCC-specific extensions.

On the bright side, it is already possible to compile clox with those other compilers, provided you tell them to compile as C and not C++.

**Comment by munificent** [comment]
Thanks for catching this! I poked around at removing the designated initializers to get it to be strictly valid C++, but it felt pointlessly pedantic and verbose, so I just reworded the aside a little.

**Comment by invertego** [comment]
Later I noticed there is a similar aside in "Methods and Initializers". Not sure if you want to edit that as well or leave it as-is, but either way, I thought I should mention it.
