### ISSUE TITLE
[clox] Why we need to mark the closure through `CallFrame` when GC happens?

### ISSUE THREAD

**Issue by enochii** [munificent/craftinginterpreters#889]
Hello, thanks for this awesome book! I'm a little confused [here](http://www.craftinginterpreters.com/garbage-collection.html#less-obvious-roots). It claims that
>Most function call state lives in the value stack, but the VM maintains a separate stack of CallFrames. Each CallFrame contains a pointer to the closure being called. The VM uses those pointers to access constants and upvalues, so those closures need to be kept around too.
>```c
>  for (int i = 0; i < vm.frameCount; i++) {
>    markObject((Obj*)vm.frames[i].closure);
>  }
>```
My question is, when we call a closure(or we say function), the closure is in the runtime stack(at the begin of active frame), which we would do the marking when traversing the stack. So I don't know why we need to do the marking through `vm.frames` again.
Could you point out where I am wrong? Thanks!

**Comment by munificent** [comment]
You are correct that the functions are on the stack at that point in the book. But when methods are added in a later chapter, the stack slot that currently holds the function ends up holding the `this` reference instead. I suppose you can probably still reach the called method through the instance's class reference and from there to the method table, so even then it's technically redundant. But, I don't know, it seems cleaner/safer to me to mark the closure pointers in the frame array too.

**Comment by enochii** [comment]
I got it. Thanks!
