### ISSUE TITLE
Trouble with clox on windows.

### ISSUE THREAD

**Issue by nailuj29gaming** [munificent/craftinginterpreters#892]
I just finished jlox, so I started clox. I am very new to C programming, so I don't really know what I'm doing, and when I finished chapter 17, I started noticing a strange error. The call to `realloc` in `reallocate` ran out of memory. When debugging with Visual Studio, there should be sufficent memory, the arguments are very low. This only happens when there are multiple chained binary expressions such as 3 + 3 + 3. This might be an error on my end, but the code in `reallocate`, which I believe to be the root of the problem, is the same as the provided code, except I added some logging.

**Comment by munificent** [comment]
I know other readers have run the code on Windows without issue, so it's likely an error on your side, but I'm not sure. I don't have a handy Windows machine to test on. The usual culprits when you see huge memory allocation are:

* Some unexpected implicit signed-unsigned conversion.
* Unexpected underflow or overflow.

You might want to try enabling as many warnings as you can in your compiler about implicit conversions. By default, C compilers tend to be pretty permissive. Sorry I can't help you debug it in more detail.
