### ISSUE TITLE
[Typo] Section 2.2.3 side blurb "did" => "died"?

### ISSUE THREAD

**Issue by xysun** [munificent/craftinginterpreters#893]
"He died too young, but sure as hell lived before he did." => "before he died"?

(not native speaker though so apologies if this is intentional)

**Comment by GoldfieldGeek** [comment]
This is idiomatic English, and would be recognized as correct by a native English speaker.
“Did" refers to the action mentioned previously in the sentence.

**Comment by xysun** [comment]
ah I see. Thanks.
