### ISSUE TITLE
code error in the book

### ISSUE THREAD

**Issue by bulanzade** [munificent/craftinginterpreters#899]
http://craftinginterpreters.com/scanning.html#reserved-words-and-identifiers

![screenshot](https://note.youdao.com/yws/api/personal/file/WEB99b7af2d9c14ba4a59c7c2bbb4100837?method=download&shareKey=482feb62520b392a1972fa77cb92f467)
the code may write like this:
```java
case 'o':
    if (this.match('r'))
    {
        this.addToken(TokenType.OR);
    }
    break;
```

**Comment by nalzok** [comment]
I believe this is not an error. If you try compiling the code it will work. In fact, the author deliberately omitted `this.` and `TokenType.` as he said

> I know static imports are considered bad style by some, but they save me from having to sprinkle `TokenType.` all over the scanner and parser. Forgive me, but every character counts in a book.

**Comment by bulanzade** [comment]
If you complied the code, you will get an error. The key point is not ```this.``` and ```TokenType.``` (In fact, it's just my personal habit) , but the method ```peek()``` vs ```match()```. 
```peek()``` won't consume the 'r' character and will result in ```Unexpected character``` error.

**Comment by bulanzade** [comment]
> I believe this is not an error. If you try compiling the code it will work. In fact, the author deliberately omitted `this.` and `TokenType.` as he said
> 
> > I know static imports are considered bad style by some, but they save me from having to sprinkle `TokenType.` all over the scanner and parser. Forgive me, but every character counts in a book.

If you complied the code, you will get an error. The key point is not this. and TokenType. (In fact, it's just my personal habit) , but the method peek() vs match().
peek() won't consume the 'r' character and will result in Unexpected character error.

**Comment by bulanzade** [comment]
> I believe this is not an error. If you try compiling the code it will work. In fact, the author deliberately omitted `this.` and `TokenType.` as he said
> 
> > I know static imports are considered bad style by some, but they save me from having to sprinkle `TokenType.` all over the scanner and parser. Forgive me, but every character counts in a book.

If you complied the code, you will get an error. The key point is not ```this.``` and ```TokenType.``` (In fact, it's just my personal habit) , but the method ```peek()``` vs ```match()```.
 ```peek()``` won't consume the 'r' character and will result in ```Unexpected character``` error.

**Comment by nalzok** [comment]
Oh, I see. You are right and this snippet is wrong. Even though the preceding paragraph says

>  You might think we could match keywords like `or` in the same way we handle multiple-character operators like `<=`:

The author presented this (deliberately incorrect) snippet to illustrate the maximal munch principle, instead of having us leave an extra character in the source buffer.

**Comment by munificent** [comment]
At some level this doesn't matter since it's just hypothetical wrong code anyway, but I agree using `match()` here makes more sense. Thanks!
