### ISSUE TITLE
8. Mention update AstPrinter

### ISSUE THREAD

**Issue by alexito4** [munificent/craftinginterpreters#90]
In this chapter many new types are added to the AST but I think the chapter doesn't mention the need to update the AstPrinter.
Is a trivial change that anyone finds easily by running the compiler but I thought on raising it, maybe is worth mentioning it in a side note.

**Comment by munificent** [comment]
Yeah, I thought about that, but I felt it would be annoying to keep reminding people about that. So in chapter five, I say:

> Also, as we add new syntax tree types, I won’t bother showing the necessary visit methods for them in AstPrinter. If you want to (and you want the Java compiler to not yell at you), go ahead and add them yourself.

Trying to let myself off the hook here... 😁
