### ISSUE TITLE
Improving jlox's Scanner by maintaining line/column offset in advance()

### ISSUE THREAD

**Issue by nalzok** [munificent/craftinginterpreters#900]
Instead of having `if (peek() == '\n') line++;` everywhere, what about moving the house-keeping code to `advance`? This should make the implementation clearer and less error-prone. For example,

```
private char advance() {
    current++;
    char c = source.charAt(current - 1);
    if (c == '\n') line++;
    return c;
}
```

By the way, we can easily add another private field `column` which tracks each token's offset in its line and update it in `advance`.

**Comment by munificent** [comment]
I agree that is a little cleaner, but there's only two calls to `line++`, so it's not saving much. I've already gone through copy editing that chapter, so I'm hesitant to make changes (and risk new mistakes in the prose) unless there's a significant improvement, so I think I'm going to leave this as it is.
