### ISSUE TITLE
Weird GROW_CAPACITY behaviour

### ISSUE THREAD

**Issue by mcfriend99** [munificent/craftinginterpreters#905]
Hi @munificent 

I am trying to test a new multiplier for the GROW_CAPACITY macro (1.5).

For some weird reason, whenever I change the multiplier to a non power of 2 number, nothing works anymore. When I profiled it, I saw that both findEntry and tableFindString no longer works. valuesEqual no longer works, AS_OBJ no longer works.

What could be responsible for this weird behaviour??

**Comment by munificent** [comment]
> For some weird reason, whenever I change the multiplier to a non power of 2 number, nothing works anymore. When I profiled it, I saw that both findEntry and tableFindString no longer works. valuesEqual no longer works, AS_OBJ no longer works.

Are you enabling `NAN_BOXING`? That requires hash tables to have a power of two capacity.

**Comment by mcfriend99** [comment]
I suspected as much and disabled nan boxing and the behavior is still the same. 

Also, if nan boxing requires the capacity to grow at a power of two, the question is why?? And wouldn't it be good to mention it in the book??

**Comment by cm1776** [comment]
> Also, if nan boxing requires the capacity to grow at a power of two, the question is why?? And wouldn't it be good to mention it in the book??

Read the whole of section[ 30.2 (Faster Hash Table Probing)](https://craftinginterpreters.com/optimization.html#faster-hash-table-probing) for the answer.

**Comment by munificent** [comment]
Oh, I'm sorry. I got my wires crossed. :)

It's not `NAN_BOXING` that's the problem. It's the *other* optimization in the last chapter that replaces the modulo (`%`) with bitwise and. If you undo that optimization and go back to `%`, then your non-power of two capacity change should work fine.
