### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mark-summerfield** [munificent/craftinginterpreters#907]
In http://craftinginterpreters.com/introduction.html
s/However, it work by taking advantage/However, it works by taking advantage/

**Comment by docwhat** [comment]
Full paragraph from section 1.3:

> By the end of part II, we’ll have a simple, readable implementation. It’s not very fast, but it’s correct. However, it work by taking advantage of the Java virtual machine’s own runtime facilities. We want to learn how Java itself implements those things.

The whole paragraph could use a rewrite or maybe splitting it up; having a compiler and wanting to understand how Java does things almost seem like separate thoughts.
