### ISSUE TITLE
Precedence confusion

### ISSUE THREAD

**Issue by MichaelLiuzzi** [munificent/craftinginterpreters#908]
Hi!

Firstly, thank you so much for this book. It has been a joy to read and work through. I have a question. Is an expression like this forbidden by Lox's grammar?

print 1 + 4 * 6 + 2

I have also tried grouping like so ((2+3) * 4) and that will fail. But (2+3) * 4 will succeed. Is that also intended? It seems like additional parentheses should be permissible.

**Comment by mcfriend99** [comment]
Did you finish the post on expression parsing?? Because that works perfectly in my implementation

**Comment by munificent** [comment]
> Is an expression like this forbidden by Lox's grammar?
> 
>     print 1 + 4 * 6 + 2

No, that should be allowed and work fine. Probably a bug somewhere in your parser implementation. (Happens to the best of us.) :)
