### ISSUE TITLE
typo???!!!

### ISSUE THREAD

**Issue by OrionRandD** [munificent/craftinginterpreters#910]
"At the same time, I don’t want to drag you through reams of language lawyering..."
Is it reams or realms?

Also, I have installed everything and have this in my folder:
built with:
make get
make 
And then???!!!

asset/  build/  java/  site/  tool/  clox*  LICENSE   README.md
book/   c/      note/  test/  util/  jlox*  Makefile

But have no idea on where and how to start using it :(
How do I open the files? With Vim, Emacs, in the browser?
Which is the lox language extension?  my_hello_world.lox???!!!

**Comment by degustaf** [comment]
[Not a typo.](https://www.dictionary.com/browse/ream)

As for running it. You can get a repl by running either clox, or jlox. The file extension is lox. Either vim, or emacs should be able to open the files.

**Comment by cm1776** [comment]
Hi @OrionRandD,

If you are satisfied with the response of @degustaf, I would suggest that you close your issue.

Cheers

**Comment by OrionRandD** [comment]
@cm1776  Yes and no.

./jlox see.lox

[line 12] Error: Unexpected character.
[line 12] Error: Unexpected character.
[line 17] Error: Unexpected character.
[line 17] Error: Unexpected character.
[line 1] Error at 'com': Expect ';' after expression.
[line 3] Error at 'java': Expect ';' after expression.
[line 4] Error at 'java': Expect ';' after expression.
[line 5] Error at 'java': Expect ';' after expression.
[line 6] Error at 'java': Expect ';' after expression.
[line 7] Error at 'java': Expect ';' after expression.
[line 8] Error at 'java': Expect ';' after expression.
[line 9] Error at 'java': Expect ';' after expression.
[line 11] Error at 'class': Expect ';' after expression.
[line 17] Error at '0': Expect ')' after arguments.
[line 21] Error at '}': Expect expression.

The file content is:

package com.craftinginterpreters.lox;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class Lox {
  public static void main(String[] args) throws IOException {
    if (args.length > 1) {
      System.out.println("Usage: jlox [script]");
      System.exit(64);
    } else if (args.length == 1) {
      runFile(args[0]);
    } else {
      runPrompt();
    }
  }
}

**Comment by munificent** [comment]
That file content is Java code, not Lox code.
