### ISSUE TITLE
Perl 6 renamed to Raku

### ISSUE THREAD

**Issue by heyajulia** [munificent/craftinginterpreters#912]
Hi!

[Perl 6 was renamed to Raku in October 2019](https://lwn.net/Articles/802329/). [A cursory Google search](https://www.google.com/search?q="Perl+6"+site:craftinginterpreters.com) shows the book only mentions Perl 6 two times in passing—[once in "Strings"](https://craftinginterpreters.com/strings.html), [and again in "Classes"](https://craftinginterpreters.com/classes.html)—but I still thought you might want to fix this (but it's not a huge problem).

**Comment by munificent** [comment]
Good catch, thanks!
