### ISSUE TITLE
Why not use call(function,0)? (Section 24.5.1)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#916]
At the end of Section 24.5.1, we replace the 4 lines below:

```
  CallFrame* frame = &vm.frames[vm.frameCount++];
  frame->function = function;
  frame->ip = function->chunk.code;
  frame->slots = vm.stack;
```
by `callValue(OBJ_VAL(function), 0);`

Here is what happens:

1. We wrap `function `(which we know is of type `ObjFunction*`) in a `Value `struct.
2. We invoke `callValue `with the above `Value `struct and `Zero`.
3. `callValue `determines the type of the `Value `struct to be `OBJ_FUNCTION`.
4. `callValue `then unwraps the `Value `struct to get back the bare `function`.
5. Finally, `callValue `invokes `call `with `function `and `Zero`.

Question: Rather than replacing the original 4 lines by` callValue(OBJ_VAL(function), 0); `why not just use `call(function,0)` in the first place?

**Comment by cm1776** [comment]
We have the same issue (question) with regards to the end of Section 25.1

```
  ObjClosure* closure = newClosure(function);
  pop();
  push(OBJ_VAL(closure));
  callValue(OBJ_VAL(closure), 0);

```
Why not replace `callValue(OBJ_VAL(closure), 0);` by` call(closure, 0);`

**Comment by mcfriend99** [comment]
If you replace all of the four line with the single line, you are highly likely encounter a garbage collection error (more when you get to garbage collection in the book) because the new closure will not be on the stack when it is being used and can get collected before the VM can finish the `callValue()` method. For any operation beyond a few lines of code, you will definitely encounter the GC error.

**Comment by munificent** [comment]
@cm1776 is right, there's no real point to going through `callValue()`. Thanks for the suggestion!

**Comment by mcfriend99** [comment]
I must have misinterpreted his question. I thought he was talking about replacing the entire four lines with the single line. Of course, the `callValue` in the last line can be replaced by `call`.
