### ISSUE TITLE
Premature example: Section 28.1.2

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#918]
Consider the following excerpt:

![image](https://user-images.githubusercontent.com/44275568/111222769-93913b00-85dc-11eb-9c85-5ceb19b4579e.png)

At this point in the book, if you _throw the example at the compiler_, you will get a compile error. 

To compile successfully, you must wait until you define `static void defineMethod(ObjString* name)` , which occurs towards the end of Section 28.1

**Comment by mcfriend99** [comment]
Nope. the `defineMethod` allows the VM to run this code, but if you have debug enabled, you should see it compile successfully. Here, @munificent was referring to the programs ability to compile not its ability to run.

**Comment by cm1776** [comment]
Seeing how far the author has progressed in the production (for publication) of his book (see https://twitter.com/munificentbob/status/1395739627235864581/retweets/with_comments for details), I am closing this issue in order not to distract the author unnecessarily. After all, the issue is NOT a show stopper.

**Comment by munificent** [comment]
I might take a look at this, but no promises. :)

**Comment by cm1776** [comment]
Book is published. Too late for change.
