### ISSUE TITLE
Suggestion: Section 28.4 (class CoffeeMaker)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#919]
Right at the end of Section 28.4 we have the following:

![image](https://user-images.githubusercontent.com/44275568/111342286-993d5e00-867a-11eb-81d7-eedf503ea86b.png)

When we run `maker.brew() `the first time, we get the expected response: `Enjoy your cup of coffee and chicory
`
However, running `maker.brew()` a second time produces an error: `Operands must be two numbers or two strings.` _But all we wanted was a second cup of coffee and chicory._

Here is a suggested update for `brew()` that prevents the above error message and provides an endless supply of our favorite beverage:

```
  brew() {
      print "Enjoy your cup of " + this.coffee;
  }
```

**Comment by munificent** [comment]
If only real coffee makers would also magically provide infinite coffee. :)

In this case, I think the dumb little joke in the original code is worth keeping.
