### ISSUE TITLE
4.6 Possible typo

### ISSUE THREAD

**Issue by cesartl** [munificent/craftinginterpreters#921]
```java
 private char peek() {
    if (isAtEnd()) return '\0';
    return source.charAt(current);
  }
```

shouldn't it be?
```java
 private char peek() {
    if (isAtEnd()) return '\n';
    return source.charAt(current);
  }
```

also
```java
while (peek() != '\n' && !isAtEnd()) advance();
```
since `peek` is already checking `isAtEnd`, do we need to check it again in the `/` case?

**Comment by cesartl** [comment]
ok I think I see what's happening. I'm doing the parser in Kotlin and it doesn't have `\0`, I guess it makes sense in that case.

**Comment by doste** [comment]
Hi, I have the same question. Why should we use '\0' instead of '\n' ?

**Comment by munificent** [comment]
The value returned here doesn't matter very much because, in general, the scanner code that calls `peek()` is also checking for `isAtEnd()`. Returning `\0` is just a value that won't appear in the string itself, so is a useful way to signal "no more characters in the input".
