### ISSUE TITLE
Ch. 3: lox.exe

### ISSUE THREAD

**Issue by StrongBishop** [munificent/craftinginterpreters#923]
Hi Bob,

I love your work. Thank you for sharing, and definitely let me know when and where your book signing is so I can get my own autographed copy.  😀

In the intro to Chapter 3, you say, "A tutorial isn’t very fun if you can’t try the code out yourself. Alas, you don’t have a Lox interpreter yet, since you haven’t built one!  Fear not. You can use mine."

Have you thought about also making an executable available in your repo for folks to try?  It would provide immediate gratification in the moment.  I'm guessing you have thought about it and have your reasons for not supplying one.  In any case, I'm curious.

While I got Visual Studio Code up and running (and have contributed my learnings to your Discussion about compiling to Windows to help get others up to speed more quickly), it would have made reading Chapter 3 more enjoyable for me.

**Comment by StrongBishop** [comment]
On the plus side, I eventually got my environment setup (which I needed to do anyway) and both lox implementations working. I just had to delay gratification, which I had in abundance.

**Comment by munificent** [comment]
> Have you thought about also making an executable available in your repo for folks to try?

I have, but that's a real maintenance chore. It would mean that every time I touch the code I have to get my hands on a Mac, Linux, and Windows machine. People will end up asking for it to be on every distro's package manager, etc.
