### ISSUE TITLE
[jlox] Possibly use static methods for predicates in Scanner?

### ISSUE THREAD

**Issue by quipa** [munificent/craftinginterpreters#931]
I'm new to Java so feel free to disregard my issue if it's silly! 

Would turning the following methods in the `Scanner` class `static` make sense in terms of efficiency and if so is it worth the extra characters considering your aim for concise code in the book?

```java
static private boolean isAlpha(char c)
static private boolean isDigit(char c)
static private boolean isAlphaNumeric(char c)
```

If it is silly and you do have the time to answer, thanks in advance!

**Comment by munificent** [comment]
I can't answer definitely without looking at a profiler, but I would be *very* surprised if making the methods static had any performance effect. The bodies are small enough that the JVM JIT probably inlines the bodies wherever they are call. Also, I don't think there's a significant performance different between static and instance invocations if they aren't inlined.

Good question!
