### ISSUE TITLE
[book] Side note chapter 8 on declarations that are expressions.

### ISSUE THREAD

**Issue by quipa** [munificent/craftinginterpreters#934]
In the side note of the introduction of Chapter 8, 3rd paragraph, you say:

"You could make a language that treats variable declarations as expressions that both create a binding and produce a value, but I’m not aware of any widely used languages that do that. Scheme seems like a contender, but note that after a let expression is evaluated, the variable it bound is forgotten. The define syntax is not an expression."

Tcl's `set` and `incr` actually seem to do this :smiley:!

```tcl
% set a 1
1
% expr {$a + [set b 2]}
3
% list $a $b [set c 3]    
1 2 3
% puts $c
3
% expr {1 + [incr i]}
2
% puts $i
1
```
Not sure if Tcl can be said to be widely used these days (except through tk bindings), but it does show up with Scheme in the *next 50 programming languages* section of [TIOBE Index as of April 2021](https://www.tiobe.com/tiobe-index/).

By the way after Scheme/Lisp, Tcl is probably one of the most metaprogrammable languages I've seen around. I highly recommend the [Tcl the misunderstood](http://antirez.com/articoli/tclmisunderstood.html) essay.

**Comment by munificent** [comment]
Ah, good catch, thanks!
