### ISSUE TITLE
Chapter 30 leftover text from issue 895 changes

### ISSUE THREAD

**Issue by jcgoble3** [munificent/craftinginterpreters#936]
In #895, a lot of text and code regarding caching the decrement was rightfully removed. However, there remains this line at the top of section 30.2: "There’s a lot of scaffolding around the change we’ll have to deal with, but the main optimization itself is pint-sized."

Since all of that scaffolding is now gone, this should probably be updated.

**Comment by munificent** [comment]
Nice catch, thank you!
