### ISSUE TITLE
Small grammatical error

### ISSUE THREAD

**Issue by CyberneticSquid** [munificent/craftinginterpreters#938]
From the aside in [3.4.1](https://craftinginterpreters.com/the-lox-language.html#arithmetic)

> A few languages let you define your own operators and control how they are positioned—their “fixity”.

"their" should probably be "they're".

**Comment by texdraft** [comment]
In this case, *fixity* is a noun derived from the suffix &ldquo;-fix&rdquo; in words like *prefix*, *postfix*, *infix*. An operator's fixity is where it is positioned in expressions, in relation to its operandi. Therefore fixity is a property of an operator, and the possessive &ldquo;their&rdquo; is correct.

**Comment by CyberneticSquid** [comment]
Ah, okay. Apologies.
