### ISSUE TITLE
clox: The `name` field of `ClassCompiler` is never used

### ISSUE THREAD

**Issue by ceronman** [munificent/craftinginterpreters#943]
When defining the `ClassCompiler` struct in chapter 28, there is a `name` field.

```c
typedef struct ClassCompiler {
  struct ClassCompiler* enclosing;
  Token name;
} ClassCompiler;
```
I have not found any use of this `name` field anywhere. Perhaps just remove it completely? Or perhaps it could be used to provide some better error messages in some places.

**Comment by munificent** [comment]
Oh, wow. How did I never notice this? That field must have come along when I ported the VM from Wren and I never noticed that I wasn't using the name in error messages anymore.
