### ISSUE TITLE
Inconsistent parameter type for methods define() and assign() (sections 8.3/8.4)

### ISSUE THREAD

**Issue by cakebaker** [munificent/craftinginterpreters#945]
The two methods `define()`and `assign()` of the class `Environment` do almost the same thing but have different types for the `name` parameter:

`void define(String name, Object value)`
vs.
`void assign(Token name, Object value)`

For consistency reasons I suggest to use the same type for both `name` parameters.

**Comment by munificent** [comment]
`assign()` and `get()` take tokens because they may throw a runtime error, which needs the source location. `define()` can never fail, so it takes the bare name.
