### ISSUE TITLE
Doubts about using strucutre

### ISSUE THREAD

**Issue by 724399396** [munificent/craftinginterpreters#957]
Hi,
  Sorry i'm a newbee to c, in clox, Value is constructor like this ``` NUMBER_VAL(value)```, run clox on ubuntu 20.02 desktop, i found Value structure is allocated on stack,  will this cause strucutre in memory bits disturb by another method call?

**Comment by munificent** [comment]
No, it won't cause any problems. When you a return a value on the stack in C, it copies all of the bits.

**Comment by 724399396** [comment]
> No, it won't cause any problems. When you a return a value on the stack in C, it copies all of the bits.

Thanks for your answer, i got it, structure is same as int.
