### ISSUE TITLE
Section 23.1 - Off by 1?

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#960]
In the paragraph immediately following the definition of `emitJump()`, we read the following:

**A 16-bit offset lets us jump over up to 65,536 bytes of code...**

I think the maximum we can jump is 65,535.
I believe a 16-bit unsigned integer can store a maximum integer value of 65535 (2^16 - 1 = 65536 - 1 = 65535) and that's the farthest we can jump.` vm.ip + 0 == vm.ip`

**Comment by munificent** [comment]
Nice catch!
