### ISSUE TITLE
Section 25.4 - A demonstration of truth

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#962]
The very first example in Section 25.4 is as follows:

```
fun outer() {
  var x = "outside";
  fun inner() {
    print x;
  }

  return inner;
}

var closure = outer();
closure();

```
In the paragraph immediately following the example, you go on to state:

**At runtime, it will end up reading from a stack slot that no longer contains the closed-over variable.**

Your statement is indeed correct. However, on my system, when I run the example as shown, "outside" is printed to the screen. Why is this? Well, the answer is that the value of var x is still on the stack and the closure still has a reference to the location of this value.

To demonstrate, beyond all doubt, the truth of your statement to the reader, I suggest you modify the example slightly. Add a statement between `var closure ... `and the call to` closure` that overwrites the value of var x on the stack. Here is an example:

```
var closure = outer();
print 1 + 2;
closure(); // 2 should be be printed
```

**Comment by cm1776** [comment]
Book is published. Too late for any changes.

**Comment by munificent** [comment]
Yeah, I eventually had to just stop changing stuff and kick it out the door. :-/
