### ISSUE TITLE
Really stupid question

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [munificent/craftinginterpreters#966]
Sorry, this is a really dumb question. I'm working my way from the beginning again (after stalling due to work commitments many months ago), and this sentence tripped me up:

> From the user’s perspective, as long as the resulting contraption faithfully follows the language’s specification, it’s all implementation detail.

"user": User of the language you've created? User of the interpreter we're building? User of he resulting app built in your own language?

"resulting contraption": The app that was built using your language? The interpreter we're building?  The language specification itself?

"it’s all implementation detail": What's all implementation detail? The contents of this book? The concerns of the user? The concerns of the interpreter developer?

I understand the gist that "language" can apparently refer to either its implementation or specification, and this book concerns itself with the implementation (which is how a language is turned from raw code into an executable program), but the wording of the above sentence just throws me.

I know it's a very minor thing, but I just thought I'd flag it as I remember it tripping me up many months ago, too.

Can someone explain what Bob is saying?

**Comment by munificent** [comment]
> "user": User of the language you've created? User of the interpreter we're building?

This. These are both saying the same thing. "User" here means a user writing code in our language and running it in our interpreter.

> "resulting contraption": The app that was built using your language? The interpreter we're building? 

The interpreter. :)
