### ISSUE TITLE
Remove Expr.Grouping

### ISSUE THREAD

**Issue by forax** [munificent/craftinginterpreters#98]
Parenthesis are here to allow a user to specify how to parse something, once the grammar is parsed, there is no need for an AST node that represent the fact that the input file has to be parsed in a certain way.

So Expr.Grouping and the corresponding visits that does nothing can be removed.

**Comment by munificent** [comment]
You would think so, but we need it to correct translate assignment expressions. See [here](http://www.craftinginterpreters.com/statements-and-state.html) and search for "parenthesized". :)

**Comment by forax** [comment]
It's because you consider that '(a)' is not a valid left hand side, it's a detail in my opinion.
The important thing is that not all expressions are valid LHS.

I think it's better to say that Expr.Grouping is not necessary when doing the parsing and then note in statements-and-state that because of that it doesn't allow you to reject '(a).'

Keeping Grouping just for a note seems far fetched.

**Comment by munificent** [comment]
> I think it's better to say that Expr.Grouping is not necessary when doing the parsing and then note in statements-and-state that because of that it doesn't allow you to reject '(a).'

I do think it's important to reject `(a) = 1`. I try to keep the book and the code simple where I can, but as much as possible, I'm trying not to cut corners in the language semantics itself. Allowing a piece of syntax that C, C++, JS, C#, Java et al. forbid feels like a misstep just to shave off a few lines of code.

It's also the case that in some parsers you do want to preserve grouping expressions in the AST. If you're say, writing a code formatter, you need that. So I think it's reasonable to give users an example of a parser that does. When we get to clox, it won't reify parenthesized expressions at all (it compiles straight to bytecode with no interleaving AST), so I think it accomplishes some of what you have in mind there.

**Comment by forax** [comment]
> I do think it's important to reject (a) = 1. I try to keep the book and the code simple where I can, but as much as possible, I'm trying not to cut corners in the language semantics itself. Allowing a piece of syntax that C, C++, JS, C#, Java et al. forbid feels like a misstep just to shave off a few lines of code.

Ok, i think you're right here.

> It's also the case that in some parsers you do want to preserve grouping expressions in the AST. If you're say, writing a code formatter, you need that. So I think it's reasonable to give users an example of a parser that does. When we get to clox, it won't reify parenthesized expressions at all (it compiles straight to bytecode with no interleaving AST), so I think it accomplishes some of what you have in mind there.

i'm curious, do you want to use read-only bytecodes like Android or read-write like the JVM ?

**Comment by munificent** [comment]
I'm not sure what you mean by read-write bytecodes. It does a small amount of patching the bytecode during compilation to handle things like jump offsets, but after a chunk of code is done being compiled, the bytecode is no longer modified. Is that what you mean?

**Comment by forax** [comment]
Yes,
so no profiling, cache, lazy initialization, etc

**Comment by munificent** [comment]
Right. That kind of stuff is definitely fun, but a little out of scope for the book.
