### ISSUE TITLE
Congratulations! (And an issue)

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [munificent/craftinginterpreters#983]
Hi Bob, congratulations on the print version becoming a reality! I was just about to purchase a copy when I noticed that Amazon says it's out of stock? Was I too quick?

This is the link in your email:
https://www.amazon.com/dp/0990582930

**Comment by captbaritone** [comment]
For what it's worth I was able to place and order a few minutes ago, and the page still says "in stock" for me.![image](https://user-images.githubusercontent.com/162735/127516122-58cba678-509f-4fdf-9eed-417d87f17c0c.png)

**Comment by munificent** [comment]
It *should* be in stock everywhere, but it can take a while for this stuff to percolate. Were you on Amazon.com or another country's Amazon site?

**Comment by cagix** [comment]
@munificent Congratulations on the successful publication of this book :)  It is available on Amazon.de and I am definitely going to order a copy. Thank you for your great work and for keeping the book sources open source!

**Comment by JohnnyWalkerDesign** [comment]
Strange.

<img width="1044" alt="Screenshot 2021-07-29 at 16 22 08" src="https://user-images.githubusercontent.com/6763222/127519476-008b733b-1c67-4abf-95e4-8b60ce3c0eef.png">

**Comment by JohnnyWalkerDesign** [comment]
Ah, it's the fact that my account was set to ship to the UK. I switched it to my old Pasadena address and now it's available.
