### ISSUE TITLE
Are we allowed to "repurpose" code that was used in the book?

### ISSUE THREAD

**Issue by daresom** [munificent/craftinginterpreters#988]
Hello! Ive been reading Crafting Interpreters for a few weeks and I love it so far, it's understandable and easy to read. On a chapter, specifically 14.3. It's about making, and writing to a dynamic array (chunks). And my mind jumped to some kind of vector (c++ dynamic array) implementation in c. The functions where we learn how to allocate/reallocate memory to the chunk and write to it helped me to get a starting point on how to somewhat implement basic functions of a vector. My plan is to use some of the functions in the book and slowly build up from there. Is this allowed?

**Comment by cagix** [comment]
According to the [`LICENSE`](https://github.com/munificent/craftinginterpreters/blob/master/LICENSE) document, the MIT license applies to the source code.

**Comment by daresom** [comment]
Alright, thanks!

**Comment by munificent** [comment]
@cagix is right. You're free to do whatever you want with the code in the book (but not the text, which is more restricted).
